"""Standalone, off-hot-path Aegis-MX time-series forecast service."""

from aegis_mx_timeseries.adapters import (
    AdapterForecast,
    AdapterResult,
    BaselineAdapter,
    ForecastModelAdapter,
    ReferenceTimesFmAdapter,
    TimesFmAdapter,
    TimesFmBackend,
)
from aegis_mx_timeseries.domain import (
    AdapterDevice,
    AdapterDeviceError,
    AdapterUnavailableError,
    BaselineKind,
    ContextBuilder,
    ContextBuildRequest,
    ForecastContext,
    ForecastTarget,
    KnownFutureCovariate,
    ModelHealth,
    SessionState,
    TimeSeriesPoint,
    WorkerStatus,
    decode_context,
    encode_context,
)
from aegis_mx_timeseries.evaluation import (
    REQUIRED_EVALUATION_TARGETS,
    BaselineMetric,
    EvaluationSeries,
    TargetEvaluation,
    WalkForwardReport,
    compare_baselines_walk_forward,
)
from aegis_mx_timeseries.service import (
    ForecastCache,
    ForecastCacheKey,
    ForecastRequest,
    PublishedForecast,
    ServiceConfig,
    ServiceStatus,
    TimeseriesForecastService,
    WorkerConfig,
    WorkerResult,
)

__all__ = [
    "REQUIRED_EVALUATION_TARGETS",
    "AdapterDevice",
    "AdapterDeviceError",
    "AdapterForecast",
    "AdapterResult",
    "AdapterUnavailableError",
    "BaselineAdapter",
    "BaselineKind",
    "BaselineMetric",
    "ContextBuildRequest",
    "ContextBuilder",
    "EvaluationSeries",
    "ForecastCache",
    "ForecastCacheKey",
    "ForecastContext",
    "ForecastModelAdapter",
    "ForecastRequest",
    "ForecastTarget",
    "KnownFutureCovariate",
    "ModelHealth",
    "PublishedForecast",
    "ReferenceTimesFmAdapter",
    "ServiceConfig",
    "ServiceStatus",
    "SessionState",
    "TargetEvaluation",
    "TimeSeriesPoint",
    "TimesFmAdapter",
    "TimesFmBackend",
    "TimeseriesForecastService",
    "WalkForwardReport",
    "WorkerConfig",
    "WorkerResult",
    "WorkerStatus",
    "compare_baselines_walk_forward",
    "decode_context",
    "encode_context",
]
