from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from aegis.mx.contracts.v1.AuctionSide import AuctionSide
from aegis.mx.contracts.v1.ChannelId import ChannelId
from aegis.mx.contracts.v1.ExchangeEventTimeNs import ExchangeEventTimeNs
from aegis.mx.contracts.v1.GlobalEventId import GlobalEventId
from aegis.mx.contracts.v1.InstrumentId import InstrumentId
from aegis.mx.contracts.v1.NicReceiveTimeNs import NicReceiveTimeNs
from aegis.mx.contracts.v1.PriceUnit import PriceUnit
from aegis.mx.contracts.v1.ProcessMonotonicTimeNs import ProcessMonotonicTimeNs
from aegis.mx.contracts.v1.QuantityUnit import QuantityUnit
from aegis.mx.contracts.v1.SchemaVersion import SchemaVersion
from aegis.mx.contracts.v1.SessionId import SessionId
from aegis.mx.contracts.v1.VenueId import VenueId

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class AuctionImbalance:
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> AuctionImbalance: ...
  @classmethod
  def GetRootAsAuctionImbalance(cls, buf: bytes, offset: int) -> AuctionImbalance: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def SchemaVersion(self) -> SchemaVersion | None: ...
  def GlobalEventId(self) -> GlobalEventId | None: ...
  def SessionId(self) -> SessionId | None: ...
  def VenueId(self) -> VenueId | None: ...
  def InstrumentId(self) -> InstrumentId | None: ...
  def ChannelId(self) -> ChannelId | None: ...
  def ChannelSequence(self) -> int: ...
  def ExchangeEventTime(self) -> ExchangeEventTimeNs | None: ...
  def NicReceiveTime(self) -> NicReceiveTimeNs | None: ...
  def ProcessMonotonicTime(self) -> ProcessMonotonicTimeNs | None: ...
  def ImbalanceSide(self) -> typing.Literal[AuctionSide.UNKNOWN, AuctionSide.BUY_IMBALANCE, AuctionSide.SELL_IMBALANCE, AuctionSide.PAIRED]: ...
  def PriceUnit(self) -> typing.Literal[PriceUnit.UNKNOWN, PriceUnit.TICKS]: ...
  def IndicativePriceTicks(self) -> int: ...
  def QuantityUnit(self) -> typing.Literal[QuantityUnit.UNKNOWN, QuantityUnit.INSTRUMENT_UNITS]: ...
  def ImbalanceQuantityUnits(self) -> int: ...
  def PairedQuantityUnits(self) -> int: ...
def AuctionImbalanceStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def AuctionImbalanceAddSchemaVersion(builder: flatbuffers.Builder, schemaVersion: uoffset) -> None: ...
def AuctionImbalanceAddGlobalEventId(builder: flatbuffers.Builder, globalEventId: uoffset) -> None: ...
def AuctionImbalanceAddSessionId(builder: flatbuffers.Builder, sessionId: uoffset) -> None: ...
def AuctionImbalanceAddVenueId(builder: flatbuffers.Builder, venueId: uoffset) -> None: ...
def AuctionImbalanceAddInstrumentId(builder: flatbuffers.Builder, instrumentId: uoffset) -> None: ...
def AuctionImbalanceAddChannelId(builder: flatbuffers.Builder, channelId: uoffset) -> None: ...
def AuctionImbalanceAddChannelSequence(builder: flatbuffers.Builder, channelSequence: int) -> None: ...
def AuctionImbalanceAddExchangeEventTime(builder: flatbuffers.Builder, exchangeEventTime: uoffset) -> None: ...
def AuctionImbalanceAddNicReceiveTime(builder: flatbuffers.Builder, nicReceiveTime: uoffset) -> None: ...
def AuctionImbalanceAddProcessMonotonicTime(builder: flatbuffers.Builder, processMonotonicTime: uoffset) -> None: ...
def AuctionImbalanceAddImbalanceSide(builder: flatbuffers.Builder, imbalanceSide: typing.Literal[AuctionSide.UNKNOWN, AuctionSide.BUY_IMBALANCE, AuctionSide.SELL_IMBALANCE, AuctionSide.PAIRED]) -> None: ...
def AuctionImbalanceAddPriceUnit(builder: flatbuffers.Builder, priceUnit: typing.Literal[PriceUnit.UNKNOWN, PriceUnit.TICKS]) -> None: ...
def AuctionImbalanceAddIndicativePriceTicks(builder: flatbuffers.Builder, indicativePriceTicks: int) -> None: ...
def AuctionImbalanceAddQuantityUnit(builder: flatbuffers.Builder, quantityUnit: typing.Literal[QuantityUnit.UNKNOWN, QuantityUnit.INSTRUMENT_UNITS]) -> None: ...
def AuctionImbalanceAddImbalanceQuantityUnits(builder: flatbuffers.Builder, imbalanceQuantityUnits: int) -> None: ...
def AuctionImbalanceAddPairedQuantityUnits(builder: flatbuffers.Builder, pairedQuantityUnits: int) -> None: ...
def AuctionImbalanceEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

