# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from aegis.mx.contracts.v1.ConfigurationVersion import ConfigurationVersion
from aegis.mx.contracts.v1.GlobalEventId import GlobalEventId
from aegis.mx.contracts.v1.ProcessMonotonicTimeNs import ProcessMonotonicTimeNs
from aegis.mx.contracts.v1.SchemaVersion import SchemaVersion
from aegis.mx.contracts.v1.SessionId import SessionId
from aegis.mx.contracts.v1.Sha256Digest import Sha256Digest
from aegis.mx.contracts.v1.WallClockUtcTimeNs import WallClockUtcTimeNs
from typing import Optional
np = import_numpy()

class AuditEnvelope(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = AuditEnvelope()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsAuditEnvelope(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def AuditEnvelopeBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x41\x4D\x41\x45", size_prefixed=size_prefixed)

    # AuditEnvelope
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # AuditEnvelope
    def SchemaVersion(self) -> Optional[SchemaVersion]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            obj = SchemaVersion()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # AuditEnvelope
    def EnvelopeId(self) -> Optional[GlobalEventId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            obj = GlobalEventId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # AuditEnvelope
    def SessionId(self) -> Optional[SessionId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = o + self._tab.Pos
            obj = SessionId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # AuditEnvelope
    def ConfigurationVersion(self) -> Optional[ConfigurationVersion]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = o + self._tab.Pos
            obj = ConfigurationVersion()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # AuditEnvelope
    def CreatedProcessMonotonicTime(self) -> Optional[ProcessMonotonicTimeNs]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = o + self._tab.Pos
            obj = ProcessMonotonicTimeNs()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # AuditEnvelope
    def RecordedWallClockUtcTime(self) -> Optional[WallClockUtcTimeNs]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = o + self._tab.Pos
            obj = WallClockUtcTimeNs()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # AuditEnvelope
    def RecordType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # AuditEnvelope
    def Payload(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # AuditEnvelope
    def PayloadAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # AuditEnvelope
    def PayloadLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # AuditEnvelope
    def PayloadIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        return o == 0

    # AuditEnvelope
    def PayloadSha256(self) -> Optional[Sha256Digest]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            x = o + self._tab.Pos
            obj = Sha256Digest()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # AuditEnvelope
    def PreviousEnvelopeSha256(self) -> Optional[Sha256Digest]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            x = o + self._tab.Pos
            obj = Sha256Digest()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def AuditEnvelopeStart(builder: flatbuffers.Builder):
    builder.StartObject(10)

def Start(builder: flatbuffers.Builder):
    AuditEnvelopeStart(builder)

def AuditEnvelopeAddSchemaVersion(builder: flatbuffers.Builder, schemaVersion: Any):
    builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(schemaVersion), 0)

def AddSchemaVersion(builder: flatbuffers.Builder, schemaVersion: Any):
    AuditEnvelopeAddSchemaVersion(builder, schemaVersion)

def AuditEnvelopeAddEnvelopeId(builder: flatbuffers.Builder, envelopeId: Any):
    builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(envelopeId), 0)

def AddEnvelopeId(builder: flatbuffers.Builder, envelopeId: Any):
    AuditEnvelopeAddEnvelopeId(builder, envelopeId)

def AuditEnvelopeAddSessionId(builder: flatbuffers.Builder, sessionId: Any):
    builder.PrependStructSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(sessionId), 0)

def AddSessionId(builder: flatbuffers.Builder, sessionId: Any):
    AuditEnvelopeAddSessionId(builder, sessionId)

def AuditEnvelopeAddConfigurationVersion(builder: flatbuffers.Builder, configurationVersion: Any):
    builder.PrependStructSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(configurationVersion), 0)

def AddConfigurationVersion(builder: flatbuffers.Builder, configurationVersion: Any):
    AuditEnvelopeAddConfigurationVersion(builder, configurationVersion)

def AuditEnvelopeAddCreatedProcessMonotonicTime(builder: flatbuffers.Builder, createdProcessMonotonicTime: Any):
    builder.PrependStructSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(createdProcessMonotonicTime), 0)

def AddCreatedProcessMonotonicTime(builder: flatbuffers.Builder, createdProcessMonotonicTime: Any):
    AuditEnvelopeAddCreatedProcessMonotonicTime(builder, createdProcessMonotonicTime)

def AuditEnvelopeAddRecordedWallClockUtcTime(builder: flatbuffers.Builder, recordedWallClockUtcTime: Any):
    builder.PrependStructSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(recordedWallClockUtcTime), 0)

def AddRecordedWallClockUtcTime(builder: flatbuffers.Builder, recordedWallClockUtcTime: Any):
    AuditEnvelopeAddRecordedWallClockUtcTime(builder, recordedWallClockUtcTime)

def AuditEnvelopeAddRecordType(builder: flatbuffers.Builder, recordType: int):
    builder.PrependUint8Slot(6, recordType, 0)

def AddRecordType(builder: flatbuffers.Builder, recordType: int):
    AuditEnvelopeAddRecordType(builder, recordType)

def AuditEnvelopeAddPayload(builder: flatbuffers.Builder, payload: int):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(payload), 0)

def AddPayload(builder: flatbuffers.Builder, payload: int):
    AuditEnvelopeAddPayload(builder, payload)

def AuditEnvelopeStartPayloadVector(builder, numElems: int) -> int:
    return builder.StartVector(1, numElems, 1)

def StartPayloadVector(builder, numElems: int) -> int:
    return AuditEnvelopeStartPayloadVector(builder, numElems)

def AuditEnvelopeAddPayloadSha256(builder: flatbuffers.Builder, payloadSha256: Any):
    builder.PrependStructSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(payloadSha256), 0)

def AddPayloadSha256(builder: flatbuffers.Builder, payloadSha256: Any):
    AuditEnvelopeAddPayloadSha256(builder, payloadSha256)

def AuditEnvelopeAddPreviousEnvelopeSha256(builder: flatbuffers.Builder, previousEnvelopeSha256: Any):
    builder.PrependStructSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(previousEnvelopeSha256), 0)

def AddPreviousEnvelopeSha256(builder: flatbuffers.Builder, previousEnvelopeSha256: Any):
    AuditEnvelopeAddPreviousEnvelopeSha256(builder, previousEnvelopeSha256)

def AuditEnvelopeEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return AuditEnvelopeEnd(builder)
