from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from aegis.mx.contracts.v1.ConfigurationVersion import ConfigurationVersion
from aegis.mx.contracts.v1.GlobalEventId import GlobalEventId
from aegis.mx.contracts.v1.ProcessMonotonicTimeNs import ProcessMonotonicTimeNs
from aegis.mx.contracts.v1.RecordType import RecordType
from aegis.mx.contracts.v1.SchemaVersion import SchemaVersion
from aegis.mx.contracts.v1.SessionId import SessionId
from aegis.mx.contracts.v1.Sha256Digest import Sha256Digest
from aegis.mx.contracts.v1.WallClockUtcTimeNs import WallClockUtcTimeNs

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class AuditEnvelope:
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> AuditEnvelope: ...
  @classmethod
  def GetRootAsAuditEnvelope(cls, buf: bytes, offset: int) -> AuditEnvelope: ...
  @classmethod
  def AuditEnvelopeBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def SchemaVersion(self) -> SchemaVersion | None: ...
  def EnvelopeId(self) -> GlobalEventId | None: ...
  def SessionId(self) -> SessionId | None: ...
  def ConfigurationVersion(self) -> ConfigurationVersion | None: ...
  def CreatedProcessMonotonicTime(self) -> ProcessMonotonicTimeNs | None: ...
  def RecordedWallClockUtcTime(self) -> WallClockUtcTimeNs | None: ...
  def RecordType(self) -> typing.Literal[RecordType.UNKNOWN, RecordType.INSTRUMENT_REFERENCE_DATA, RecordType.MARKET_EVENT, RecordType.BOOK_UPDATE, RecordType.TRADE_EVENT, RecordType.QUOTE_EVENT, RecordType.AUCTION_IMBALANCE, RecordType.TRADING_STATUS, RecordType.FEATURE_SNAPSHOT_METADATA, RecordType.MODEL_FORECAST, RecordType.ENSEMBLE_FORECAST, RecordType.ORDER_INTENT, RecordType.RISK_DECISION, RecordType.ORDER_EVENT, RecordType.FILL_EVENT, RecordType.POSITION_SNAPSHOT, RecordType.EVENT_INTELLIGENCE_RECORD, RecordType.DATA_QUALITY_STATE, RecordType.CLOCK_QUALITY_STATE, RecordType.KILL_SWITCH_EVENT]: ...
  def Payload(self, i: int) -> typing.List[int]: ...
  def PayloadAsNumpy(self) -> np.ndarray: ...
  def PayloadLength(self) -> int: ...
  def PayloadIsNone(self) -> bool: ...
  def PayloadSha256(self) -> Sha256Digest | None: ...
  def PreviousEnvelopeSha256(self) -> Sha256Digest | None: ...
def AuditEnvelopeStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def AuditEnvelopeAddSchemaVersion(builder: flatbuffers.Builder, schemaVersion: uoffset) -> None: ...
def AuditEnvelopeAddEnvelopeId(builder: flatbuffers.Builder, envelopeId: uoffset) -> None: ...
def AuditEnvelopeAddSessionId(builder: flatbuffers.Builder, sessionId: uoffset) -> None: ...
def AuditEnvelopeAddConfigurationVersion(builder: flatbuffers.Builder, configurationVersion: uoffset) -> None: ...
def AuditEnvelopeAddCreatedProcessMonotonicTime(builder: flatbuffers.Builder, createdProcessMonotonicTime: uoffset) -> None: ...
def AuditEnvelopeAddRecordedWallClockUtcTime(builder: flatbuffers.Builder, recordedWallClockUtcTime: uoffset) -> None: ...
def AuditEnvelopeAddRecordType(builder: flatbuffers.Builder, recordType: typing.Literal[RecordType.UNKNOWN, RecordType.INSTRUMENT_REFERENCE_DATA, RecordType.MARKET_EVENT, RecordType.BOOK_UPDATE, RecordType.TRADE_EVENT, RecordType.QUOTE_EVENT, RecordType.AUCTION_IMBALANCE, RecordType.TRADING_STATUS, RecordType.FEATURE_SNAPSHOT_METADATA, RecordType.MODEL_FORECAST, RecordType.ENSEMBLE_FORECAST, RecordType.ORDER_INTENT, RecordType.RISK_DECISION, RecordType.ORDER_EVENT, RecordType.FILL_EVENT, RecordType.POSITION_SNAPSHOT, RecordType.EVENT_INTELLIGENCE_RECORD, RecordType.DATA_QUALITY_STATE, RecordType.CLOCK_QUALITY_STATE, RecordType.KILL_SWITCH_EVENT]) -> None: ...
def AuditEnvelopeAddPayload(builder: flatbuffers.Builder, payload: uoffset) -> None: ...
def AuditEnvelopeStartPayloadVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartPayloadVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def AuditEnvelopeAddPayloadSha256(builder: flatbuffers.Builder, payloadSha256: uoffset) -> None: ...
def AuditEnvelopeAddPreviousEnvelopeSha256(builder: flatbuffers.Builder, previousEnvelopeSha256: uoffset) -> None: ...
def AuditEnvelopeEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

