from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from aegis.mx.contracts.v1.BookAction import BookAction
from aegis.mx.contracts.v1.BookSide import BookSide
from aegis.mx.contracts.v1.ChannelId import ChannelId
from aegis.mx.contracts.v1.ExchangeEventTimeNs import ExchangeEventTimeNs
from aegis.mx.contracts.v1.GlobalEventId import GlobalEventId
from aegis.mx.contracts.v1.InstrumentId import InstrumentId
from aegis.mx.contracts.v1.NicReceiveTimeNs import NicReceiveTimeNs
from aegis.mx.contracts.v1.PriceUnit import PriceUnit
from aegis.mx.contracts.v1.ProcessMonotonicTimeNs import ProcessMonotonicTimeNs
from aegis.mx.contracts.v1.QuantityUnit import QuantityUnit
from aegis.mx.contracts.v1.SchemaVersion import SchemaVersion
from aegis.mx.contracts.v1.SessionId import SessionId
from aegis.mx.contracts.v1.VenueId import VenueId

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class BookUpdate:
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> BookUpdate: ...
  @classmethod
  def GetRootAsBookUpdate(cls, buf: bytes, offset: int) -> BookUpdate: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def SchemaVersion(self) -> SchemaVersion | None: ...
  def GlobalEventId(self) -> GlobalEventId | None: ...
  def SessionId(self) -> SessionId | None: ...
  def VenueId(self) -> VenueId | None: ...
  def InstrumentId(self) -> InstrumentId | None: ...
  def ChannelId(self) -> ChannelId | None: ...
  def ChannelSequence(self) -> int: ...
  def ExchangeEventTime(self) -> ExchangeEventTimeNs | None: ...
  def NicReceiveTime(self) -> NicReceiveTimeNs | None: ...
  def ProcessMonotonicTime(self) -> ProcessMonotonicTimeNs | None: ...
  def Side(self) -> typing.Literal[BookSide.UNKNOWN, BookSide.BID, BookSide.ASK]: ...
  def Action(self) -> typing.Literal[BookAction.UNKNOWN, BookAction.ADD, BookAction.CHANGE, BookAction.DELETE, BookAction.CLEAR_SIDE, BookAction.CLEAR_BOOK]: ...
  def PriceUnit(self) -> typing.Literal[PriceUnit.UNKNOWN, PriceUnit.TICKS]: ...
  def PriceTicks(self) -> int: ...
  def QuantityUnit(self) -> typing.Literal[QuantityUnit.UNKNOWN, QuantityUnit.INSTRUMENT_UNITS]: ...
  def QuantityUnits(self) -> int: ...
  def OrderCount(self) -> int: ...
def BookUpdateStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def BookUpdateAddSchemaVersion(builder: flatbuffers.Builder, schemaVersion: uoffset) -> None: ...
def BookUpdateAddGlobalEventId(builder: flatbuffers.Builder, globalEventId: uoffset) -> None: ...
def BookUpdateAddSessionId(builder: flatbuffers.Builder, sessionId: uoffset) -> None: ...
def BookUpdateAddVenueId(builder: flatbuffers.Builder, venueId: uoffset) -> None: ...
def BookUpdateAddInstrumentId(builder: flatbuffers.Builder, instrumentId: uoffset) -> None: ...
def BookUpdateAddChannelId(builder: flatbuffers.Builder, channelId: uoffset) -> None: ...
def BookUpdateAddChannelSequence(builder: flatbuffers.Builder, channelSequence: int) -> None: ...
def BookUpdateAddExchangeEventTime(builder: flatbuffers.Builder, exchangeEventTime: uoffset) -> None: ...
def BookUpdateAddNicReceiveTime(builder: flatbuffers.Builder, nicReceiveTime: uoffset) -> None: ...
def BookUpdateAddProcessMonotonicTime(builder: flatbuffers.Builder, processMonotonicTime: uoffset) -> None: ...
def BookUpdateAddSide(builder: flatbuffers.Builder, side: typing.Literal[BookSide.UNKNOWN, BookSide.BID, BookSide.ASK]) -> None: ...
def BookUpdateAddAction(builder: flatbuffers.Builder, action: typing.Literal[BookAction.UNKNOWN, BookAction.ADD, BookAction.CHANGE, BookAction.DELETE, BookAction.CLEAR_SIDE, BookAction.CLEAR_BOOK]) -> None: ...
def BookUpdateAddPriceUnit(builder: flatbuffers.Builder, priceUnit: typing.Literal[PriceUnit.UNKNOWN, PriceUnit.TICKS]) -> None: ...
def BookUpdateAddPriceTicks(builder: flatbuffers.Builder, priceTicks: int) -> None: ...
def BookUpdateAddQuantityUnit(builder: flatbuffers.Builder, quantityUnit: typing.Literal[QuantityUnit.UNKNOWN, QuantityUnit.INSTRUMENT_UNITS]) -> None: ...
def BookUpdateAddQuantityUnits(builder: flatbuffers.Builder, quantityUnits: int) -> None: ...
def BookUpdateAddOrderCount(builder: flatbuffers.Builder, orderCount: int) -> None: ...
def BookUpdateEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

