# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

class BookAction(object):
    UNKNOWN = 0
    ADD = 1
    CHANGE = 2
    DELETE = 3
    CLEAR_SIDE = 4
    CLEAR_BOOK = 5
