# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

class ClockQualityCode(object):
    UNKNOWN = 0
    SYNCHRONIZED = 1
    HOLDOVER = 2
    UNSYNCHRONIZED = 3
    INVALID = 4
