# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from aegis.mx.contracts.v1.ChannelId import ChannelId
from aegis.mx.contracts.v1.ProcessMonotonicTimeNs import ProcessMonotonicTimeNs
from aegis.mx.contracts.v1.SchemaVersion import SchemaVersion
from aegis.mx.contracts.v1.WallClockUtcTimeNs import WallClockUtcTimeNs
from typing import Optional
np = import_numpy()

class ClockQualityState(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ClockQualityState()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsClockQualityState(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ClockQualityState
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ClockQualityState
    def SchemaVersion(self) -> Optional[SchemaVersion]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            obj = SchemaVersion()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ClockQualityState
    def SourceChannelId(self) -> Optional[ChannelId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            obj = ChannelId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ClockQualityState
    def State(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # ClockQualityState
    def ObservedProcessMonotonicTime(self) -> Optional[ProcessMonotonicTimeNs]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = o + self._tab.Pos
            obj = ProcessMonotonicTimeNs()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ClockQualityState
    def ObservedWallClockUtcTime(self) -> Optional[WallClockUtcTimeNs]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = o + self._tab.Pos
            obj = WallClockUtcTimeNs()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ClockQualityState
    def OffsetFromReferenceNs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ClockQualityState
    def UncertaintyNs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # ClockQualityState
    def MaximumPermittedUncertaintyNs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def ClockQualityStateStart(builder: flatbuffers.Builder):
    builder.StartObject(8)

def Start(builder: flatbuffers.Builder):
    ClockQualityStateStart(builder)

def ClockQualityStateAddSchemaVersion(builder: flatbuffers.Builder, schemaVersion: Any):
    builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(schemaVersion), 0)

def AddSchemaVersion(builder: flatbuffers.Builder, schemaVersion: Any):
    ClockQualityStateAddSchemaVersion(builder, schemaVersion)

def ClockQualityStateAddSourceChannelId(builder: flatbuffers.Builder, sourceChannelId: Any):
    builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(sourceChannelId), 0)

def AddSourceChannelId(builder: flatbuffers.Builder, sourceChannelId: Any):
    ClockQualityStateAddSourceChannelId(builder, sourceChannelId)

def ClockQualityStateAddState(builder: flatbuffers.Builder, state: int):
    builder.PrependUint8Slot(2, state, 0)

def AddState(builder: flatbuffers.Builder, state: int):
    ClockQualityStateAddState(builder, state)

def ClockQualityStateAddObservedProcessMonotonicTime(builder: flatbuffers.Builder, observedProcessMonotonicTime: Any):
    builder.PrependStructSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(observedProcessMonotonicTime), 0)

def AddObservedProcessMonotonicTime(builder: flatbuffers.Builder, observedProcessMonotonicTime: Any):
    ClockQualityStateAddObservedProcessMonotonicTime(builder, observedProcessMonotonicTime)

def ClockQualityStateAddObservedWallClockUtcTime(builder: flatbuffers.Builder, observedWallClockUtcTime: Any):
    builder.PrependStructSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(observedWallClockUtcTime), 0)

def AddObservedWallClockUtcTime(builder: flatbuffers.Builder, observedWallClockUtcTime: Any):
    ClockQualityStateAddObservedWallClockUtcTime(builder, observedWallClockUtcTime)

def ClockQualityStateAddOffsetFromReferenceNs(builder: flatbuffers.Builder, offsetFromReferenceNs: int):
    builder.PrependInt64Slot(5, offsetFromReferenceNs, 0)

def AddOffsetFromReferenceNs(builder: flatbuffers.Builder, offsetFromReferenceNs: int):
    ClockQualityStateAddOffsetFromReferenceNs(builder, offsetFromReferenceNs)

def ClockQualityStateAddUncertaintyNs(builder: flatbuffers.Builder, uncertaintyNs: int):
    builder.PrependUint64Slot(6, uncertaintyNs, 0)

def AddUncertaintyNs(builder: flatbuffers.Builder, uncertaintyNs: int):
    ClockQualityStateAddUncertaintyNs(builder, uncertaintyNs)

def ClockQualityStateAddMaximumPermittedUncertaintyNs(builder: flatbuffers.Builder, maximumPermittedUncertaintyNs: int):
    builder.PrependUint64Slot(7, maximumPermittedUncertaintyNs, 0)

def AddMaximumPermittedUncertaintyNs(builder: flatbuffers.Builder, maximumPermittedUncertaintyNs: int):
    ClockQualityStateAddMaximumPermittedUncertaintyNs(builder, maximumPermittedUncertaintyNs)

def ClockQualityStateEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return ClockQualityStateEnd(builder)
