from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from aegis.mx.contracts.v1.ChannelId import ChannelId
from aegis.mx.contracts.v1.ClockQualityCode import ClockQualityCode
from aegis.mx.contracts.v1.ProcessMonotonicTimeNs import ProcessMonotonicTimeNs
from aegis.mx.contracts.v1.SchemaVersion import SchemaVersion
from aegis.mx.contracts.v1.WallClockUtcTimeNs import WallClockUtcTimeNs

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class ClockQualityState:
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> ClockQualityState: ...
  @classmethod
  def GetRootAsClockQualityState(cls, buf: bytes, offset: int) -> ClockQualityState: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def SchemaVersion(self) -> SchemaVersion | None: ...
  def SourceChannelId(self) -> ChannelId | None: ...
  def State(self) -> typing.Literal[ClockQualityCode.UNKNOWN, ClockQualityCode.SYNCHRONIZED, ClockQualityCode.HOLDOVER, ClockQualityCode.UNSYNCHRONIZED, ClockQualityCode.INVALID]: ...
  def ObservedProcessMonotonicTime(self) -> ProcessMonotonicTimeNs | None: ...
  def ObservedWallClockUtcTime(self) -> WallClockUtcTimeNs | None: ...
  def OffsetFromReferenceNs(self) -> int: ...
  def UncertaintyNs(self) -> int: ...
  def MaximumPermittedUncertaintyNs(self) -> int: ...
def ClockQualityStateStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def ClockQualityStateAddSchemaVersion(builder: flatbuffers.Builder, schemaVersion: uoffset) -> None: ...
def ClockQualityStateAddSourceChannelId(builder: flatbuffers.Builder, sourceChannelId: uoffset) -> None: ...
def ClockQualityStateAddState(builder: flatbuffers.Builder, state: typing.Literal[ClockQualityCode.UNKNOWN, ClockQualityCode.SYNCHRONIZED, ClockQualityCode.HOLDOVER, ClockQualityCode.UNSYNCHRONIZED, ClockQualityCode.INVALID]) -> None: ...
def ClockQualityStateAddObservedProcessMonotonicTime(builder: flatbuffers.Builder, observedProcessMonotonicTime: uoffset) -> None: ...
def ClockQualityStateAddObservedWallClockUtcTime(builder: flatbuffers.Builder, observedWallClockUtcTime: uoffset) -> None: ...
def ClockQualityStateAddOffsetFromReferenceNs(builder: flatbuffers.Builder, offsetFromReferenceNs: int) -> None: ...
def ClockQualityStateAddUncertaintyNs(builder: flatbuffers.Builder, uncertaintyNs: int) -> None: ...
def ClockQualityStateAddMaximumPermittedUncertaintyNs(builder: flatbuffers.Builder, maximumPermittedUncertaintyNs: int) -> None: ...
def ClockQualityStateEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

