# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from aegis.mx.contracts.v1.GlobalEventId import GlobalEventId
from aegis.mx.contracts.v1.SchemaVersion import SchemaVersion
from flatbuffers.table import Table
from typing import Optional
np = import_numpy()

class ContractRecord(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ContractRecord()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsContractRecord(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def ContractRecordBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x41\x4D\x43\x52", size_prefixed=size_prefixed)

    # ContractRecord
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ContractRecord
    def SchemaVersion(self) -> Optional[SchemaVersion]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            obj = SchemaVersion()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ContractRecord
    def RecordId(self) -> Optional[GlobalEventId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            obj = GlobalEventId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ContractRecord
    def RecordType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # ContractRecord
    def PayloadType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # ContractRecord
    def Payload(self) -> Optional[flatbuffers.table.Table]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def ContractRecordStart(builder: flatbuffers.Builder):
    builder.StartObject(5)

def Start(builder: flatbuffers.Builder):
    ContractRecordStart(builder)

def ContractRecordAddSchemaVersion(builder: flatbuffers.Builder, schemaVersion: Any):
    builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(schemaVersion), 0)

def AddSchemaVersion(builder: flatbuffers.Builder, schemaVersion: Any):
    ContractRecordAddSchemaVersion(builder, schemaVersion)

def ContractRecordAddRecordId(builder: flatbuffers.Builder, recordId: Any):
    builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(recordId), 0)

def AddRecordId(builder: flatbuffers.Builder, recordId: Any):
    ContractRecordAddRecordId(builder, recordId)

def ContractRecordAddRecordType(builder: flatbuffers.Builder, recordType: int):
    builder.PrependUint8Slot(2, recordType, 0)

def AddRecordType(builder: flatbuffers.Builder, recordType: int):
    ContractRecordAddRecordType(builder, recordType)

def ContractRecordAddPayloadType(builder: flatbuffers.Builder, payloadType: int):
    builder.PrependUint8Slot(3, payloadType, 0)

def AddPayloadType(builder: flatbuffers.Builder, payloadType: int):
    ContractRecordAddPayloadType(builder, payloadType)

def ContractRecordAddPayload(builder: flatbuffers.Builder, payload: int):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(payload), 0)

def AddPayload(builder: flatbuffers.Builder, payload: int):
    ContractRecordAddPayload(builder, payload)

def ContractRecordEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return ContractRecordEnd(builder)
