from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from aegis.mx.contracts.v1.ContractPayload import ContractPayload
from aegis.mx.contracts.v1.GlobalEventId import GlobalEventId
from aegis.mx.contracts.v1.RecordType import RecordType
from aegis.mx.contracts.v1.SchemaVersion import SchemaVersion
from flatbuffers import table

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class ContractRecord:
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> ContractRecord: ...
  @classmethod
  def GetRootAsContractRecord(cls, buf: bytes, offset: int) -> ContractRecord: ...
  @classmethod
  def ContractRecordBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def SchemaVersion(self) -> SchemaVersion | None: ...
  def RecordId(self) -> GlobalEventId | None: ...
  def RecordType(self) -> typing.Literal[RecordType.UNKNOWN, RecordType.INSTRUMENT_REFERENCE_DATA, RecordType.MARKET_EVENT, RecordType.BOOK_UPDATE, RecordType.TRADE_EVENT, RecordType.QUOTE_EVENT, RecordType.AUCTION_IMBALANCE, RecordType.TRADING_STATUS, RecordType.FEATURE_SNAPSHOT_METADATA, RecordType.MODEL_FORECAST, RecordType.ENSEMBLE_FORECAST, RecordType.ORDER_INTENT, RecordType.RISK_DECISION, RecordType.ORDER_EVENT, RecordType.FILL_EVENT, RecordType.POSITION_SNAPSHOT, RecordType.EVENT_INTELLIGENCE_RECORD, RecordType.DATA_QUALITY_STATE, RecordType.CLOCK_QUALITY_STATE, RecordType.KILL_SWITCH_EVENT]: ...
  def PayloadType(self) -> typing.Literal[ContractPayload.NONE, ContractPayload.InstrumentReferenceData, ContractPayload.MarketEvent, ContractPayload.BookUpdate, ContractPayload.TradeEvent, ContractPayload.QuoteEvent, ContractPayload.AuctionImbalance, ContractPayload.TradingStatus, ContractPayload.FeatureSnapshotMetadata, ContractPayload.ModelForecast, ContractPayload.EnsembleForecast, ContractPayload.OrderIntent, ContractPayload.RiskDecision, ContractPayload.OrderEvent, ContractPayload.FillEvent, ContractPayload.PositionSnapshot, ContractPayload.EventIntelligenceRecord, ContractPayload.DataQualityState, ContractPayload.ClockQualityState, ContractPayload.KillSwitchEvent]: ...
  def Payload(self) -> table.Table | None: ...
def ContractRecordStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def ContractRecordAddSchemaVersion(builder: flatbuffers.Builder, schemaVersion: uoffset) -> None: ...
def ContractRecordAddRecordId(builder: flatbuffers.Builder, recordId: uoffset) -> None: ...
def ContractRecordAddRecordType(builder: flatbuffers.Builder, recordType: typing.Literal[RecordType.UNKNOWN, RecordType.INSTRUMENT_REFERENCE_DATA, RecordType.MARKET_EVENT, RecordType.BOOK_UPDATE, RecordType.TRADE_EVENT, RecordType.QUOTE_EVENT, RecordType.AUCTION_IMBALANCE, RecordType.TRADING_STATUS, RecordType.FEATURE_SNAPSHOT_METADATA, RecordType.MODEL_FORECAST, RecordType.ENSEMBLE_FORECAST, RecordType.ORDER_INTENT, RecordType.RISK_DECISION, RecordType.ORDER_EVENT, RecordType.FILL_EVENT, RecordType.POSITION_SNAPSHOT, RecordType.EVENT_INTELLIGENCE_RECORD, RecordType.DATA_QUALITY_STATE, RecordType.CLOCK_QUALITY_STATE, RecordType.KILL_SWITCH_EVENT]) -> None: ...
def ContractRecordAddPayloadType(builder: flatbuffers.Builder, payloadType: typing.Literal[ContractPayload.NONE, ContractPayload.InstrumentReferenceData, ContractPayload.MarketEvent, ContractPayload.BookUpdate, ContractPayload.TradeEvent, ContractPayload.QuoteEvent, ContractPayload.AuctionImbalance, ContractPayload.TradingStatus, ContractPayload.FeatureSnapshotMetadata, ContractPayload.ModelForecast, ContractPayload.EnsembleForecast, ContractPayload.OrderIntent, ContractPayload.RiskDecision, ContractPayload.OrderEvent, ContractPayload.FillEvent, ContractPayload.PositionSnapshot, ContractPayload.EventIntelligenceRecord, ContractPayload.DataQualityState, ContractPayload.ClockQualityState, ContractPayload.KillSwitchEvent]) -> None: ...
def ContractRecordAddPayload(builder: flatbuffers.Builder, payload: uoffset) -> None: ...
def ContractRecordEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

