# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

class ContractPayload(object):
    NONE = 0
    InstrumentReferenceData = 1
    MarketEvent = 2
    BookUpdate = 3
    TradeEvent = 4
    QuoteEvent = 5
    AuctionImbalance = 6
    TradingStatus = 7
    FeatureSnapshotMetadata = 8
    ModelForecast = 9
    EnsembleForecast = 10
    OrderIntent = 11
    RiskDecision = 12
    OrderEvent = 13
    FillEvent = 14
    PositionSnapshot = 15
    EventIntelligenceRecord = 16
    DataQualityState = 17
    ClockQualityState = 18
    KillSwitchEvent = 19
