# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from aegis.mx.contracts.v1.ChannelId import ChannelId
from aegis.mx.contracts.v1.ExchangeEventTimeNs import ExchangeEventTimeNs
from aegis.mx.contracts.v1.NicReceiveTimeNs import NicReceiveTimeNs
from aegis.mx.contracts.v1.ProcessMonotonicTimeNs import ProcessMonotonicTimeNs
from aegis.mx.contracts.v1.SchemaVersion import SchemaVersion
from aegis.mx.contracts.v1.VenueId import VenueId
from typing import Optional
np = import_numpy()

class DataQualityState(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DataQualityState()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDataQualityState(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # DataQualityState
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DataQualityState
    def SchemaVersion(self) -> Optional[SchemaVersion]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            obj = SchemaVersion()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # DataQualityState
    def VenueId(self) -> Optional[VenueId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            obj = VenueId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # DataQualityState
    def ChannelId(self) -> Optional[ChannelId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = o + self._tab.Pos
            obj = ChannelId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # DataQualityState
    def State(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # DataQualityState
    def ObservedProcessMonotonicTime(self) -> Optional[ProcessMonotonicTimeNs]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = o + self._tab.Pos
            obj = ProcessMonotonicTimeNs()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # DataQualityState
    def LastGoodExchangeEventTime(self) -> Optional[ExchangeEventTimeNs]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = o + self._tab.Pos
            obj = ExchangeEventTimeNs()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # DataQualityState
    def LastGoodNicReceiveTime(self) -> Optional[NicReceiveTimeNs]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            x = o + self._tab.Pos
            obj = NicReceiveTimeNs()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # DataQualityState
    def MissingSequenceCount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # DataQualityState
    def MalformedRecordCount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # DataQualityState
    def StaleAfterNs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def DataQualityStateStart(builder: flatbuffers.Builder):
    builder.StartObject(10)

def Start(builder: flatbuffers.Builder):
    DataQualityStateStart(builder)

def DataQualityStateAddSchemaVersion(builder: flatbuffers.Builder, schemaVersion: Any):
    builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(schemaVersion), 0)

def AddSchemaVersion(builder: flatbuffers.Builder, schemaVersion: Any):
    DataQualityStateAddSchemaVersion(builder, schemaVersion)

def DataQualityStateAddVenueId(builder: flatbuffers.Builder, venueId: Any):
    builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(venueId), 0)

def AddVenueId(builder: flatbuffers.Builder, venueId: Any):
    DataQualityStateAddVenueId(builder, venueId)

def DataQualityStateAddChannelId(builder: flatbuffers.Builder, channelId: Any):
    builder.PrependStructSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(channelId), 0)

def AddChannelId(builder: flatbuffers.Builder, channelId: Any):
    DataQualityStateAddChannelId(builder, channelId)

def DataQualityStateAddState(builder: flatbuffers.Builder, state: int):
    builder.PrependUint8Slot(3, state, 0)

def AddState(builder: flatbuffers.Builder, state: int):
    DataQualityStateAddState(builder, state)

def DataQualityStateAddObservedProcessMonotonicTime(builder: flatbuffers.Builder, observedProcessMonotonicTime: Any):
    builder.PrependStructSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(observedProcessMonotonicTime), 0)

def AddObservedProcessMonotonicTime(builder: flatbuffers.Builder, observedProcessMonotonicTime: Any):
    DataQualityStateAddObservedProcessMonotonicTime(builder, observedProcessMonotonicTime)

def DataQualityStateAddLastGoodExchangeEventTime(builder: flatbuffers.Builder, lastGoodExchangeEventTime: Any):
    builder.PrependStructSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(lastGoodExchangeEventTime), 0)

def AddLastGoodExchangeEventTime(builder: flatbuffers.Builder, lastGoodExchangeEventTime: Any):
    DataQualityStateAddLastGoodExchangeEventTime(builder, lastGoodExchangeEventTime)

def DataQualityStateAddLastGoodNicReceiveTime(builder: flatbuffers.Builder, lastGoodNicReceiveTime: Any):
    builder.PrependStructSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(lastGoodNicReceiveTime), 0)

def AddLastGoodNicReceiveTime(builder: flatbuffers.Builder, lastGoodNicReceiveTime: Any):
    DataQualityStateAddLastGoodNicReceiveTime(builder, lastGoodNicReceiveTime)

def DataQualityStateAddMissingSequenceCount(builder: flatbuffers.Builder, missingSequenceCount: int):
    builder.PrependUint64Slot(7, missingSequenceCount, 0)

def AddMissingSequenceCount(builder: flatbuffers.Builder, missingSequenceCount: int):
    DataQualityStateAddMissingSequenceCount(builder, missingSequenceCount)

def DataQualityStateAddMalformedRecordCount(builder: flatbuffers.Builder, malformedRecordCount: int):
    builder.PrependUint64Slot(8, malformedRecordCount, 0)

def AddMalformedRecordCount(builder: flatbuffers.Builder, malformedRecordCount: int):
    DataQualityStateAddMalformedRecordCount(builder, malformedRecordCount)

def DataQualityStateAddStaleAfterNs(builder: flatbuffers.Builder, staleAfterNs: int):
    builder.PrependUint64Slot(9, staleAfterNs, 0)

def AddStaleAfterNs(builder: flatbuffers.Builder, staleAfterNs: int):
    DataQualityStateAddStaleAfterNs(builder, staleAfterNs)

def DataQualityStateEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return DataQualityStateEnd(builder)
