from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from aegis.mx.contracts.v1.ChannelId import ChannelId
from aegis.mx.contracts.v1.DataQualityCode import DataQualityCode
from aegis.mx.contracts.v1.ExchangeEventTimeNs import ExchangeEventTimeNs
from aegis.mx.contracts.v1.NicReceiveTimeNs import NicReceiveTimeNs
from aegis.mx.contracts.v1.ProcessMonotonicTimeNs import ProcessMonotonicTimeNs
from aegis.mx.contracts.v1.SchemaVersion import SchemaVersion
from aegis.mx.contracts.v1.VenueId import VenueId

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class DataQualityState:
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> DataQualityState: ...
  @classmethod
  def GetRootAsDataQualityState(cls, buf: bytes, offset: int) -> DataQualityState: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def SchemaVersion(self) -> SchemaVersion | None: ...
  def VenueId(self) -> VenueId | None: ...
  def ChannelId(self) -> ChannelId | None: ...
  def State(self) -> typing.Literal[DataQualityCode.UNKNOWN, DataQualityCode.VALID, DataQualityCode.DEGRADED, DataQualityCode.STALE, DataQualityCode.INVALID]: ...
  def ObservedProcessMonotonicTime(self) -> ProcessMonotonicTimeNs | None: ...
  def LastGoodExchangeEventTime(self) -> ExchangeEventTimeNs | None: ...
  def LastGoodNicReceiveTime(self) -> NicReceiveTimeNs | None: ...
  def MissingSequenceCount(self) -> int: ...
  def MalformedRecordCount(self) -> int: ...
  def StaleAfterNs(self) -> int: ...
def DataQualityStateStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def DataQualityStateAddSchemaVersion(builder: flatbuffers.Builder, schemaVersion: uoffset) -> None: ...
def DataQualityStateAddVenueId(builder: flatbuffers.Builder, venueId: uoffset) -> None: ...
def DataQualityStateAddChannelId(builder: flatbuffers.Builder, channelId: uoffset) -> None: ...
def DataQualityStateAddState(builder: flatbuffers.Builder, state: typing.Literal[DataQualityCode.UNKNOWN, DataQualityCode.VALID, DataQualityCode.DEGRADED, DataQualityCode.STALE, DataQualityCode.INVALID]) -> None: ...
def DataQualityStateAddObservedProcessMonotonicTime(builder: flatbuffers.Builder, observedProcessMonotonicTime: uoffset) -> None: ...
def DataQualityStateAddLastGoodExchangeEventTime(builder: flatbuffers.Builder, lastGoodExchangeEventTime: uoffset) -> None: ...
def DataQualityStateAddLastGoodNicReceiveTime(builder: flatbuffers.Builder, lastGoodNicReceiveTime: uoffset) -> None: ...
def DataQualityStateAddMissingSequenceCount(builder: flatbuffers.Builder, missingSequenceCount: int) -> None: ...
def DataQualityStateAddMalformedRecordCount(builder: flatbuffers.Builder, malformedRecordCount: int) -> None: ...
def DataQualityStateAddStaleAfterNs(builder: flatbuffers.Builder, staleAfterNs: int) -> None: ...
def DataQualityStateEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

