# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

class EnsembleModelWeight(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls) -> int:
        return 80

    # EnsembleModelWeight
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # EnsembleModelWeight
    def ForecastId(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 0)
        return obj

    # EnsembleModelWeight
    def ModelId(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 16)
        return obj

    # EnsembleModelWeight
    def ModelVersion(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 32)
        return obj

    # EnsembleModelWeight
    def Role(self): return self._tab.Get(flatbuffers.number_types.Uint8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(48))
    # EnsembleModelWeight
    def Eligibility(self): return self._tab.Get(flatbuffers.number_types.Uint8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(49))
    # EnsembleModelWeight
    def WeightPpm(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(52))
    # EnsembleModelWeight
    def RawGateScore(self): return self._tab.Get(flatbuffers.number_types.Uint64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(56))
    # EnsembleModelWeight
    def FreshnessPpm(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(64))
    # EnsembleModelWeight
    def ForecastHash(self): return self._tab.Get(flatbuffers.number_types.Uint64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(72))

def CreateEnsembleModelWeight(builder, forecastId_high, forecastId_low, modelId_high, modelId_low, modelVersion_high, modelVersion_low, role, eligibility, weightPpm, rawGateScore, freshnessPpm, forecastHash):
    builder.Prep(8, 80)
    builder.PrependUint64(forecastHash)
    builder.Pad(4)
    builder.PrependUint32(freshnessPpm)
    builder.PrependUint64(rawGateScore)
    builder.PrependUint32(weightPpm)
    builder.Pad(2)
    builder.PrependUint8(eligibility)
    builder.PrependUint8(role)
    builder.Prep(8, 16)
    builder.PrependUint64(modelVersion_low)
    builder.PrependUint64(modelVersion_high)
    builder.Prep(8, 16)
    builder.PrependUint64(modelId_low)
    builder.PrependUint64(modelId_high)
    builder.Prep(8, 16)
    builder.PrependUint64(forecastId_low)
    builder.PrependUint64(forecastId_high)
    return builder.Offset()
