# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

class EnsembleDecisionReasonCode(object):
    UNKNOWN = 0
    COMBINED = 1
    INVALID_CONFIGURATION = 2
    INVALID_REQUEST = 3
    UNSAFE_MARKET_STATE = 4
    INVALID_INPUT_FEED = 5
    INVALID_TRANSACTION_COST = 6
    NO_ELIGIBLE_EXPERT = 7
    WEIGHT_CAP_INFEASIBLE = 8
    NO_POSITIVE_GATE_SCORE = 9
    INSUFFICIENT_ROBUST_EDGE = 10
    NUMERIC_ERROR = 11
