# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

class EnsembleMarketStateCode(object):
    UNKNOWN = 0
    STARTUP = 1
    NORMAL = 2
    SCHEDULED_EVENT = 3
    BREAKING_NEWS = 4
    EVENT_PRICE_DISCOVERY = 5
    VOLATILITY_SPIKE = 6
    DATA_DEGRADED = 7
    HALTED = 8
    REOPENING = 9
    RECOVERY = 10
    SHUTDOWN = 11
