# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

class EnsembleExpertRoleCode(object):
    UNKNOWN = 0
    GENERIC = 1
    MICROSTRUCTURE = 2
    TIMESERIES = 3
    EVENT = 4
    OPTIONS = 5
    MACRO = 6
    AUCTION = 7
