from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from aegis.mx.contracts.v1.EnsembleDominantExpertReasonCode import EnsembleDominantExpertReasonCode
from aegis.mx.contracts.v1.EnsembleEventStateCode import EnsembleEventStateCode
from aegis.mx.contracts.v1.EnsembleGateKind import EnsembleGateKind
from aegis.mx.contracts.v1.EnsembleMarketStateCode import EnsembleMarketStateCode
from aegis.mx.contracts.v1.ForecastId import ForecastId
from aegis.mx.contracts.v1.ModelId import ModelId
from aegis.mx.contracts.v1.ModelVersion import ModelVersion

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class EnsembleDecisionExplanation:
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> EnsembleDecisionExplanation: ...
  @classmethod
  def GetRootAsEnsembleDecisionExplanation(cls, buf: bytes, offset: int) -> EnsembleDecisionExplanation: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def GateKind(self) -> typing.Literal[EnsembleGateKind.UNKNOWN, EnsembleGateKind.RULE_BASED, EnsembleGateKind.LINEAR, EnsembleGateKind.QUANTIZED_LEARNED]: ...
  def MarketState(self) -> typing.Literal[EnsembleMarketStateCode.UNKNOWN, EnsembleMarketStateCode.STARTUP, EnsembleMarketStateCode.NORMAL, EnsembleMarketStateCode.SCHEDULED_EVENT, EnsembleMarketStateCode.BREAKING_NEWS, EnsembleMarketStateCode.EVENT_PRICE_DISCOVERY, EnsembleMarketStateCode.VOLATILITY_SPIKE, EnsembleMarketStateCode.DATA_DEGRADED, EnsembleMarketStateCode.HALTED, EnsembleMarketStateCode.REOPENING, EnsembleMarketStateCode.RECOVERY, EnsembleMarketStateCode.SHUTDOWN]: ...
  def EventState(self) -> typing.Literal[EnsembleEventStateCode.UNKNOWN, EnsembleEventStateCode.NONE, EnsembleEventStateCode.SCHEDULED, EnsembleEventStateCode.BREAKING_NEWS, EnsembleEventStateCode.PRICE_DISCOVERY, EnsembleEventStateCode.VOLATILITY_SHOCK]: ...
  def InputDataQualityPpm(self) -> int: ...
  def SuppliedExpertCount(self) -> int: ...
  def EligibleExpertCount(self) -> int: ...
  def DominantForecastId(self) -> ForecastId | None: ...
  def DominantModelId(self) -> ModelId | None: ...
  def DominantModelVersion(self) -> ModelVersion | None: ...
  def DominantReason(self) -> typing.Literal[EnsembleDominantExpertReasonCode.UNKNOWN, EnsembleDominantExpertReasonCode.HIGHEST_WEIGHT, EnsembleDominantExpertReasonCode.CANONICAL_TIE_BREAK, EnsembleDominantExpertReasonCode.ONLY_ELIGIBLE_EXPERT, EnsembleDominantExpertReasonCode.NO_ELIGIBLE_EXPERT]: ...
  def RequiredEdgePpm(self) -> int: ...
  def LearnedGateSignatureHash(self) -> int: ...
  def ExplanationHash(self) -> int: ...
  def ContributingExpertCount(self) -> int: ...
  def TransactionCostForecastHash(self) -> int: ...
  def MarketStateSnapshotHash(self) -> int: ...
  def ConfigurationHash(self) -> int: ...
def EnsembleDecisionExplanationStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def EnsembleDecisionExplanationAddGateKind(builder: flatbuffers.Builder, gateKind: typing.Literal[EnsembleGateKind.UNKNOWN, EnsembleGateKind.RULE_BASED, EnsembleGateKind.LINEAR, EnsembleGateKind.QUANTIZED_LEARNED]) -> None: ...
def EnsembleDecisionExplanationAddMarketState(builder: flatbuffers.Builder, marketState: typing.Literal[EnsembleMarketStateCode.UNKNOWN, EnsembleMarketStateCode.STARTUP, EnsembleMarketStateCode.NORMAL, EnsembleMarketStateCode.SCHEDULED_EVENT, EnsembleMarketStateCode.BREAKING_NEWS, EnsembleMarketStateCode.EVENT_PRICE_DISCOVERY, EnsembleMarketStateCode.VOLATILITY_SPIKE, EnsembleMarketStateCode.DATA_DEGRADED, EnsembleMarketStateCode.HALTED, EnsembleMarketStateCode.REOPENING, EnsembleMarketStateCode.RECOVERY, EnsembleMarketStateCode.SHUTDOWN]) -> None: ...
def EnsembleDecisionExplanationAddEventState(builder: flatbuffers.Builder, eventState: typing.Literal[EnsembleEventStateCode.UNKNOWN, EnsembleEventStateCode.NONE, EnsembleEventStateCode.SCHEDULED, EnsembleEventStateCode.BREAKING_NEWS, EnsembleEventStateCode.PRICE_DISCOVERY, EnsembleEventStateCode.VOLATILITY_SHOCK]) -> None: ...
def EnsembleDecisionExplanationAddInputDataQualityPpm(builder: flatbuffers.Builder, inputDataQualityPpm: int) -> None: ...
def EnsembleDecisionExplanationAddSuppliedExpertCount(builder: flatbuffers.Builder, suppliedExpertCount: int) -> None: ...
def EnsembleDecisionExplanationAddEligibleExpertCount(builder: flatbuffers.Builder, eligibleExpertCount: int) -> None: ...
def EnsembleDecisionExplanationAddDominantForecastId(builder: flatbuffers.Builder, dominantForecastId: uoffset) -> None: ...
def EnsembleDecisionExplanationAddDominantModelId(builder: flatbuffers.Builder, dominantModelId: uoffset) -> None: ...
def EnsembleDecisionExplanationAddDominantModelVersion(builder: flatbuffers.Builder, dominantModelVersion: uoffset) -> None: ...
def EnsembleDecisionExplanationAddDominantReason(builder: flatbuffers.Builder, dominantReason: typing.Literal[EnsembleDominantExpertReasonCode.UNKNOWN, EnsembleDominantExpertReasonCode.HIGHEST_WEIGHT, EnsembleDominantExpertReasonCode.CANONICAL_TIE_BREAK, EnsembleDominantExpertReasonCode.ONLY_ELIGIBLE_EXPERT, EnsembleDominantExpertReasonCode.NO_ELIGIBLE_EXPERT]) -> None: ...
def EnsembleDecisionExplanationAddRequiredEdgePpm(builder: flatbuffers.Builder, requiredEdgePpm: int) -> None: ...
def EnsembleDecisionExplanationAddLearnedGateSignatureHash(builder: flatbuffers.Builder, learnedGateSignatureHash: int) -> None: ...
def EnsembleDecisionExplanationAddExplanationHash(builder: flatbuffers.Builder, explanationHash: int) -> None: ...
def EnsembleDecisionExplanationAddContributingExpertCount(builder: flatbuffers.Builder, contributingExpertCount: int) -> None: ...
def EnsembleDecisionExplanationAddTransactionCostForecastHash(builder: flatbuffers.Builder, transactionCostForecastHash: int) -> None: ...
def EnsembleDecisionExplanationAddMarketStateSnapshotHash(builder: flatbuffers.Builder, marketStateSnapshotHash: int) -> None: ...
def EnsembleDecisionExplanationAddConfigurationHash(builder: flatbuffers.Builder, configurationHash: int) -> None: ...
def EnsembleDecisionExplanationEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

