# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

class EnsembleDominantExpertReasonCode(object):
    UNKNOWN = 0
    HIGHEST_WEIGHT = 1
    CANONICAL_TIE_BREAK = 2
    ONLY_ELIGIBLE_EXPERT = 3
    NO_ELIGIBLE_EXPERT = 4
