from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from aegis.mx.contracts.v1.EnsembleEligibilityCode import EnsembleEligibilityCode
from aegis.mx.contracts.v1.EnsembleExpertRoleCode import EnsembleExpertRoleCode
from aegis.mx.contracts.v1.ForecastId import ForecastId
from aegis.mx.contracts.v1.ModelId import ModelId
from aegis.mx.contracts.v1.ModelVersion import ModelVersion

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class EnsembleModelWeight:
  @classmethod
  def SizeOf(cls) -> int: ...

  def Init(self, buf: bytes, pos: int) -> None: ...
  def ForecastId(self, obj: ForecastId) -> ForecastId: ...
  def ModelId(self, obj: ModelId) -> ModelId: ...
  def ModelVersion(self, obj: ModelVersion) -> ModelVersion: ...
  def Role(self) -> typing.Literal[EnsembleExpertRoleCode.UNKNOWN, EnsembleExpertRoleCode.GENERIC, EnsembleExpertRoleCode.MICROSTRUCTURE, EnsembleExpertRoleCode.TIMESERIES, EnsembleExpertRoleCode.EVENT, EnsembleExpertRoleCode.OPTIONS, EnsembleExpertRoleCode.MACRO, EnsembleExpertRoleCode.AUCTION]: ...
  def Eligibility(self) -> typing.Literal[EnsembleEligibilityCode.UNKNOWN, EnsembleEligibilityCode.ELIGIBLE, EnsembleEligibilityCode.MISSING_PROVENANCE, EnsembleEligibilityCode.EXPIRED, EnsembleEligibilityCode.MODEL_DISABLED, EnsembleEligibilityCode.INVALID_INPUT_FEED, EnsembleEligibilityCode.INCOMPATIBLE_STATE, EnsembleEligibilityCode.EXCESSIVE_OOD, EnsembleEligibilityCode.CALIBRATION_FAILED, EnsembleEligibilityCode.DATA_QUALITY_FAILED, EnsembleEligibilityCode.INVALID_FORECAST, EnsembleEligibilityCode.SCOPE_MISMATCH, EnsembleEligibilityCode.CONTROL_GENERATION_MISMATCH, EnsembleEligibilityCode.DUPLICATE_EXPERT]: ...
  def WeightPpm(self) -> int: ...
  def RawGateScore(self) -> int: ...
  def FreshnessPpm(self) -> int: ...
  def ForecastHash(self) -> int: ...

def CreateEnsembleModelWeight(builder: flatbuffers.Builder, forecastId_high: int, forecastId_low: int, modelId_high: int, modelId_low: int, modelVersion_high: int, modelVersion_low: int, role: typing.Literal[EnsembleExpertRoleCode.UNKNOWN, EnsembleExpertRoleCode.GENERIC, EnsembleExpertRoleCode.MICROSTRUCTURE, EnsembleExpertRoleCode.TIMESERIES, EnsembleExpertRoleCode.EVENT, EnsembleExpertRoleCode.OPTIONS, EnsembleExpertRoleCode.MACRO, EnsembleExpertRoleCode.AUCTION], eligibility: typing.Literal[EnsembleEligibilityCode.UNKNOWN, EnsembleEligibilityCode.ELIGIBLE, EnsembleEligibilityCode.MISSING_PROVENANCE, EnsembleEligibilityCode.EXPIRED, EnsembleEligibilityCode.MODEL_DISABLED, EnsembleEligibilityCode.INVALID_INPUT_FEED, EnsembleEligibilityCode.INCOMPATIBLE_STATE, EnsembleEligibilityCode.EXCESSIVE_OOD, EnsembleEligibilityCode.CALIBRATION_FAILED, EnsembleEligibilityCode.DATA_QUALITY_FAILED, EnsembleEligibilityCode.INVALID_FORECAST, EnsembleEligibilityCode.SCOPE_MISMATCH, EnsembleEligibilityCode.CONTROL_GENERATION_MISMATCH, EnsembleEligibilityCode.DUPLICATE_EXPERT], weightPpm: int, rawGateScore: int, freshnessPpm: int, forecastHash: int) -> uoffset: ...

