from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from aegis.mx.contracts.v1.ConfigurationVersion import ConfigurationVersion
from aegis.mx.contracts.v1.EnsembleDecisionExplanation import EnsembleDecisionExplanation
from aegis.mx.contracts.v1.EnsembleDecisionReasonCode import EnsembleDecisionReasonCode
from aegis.mx.contracts.v1.EnsembleModelWeight import EnsembleModelWeight
from aegis.mx.contracts.v1.ForecastId import ForecastId
from aegis.mx.contracts.v1.ForecastUnit import ForecastUnit
from aegis.mx.contracts.v1.InstrumentId import InstrumentId
from aegis.mx.contracts.v1.ModelId import ModelId
from aegis.mx.contracts.v1.ModelVersion import ModelVersion
from aegis.mx.contracts.v1.ProcessMonotonicTimeNs import ProcessMonotonicTimeNs
from aegis.mx.contracts.v1.SchemaVersion import SchemaVersion
from aegis.mx.contracts.v1.SessionId import SessionId

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class EnsembleForecast:
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> EnsembleForecast: ...
  @classmethod
  def GetRootAsEnsembleForecast(cls, buf: bytes, offset: int) -> EnsembleForecast: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def SchemaVersion(self) -> SchemaVersion | None: ...
  def ForecastId(self) -> ForecastId | None: ...
  def SessionId(self) -> SessionId | None: ...
  def InstrumentId(self) -> InstrumentId | None: ...
  def EnsembleModelId(self) -> ModelId | None: ...
  def EnsembleModelVersion(self) -> ModelVersion | None: ...
  def ConfigurationVersion(self) -> ConfigurationVersion | None: ...
  def ForecastUnit(self) -> typing.Literal[ForecastUnit.UNKNOWN, ForecastUnit.RETURN_TICKS, ForecastUnit.FAIR_VALUE_TICKS, ForecastUnit.PROBABILITY_PPM, ForecastUnit.QUANTITY_UNITS, ForecastUnit.RETURN_PPM, ForecastUnit.VOLATILITY_PPM, ForecastUnit.VOLUME_UNITS, ForecastUnit.SPREAD_TICKS, ForecastUnit.FACTOR_PPM]: ...
  def ForecastValue(self) -> int: ...
  def ConfidencePpm(self) -> int: ...
  def HorizonNs(self) -> int: ...
  def CreatedProcessMonotonicTime(self) -> ProcessMonotonicTimeNs | None: ...
  def ValidUntilProcessMonotonicTime(self) -> ProcessMonotonicTimeNs | None: ...
  def ContributingForecastIds(self, i: int) -> ForecastId | None: ...
  def ContributingForecastIdsLength(self) -> int: ...
  def ContributingForecastIdsIsNone(self) -> bool: ...
  def ExpectedReturnPpm(self) -> int: ...
  def ProbabilityDownPpm(self) -> int: ...
  def ProbabilityFlatPpm(self) -> int: ...
  def ProbabilityUpPpm(self) -> int: ...
  def VariancePpmSquared(self) -> int: ...
  def ReturnP10Ppm(self) -> int: ...
  def ReturnP50Ppm(self) -> int: ...
  def ReturnP90Ppm(self) -> int: ...
  def EffectiveUncertaintyPpm(self) -> int: ...
  def DisagreementPpm(self) -> int: ...
  def ModelWeights(self, i: int) -> EnsembleModelWeight | None: ...
  def ModelWeightsLength(self) -> int: ...
  def ModelWeightsIsNone(self) -> bool: ...
  def EstimatedTransactionCostPpm(self) -> int: ...
  def UncertaintyPenaltyPpm(self) -> int: ...
  def SafetyMarginPpm(self) -> int: ...
  def NetRobustEdgePpm(self) -> int: ...
  def Abstain(self) -> bool: ...
  def PrimaryReason(self) -> typing.Literal[EnsembleDecisionReasonCode.UNKNOWN, EnsembleDecisionReasonCode.COMBINED, EnsembleDecisionReasonCode.INVALID_CONFIGURATION, EnsembleDecisionReasonCode.INVALID_REQUEST, EnsembleDecisionReasonCode.UNSAFE_MARKET_STATE, EnsembleDecisionReasonCode.INVALID_INPUT_FEED, EnsembleDecisionReasonCode.INVALID_TRANSACTION_COST, EnsembleDecisionReasonCode.NO_ELIGIBLE_EXPERT, EnsembleDecisionReasonCode.WEIGHT_CAP_INFEASIBLE, EnsembleDecisionReasonCode.NO_POSITIVE_GATE_SCORE, EnsembleDecisionReasonCode.INSUFFICIENT_ROBUST_EDGE, EnsembleDecisionReasonCode.NUMERIC_ERROR]: ...
  def ReasonMask(self) -> int: ...
  def DecisionExplanation(self) -> EnsembleDecisionExplanation | None: ...
  def EnsembleHash(self) -> int: ...
def EnsembleForecastStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def EnsembleForecastAddSchemaVersion(builder: flatbuffers.Builder, schemaVersion: uoffset) -> None: ...
def EnsembleForecastAddForecastId(builder: flatbuffers.Builder, forecastId: uoffset) -> None: ...
def EnsembleForecastAddSessionId(builder: flatbuffers.Builder, sessionId: uoffset) -> None: ...
def EnsembleForecastAddInstrumentId(builder: flatbuffers.Builder, instrumentId: uoffset) -> None: ...
def EnsembleForecastAddEnsembleModelId(builder: flatbuffers.Builder, ensembleModelId: uoffset) -> None: ...
def EnsembleForecastAddEnsembleModelVersion(builder: flatbuffers.Builder, ensembleModelVersion: uoffset) -> None: ...
def EnsembleForecastAddConfigurationVersion(builder: flatbuffers.Builder, configurationVersion: uoffset) -> None: ...
def EnsembleForecastAddForecastUnit(builder: flatbuffers.Builder, forecastUnit: typing.Literal[ForecastUnit.UNKNOWN, ForecastUnit.RETURN_TICKS, ForecastUnit.FAIR_VALUE_TICKS, ForecastUnit.PROBABILITY_PPM, ForecastUnit.QUANTITY_UNITS, ForecastUnit.RETURN_PPM, ForecastUnit.VOLATILITY_PPM, ForecastUnit.VOLUME_UNITS, ForecastUnit.SPREAD_TICKS, ForecastUnit.FACTOR_PPM]) -> None: ...
def EnsembleForecastAddForecastValue(builder: flatbuffers.Builder, forecastValue: int) -> None: ...
def EnsembleForecastAddConfidencePpm(builder: flatbuffers.Builder, confidencePpm: int) -> None: ...
def EnsembleForecastAddHorizonNs(builder: flatbuffers.Builder, horizonNs: int) -> None: ...
def EnsembleForecastAddCreatedProcessMonotonicTime(builder: flatbuffers.Builder, createdProcessMonotonicTime: uoffset) -> None: ...
def EnsembleForecastAddValidUntilProcessMonotonicTime(builder: flatbuffers.Builder, validUntilProcessMonotonicTime: uoffset) -> None: ...
def EnsembleForecastAddContributingForecastIds(builder: flatbuffers.Builder, contributingForecastIds: uoffset) -> None: ...
def EnsembleForecastStartContributingForecastIdsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartContributingForecastIdsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def EnsembleForecastAddExpectedReturnPpm(builder: flatbuffers.Builder, expectedReturnPpm: int) -> None: ...
def EnsembleForecastAddProbabilityDownPpm(builder: flatbuffers.Builder, probabilityDownPpm: int) -> None: ...
def EnsembleForecastAddProbabilityFlatPpm(builder: flatbuffers.Builder, probabilityFlatPpm: int) -> None: ...
def EnsembleForecastAddProbabilityUpPpm(builder: flatbuffers.Builder, probabilityUpPpm: int) -> None: ...
def EnsembleForecastAddVariancePpmSquared(builder: flatbuffers.Builder, variancePpmSquared: int) -> None: ...
def EnsembleForecastAddReturnP10Ppm(builder: flatbuffers.Builder, returnP10Ppm: int) -> None: ...
def EnsembleForecastAddReturnP50Ppm(builder: flatbuffers.Builder, returnP50Ppm: int) -> None: ...
def EnsembleForecastAddReturnP90Ppm(builder: flatbuffers.Builder, returnP90Ppm: int) -> None: ...
def EnsembleForecastAddEffectiveUncertaintyPpm(builder: flatbuffers.Builder, effectiveUncertaintyPpm: int) -> None: ...
def EnsembleForecastAddDisagreementPpm(builder: flatbuffers.Builder, disagreementPpm: int) -> None: ...
def EnsembleForecastAddModelWeights(builder: flatbuffers.Builder, modelWeights: uoffset) -> None: ...
def EnsembleForecastStartModelWeightsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartModelWeightsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def EnsembleForecastAddEstimatedTransactionCostPpm(builder: flatbuffers.Builder, estimatedTransactionCostPpm: int) -> None: ...
def EnsembleForecastAddUncertaintyPenaltyPpm(builder: flatbuffers.Builder, uncertaintyPenaltyPpm: int) -> None: ...
def EnsembleForecastAddSafetyMarginPpm(builder: flatbuffers.Builder, safetyMarginPpm: int) -> None: ...
def EnsembleForecastAddNetRobustEdgePpm(builder: flatbuffers.Builder, netRobustEdgePpm: int) -> None: ...
def EnsembleForecastAddAbstain(builder: flatbuffers.Builder, abstain: bool) -> None: ...
def EnsembleForecastAddPrimaryReason(builder: flatbuffers.Builder, primaryReason: typing.Literal[EnsembleDecisionReasonCode.UNKNOWN, EnsembleDecisionReasonCode.COMBINED, EnsembleDecisionReasonCode.INVALID_CONFIGURATION, EnsembleDecisionReasonCode.INVALID_REQUEST, EnsembleDecisionReasonCode.UNSAFE_MARKET_STATE, EnsembleDecisionReasonCode.INVALID_INPUT_FEED, EnsembleDecisionReasonCode.INVALID_TRANSACTION_COST, EnsembleDecisionReasonCode.NO_ELIGIBLE_EXPERT, EnsembleDecisionReasonCode.WEIGHT_CAP_INFEASIBLE, EnsembleDecisionReasonCode.NO_POSITIVE_GATE_SCORE, EnsembleDecisionReasonCode.INSUFFICIENT_ROBUST_EDGE, EnsembleDecisionReasonCode.NUMERIC_ERROR]) -> None: ...
def EnsembleForecastAddReasonMask(builder: flatbuffers.Builder, reasonMask: int) -> None: ...
def EnsembleForecastAddDecisionExplanation(builder: flatbuffers.Builder, decisionExplanation: uoffset) -> None: ...
def EnsembleForecastAddEnsembleHash(builder: flatbuffers.Builder, ensembleHash: int) -> None: ...
def EnsembleForecastEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

