# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

class EnsembleEligibilityCode(object):
    UNKNOWN = 0
    ELIGIBLE = 1
    MISSING_PROVENANCE = 2
    EXPIRED = 3
    MODEL_DISABLED = 4
    INVALID_INPUT_FEED = 5
    INCOMPATIBLE_STATE = 6
    EXCESSIVE_OOD = 7
    CALIBRATION_FAILED = 8
    DATA_QUALITY_FAILED = 9
    INVALID_FORECAST = 10
    SCOPE_MISMATCH = 11
    CONTROL_GENERATION_MISMATCH = 12
    DUPLICATE_EXPERT = 13
