# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from aegis.mx.contracts.v1.ConfigurationVersion import ConfigurationVersion
from aegis.mx.contracts.v1.EnsembleDecisionExplanation import EnsembleDecisionExplanation
from aegis.mx.contracts.v1.EnsembleModelWeight import EnsembleModelWeight
from aegis.mx.contracts.v1.ForecastId import ForecastId
from aegis.mx.contracts.v1.InstrumentId import InstrumentId
from aegis.mx.contracts.v1.ModelId import ModelId
from aegis.mx.contracts.v1.ModelVersion import ModelVersion
from aegis.mx.contracts.v1.ProcessMonotonicTimeNs import ProcessMonotonicTimeNs
from aegis.mx.contracts.v1.SchemaVersion import SchemaVersion
from aegis.mx.contracts.v1.SessionId import SessionId
from typing import Optional
np = import_numpy()

class EnsembleForecast(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = EnsembleForecast()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsEnsembleForecast(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # EnsembleForecast
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # EnsembleForecast
    def SchemaVersion(self) -> Optional[SchemaVersion]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            obj = SchemaVersion()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # EnsembleForecast
    def ForecastId(self) -> Optional[ForecastId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            obj = ForecastId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # EnsembleForecast
    def SessionId(self) -> Optional[SessionId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = o + self._tab.Pos
            obj = SessionId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # EnsembleForecast
    def InstrumentId(self) -> Optional[InstrumentId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = o + self._tab.Pos
            obj = InstrumentId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # EnsembleForecast
    def EnsembleModelId(self) -> Optional[ModelId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = o + self._tab.Pos
            obj = ModelId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # EnsembleForecast
    def EnsembleModelVersion(self) -> Optional[ModelVersion]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = o + self._tab.Pos
            obj = ModelVersion()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # EnsembleForecast
    def ConfigurationVersion(self) -> Optional[ConfigurationVersion]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            x = o + self._tab.Pos
            obj = ConfigurationVersion()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # EnsembleForecast
    def ForecastUnit(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # EnsembleForecast
    def ForecastValue(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # EnsembleForecast
    def ConfidencePpm(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # EnsembleForecast
    def HorizonNs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # EnsembleForecast
    def CreatedProcessMonotonicTime(self) -> Optional[ProcessMonotonicTimeNs]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            x = o + self._tab.Pos
            obj = ProcessMonotonicTimeNs()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # EnsembleForecast
    def ValidUntilProcessMonotonicTime(self) -> Optional[ProcessMonotonicTimeNs]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            x = o + self._tab.Pos
            obj = ProcessMonotonicTimeNs()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # EnsembleForecast
    def ContributingForecastIds(self, j: int) -> Optional[ForecastId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 16
            obj = ForecastId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # EnsembleForecast
    def ContributingForecastIdsLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # EnsembleForecast
    def ContributingForecastIdsIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        return o == 0

    # EnsembleForecast
    def ExpectedReturnPpm(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # EnsembleForecast
    def ProbabilityDownPpm(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # EnsembleForecast
    def ProbabilityFlatPpm(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # EnsembleForecast
    def ProbabilityUpPpm(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(38))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # EnsembleForecast
    def VariancePpmSquared(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(40))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # EnsembleForecast
    def ReturnP10Ppm(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(42))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # EnsembleForecast
    def ReturnP50Ppm(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(44))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # EnsembleForecast
    def ReturnP90Ppm(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(46))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # EnsembleForecast
    def EffectiveUncertaintyPpm(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(48))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # EnsembleForecast
    def DisagreementPpm(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(50))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # EnsembleForecast
    def ModelWeights(self, j: int) -> Optional[EnsembleModelWeight]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(52))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 80
            obj = EnsembleModelWeight()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # EnsembleForecast
    def ModelWeightsLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(52))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # EnsembleForecast
    def ModelWeightsIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(52))
        return o == 0

    # EnsembleForecast
    def EstimatedTransactionCostPpm(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(54))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # EnsembleForecast
    def UncertaintyPenaltyPpm(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(56))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # EnsembleForecast
    def SafetyMarginPpm(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(58))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # EnsembleForecast
    def NetRobustEdgePpm(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(60))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # EnsembleForecast
    def Abstain(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(62))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return True

    # EnsembleForecast
    def PrimaryReason(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(64))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # EnsembleForecast
    def ReasonMask(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(66))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # EnsembleForecast
    def DecisionExplanation(self) -> Optional[EnsembleDecisionExplanation]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(68))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = EnsembleDecisionExplanation()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # EnsembleForecast
    def EnsembleHash(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(70))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def EnsembleForecastStart(builder: flatbuffers.Builder):
    builder.StartObject(34)

def Start(builder: flatbuffers.Builder):
    EnsembleForecastStart(builder)

def EnsembleForecastAddSchemaVersion(builder: flatbuffers.Builder, schemaVersion: Any):
    builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(schemaVersion), 0)

def AddSchemaVersion(builder: flatbuffers.Builder, schemaVersion: Any):
    EnsembleForecastAddSchemaVersion(builder, schemaVersion)

def EnsembleForecastAddForecastId(builder: flatbuffers.Builder, forecastId: Any):
    builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(forecastId), 0)

def AddForecastId(builder: flatbuffers.Builder, forecastId: Any):
    EnsembleForecastAddForecastId(builder, forecastId)

def EnsembleForecastAddSessionId(builder: flatbuffers.Builder, sessionId: Any):
    builder.PrependStructSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(sessionId), 0)

def AddSessionId(builder: flatbuffers.Builder, sessionId: Any):
    EnsembleForecastAddSessionId(builder, sessionId)

def EnsembleForecastAddInstrumentId(builder: flatbuffers.Builder, instrumentId: Any):
    builder.PrependStructSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(instrumentId), 0)

def AddInstrumentId(builder: flatbuffers.Builder, instrumentId: Any):
    EnsembleForecastAddInstrumentId(builder, instrumentId)

def EnsembleForecastAddEnsembleModelId(builder: flatbuffers.Builder, ensembleModelId: Any):
    builder.PrependStructSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(ensembleModelId), 0)

def AddEnsembleModelId(builder: flatbuffers.Builder, ensembleModelId: Any):
    EnsembleForecastAddEnsembleModelId(builder, ensembleModelId)

def EnsembleForecastAddEnsembleModelVersion(builder: flatbuffers.Builder, ensembleModelVersion: Any):
    builder.PrependStructSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(ensembleModelVersion), 0)

def AddEnsembleModelVersion(builder: flatbuffers.Builder, ensembleModelVersion: Any):
    EnsembleForecastAddEnsembleModelVersion(builder, ensembleModelVersion)

def EnsembleForecastAddConfigurationVersion(builder: flatbuffers.Builder, configurationVersion: Any):
    builder.PrependStructSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(configurationVersion), 0)

def AddConfigurationVersion(builder: flatbuffers.Builder, configurationVersion: Any):
    EnsembleForecastAddConfigurationVersion(builder, configurationVersion)

def EnsembleForecastAddForecastUnit(builder: flatbuffers.Builder, forecastUnit: int):
    builder.PrependUint8Slot(7, forecastUnit, 0)

def AddForecastUnit(builder: flatbuffers.Builder, forecastUnit: int):
    EnsembleForecastAddForecastUnit(builder, forecastUnit)

def EnsembleForecastAddForecastValue(builder: flatbuffers.Builder, forecastValue: int):
    builder.PrependInt64Slot(8, forecastValue, 0)

def AddForecastValue(builder: flatbuffers.Builder, forecastValue: int):
    EnsembleForecastAddForecastValue(builder, forecastValue)

def EnsembleForecastAddConfidencePpm(builder: flatbuffers.Builder, confidencePpm: int):
    builder.PrependUint32Slot(9, confidencePpm, 0)

def AddConfidencePpm(builder: flatbuffers.Builder, confidencePpm: int):
    EnsembleForecastAddConfidencePpm(builder, confidencePpm)

def EnsembleForecastAddHorizonNs(builder: flatbuffers.Builder, horizonNs: int):
    builder.PrependUint64Slot(10, horizonNs, 0)

def AddHorizonNs(builder: flatbuffers.Builder, horizonNs: int):
    EnsembleForecastAddHorizonNs(builder, horizonNs)

def EnsembleForecastAddCreatedProcessMonotonicTime(builder: flatbuffers.Builder, createdProcessMonotonicTime: Any):
    builder.PrependStructSlot(11, flatbuffers.number_types.UOffsetTFlags.py_type(createdProcessMonotonicTime), 0)

def AddCreatedProcessMonotonicTime(builder: flatbuffers.Builder, createdProcessMonotonicTime: Any):
    EnsembleForecastAddCreatedProcessMonotonicTime(builder, createdProcessMonotonicTime)

def EnsembleForecastAddValidUntilProcessMonotonicTime(builder: flatbuffers.Builder, validUntilProcessMonotonicTime: Any):
    builder.PrependStructSlot(12, flatbuffers.number_types.UOffsetTFlags.py_type(validUntilProcessMonotonicTime), 0)

def AddValidUntilProcessMonotonicTime(builder: flatbuffers.Builder, validUntilProcessMonotonicTime: Any):
    EnsembleForecastAddValidUntilProcessMonotonicTime(builder, validUntilProcessMonotonicTime)

def EnsembleForecastAddContributingForecastIds(builder: flatbuffers.Builder, contributingForecastIds: int):
    builder.PrependUOffsetTRelativeSlot(13, flatbuffers.number_types.UOffsetTFlags.py_type(contributingForecastIds), 0)

def AddContributingForecastIds(builder: flatbuffers.Builder, contributingForecastIds: int):
    EnsembleForecastAddContributingForecastIds(builder, contributingForecastIds)

def EnsembleForecastStartContributingForecastIdsVector(builder, numElems: int) -> int:
    return builder.StartVector(16, numElems, 8)

def StartContributingForecastIdsVector(builder, numElems: int) -> int:
    return EnsembleForecastStartContributingForecastIdsVector(builder, numElems)

def EnsembleForecastAddExpectedReturnPpm(builder: flatbuffers.Builder, expectedReturnPpm: int):
    builder.PrependInt64Slot(14, expectedReturnPpm, 0)

def AddExpectedReturnPpm(builder: flatbuffers.Builder, expectedReturnPpm: int):
    EnsembleForecastAddExpectedReturnPpm(builder, expectedReturnPpm)

def EnsembleForecastAddProbabilityDownPpm(builder: flatbuffers.Builder, probabilityDownPpm: int):
    builder.PrependUint32Slot(15, probabilityDownPpm, 0)

def AddProbabilityDownPpm(builder: flatbuffers.Builder, probabilityDownPpm: int):
    EnsembleForecastAddProbabilityDownPpm(builder, probabilityDownPpm)

def EnsembleForecastAddProbabilityFlatPpm(builder: flatbuffers.Builder, probabilityFlatPpm: int):
    builder.PrependUint32Slot(16, probabilityFlatPpm, 0)

def AddProbabilityFlatPpm(builder: flatbuffers.Builder, probabilityFlatPpm: int):
    EnsembleForecastAddProbabilityFlatPpm(builder, probabilityFlatPpm)

def EnsembleForecastAddProbabilityUpPpm(builder: flatbuffers.Builder, probabilityUpPpm: int):
    builder.PrependUint32Slot(17, probabilityUpPpm, 0)

def AddProbabilityUpPpm(builder: flatbuffers.Builder, probabilityUpPpm: int):
    EnsembleForecastAddProbabilityUpPpm(builder, probabilityUpPpm)

def EnsembleForecastAddVariancePpmSquared(builder: flatbuffers.Builder, variancePpmSquared: int):
    builder.PrependUint64Slot(18, variancePpmSquared, 0)

def AddVariancePpmSquared(builder: flatbuffers.Builder, variancePpmSquared: int):
    EnsembleForecastAddVariancePpmSquared(builder, variancePpmSquared)

def EnsembleForecastAddReturnP10Ppm(builder: flatbuffers.Builder, returnP10Ppm: int):
    builder.PrependInt64Slot(19, returnP10Ppm, 0)

def AddReturnP10Ppm(builder: flatbuffers.Builder, returnP10Ppm: int):
    EnsembleForecastAddReturnP10Ppm(builder, returnP10Ppm)

def EnsembleForecastAddReturnP50Ppm(builder: flatbuffers.Builder, returnP50Ppm: int):
    builder.PrependInt64Slot(20, returnP50Ppm, 0)

def AddReturnP50Ppm(builder: flatbuffers.Builder, returnP50Ppm: int):
    EnsembleForecastAddReturnP50Ppm(builder, returnP50Ppm)

def EnsembleForecastAddReturnP90Ppm(builder: flatbuffers.Builder, returnP90Ppm: int):
    builder.PrependInt64Slot(21, returnP90Ppm, 0)

def AddReturnP90Ppm(builder: flatbuffers.Builder, returnP90Ppm: int):
    EnsembleForecastAddReturnP90Ppm(builder, returnP90Ppm)

def EnsembleForecastAddEffectiveUncertaintyPpm(builder: flatbuffers.Builder, effectiveUncertaintyPpm: int):
    builder.PrependUint64Slot(22, effectiveUncertaintyPpm, 0)

def AddEffectiveUncertaintyPpm(builder: flatbuffers.Builder, effectiveUncertaintyPpm: int):
    EnsembleForecastAddEffectiveUncertaintyPpm(builder, effectiveUncertaintyPpm)

def EnsembleForecastAddDisagreementPpm(builder: flatbuffers.Builder, disagreementPpm: int):
    builder.PrependUint64Slot(23, disagreementPpm, 0)

def AddDisagreementPpm(builder: flatbuffers.Builder, disagreementPpm: int):
    EnsembleForecastAddDisagreementPpm(builder, disagreementPpm)

def EnsembleForecastAddModelWeights(builder: flatbuffers.Builder, modelWeights: int):
    builder.PrependUOffsetTRelativeSlot(24, flatbuffers.number_types.UOffsetTFlags.py_type(modelWeights), 0)

def AddModelWeights(builder: flatbuffers.Builder, modelWeights: int):
    EnsembleForecastAddModelWeights(builder, modelWeights)

def EnsembleForecastStartModelWeightsVector(builder, numElems: int) -> int:
    return builder.StartVector(80, numElems, 8)

def StartModelWeightsVector(builder, numElems: int) -> int:
    return EnsembleForecastStartModelWeightsVector(builder, numElems)

def EnsembleForecastAddEstimatedTransactionCostPpm(builder: flatbuffers.Builder, estimatedTransactionCostPpm: int):
    builder.PrependUint64Slot(25, estimatedTransactionCostPpm, 0)

def AddEstimatedTransactionCostPpm(builder: flatbuffers.Builder, estimatedTransactionCostPpm: int):
    EnsembleForecastAddEstimatedTransactionCostPpm(builder, estimatedTransactionCostPpm)

def EnsembleForecastAddUncertaintyPenaltyPpm(builder: flatbuffers.Builder, uncertaintyPenaltyPpm: int):
    builder.PrependUint64Slot(26, uncertaintyPenaltyPpm, 0)

def AddUncertaintyPenaltyPpm(builder: flatbuffers.Builder, uncertaintyPenaltyPpm: int):
    EnsembleForecastAddUncertaintyPenaltyPpm(builder, uncertaintyPenaltyPpm)

def EnsembleForecastAddSafetyMarginPpm(builder: flatbuffers.Builder, safetyMarginPpm: int):
    builder.PrependUint64Slot(27, safetyMarginPpm, 0)

def AddSafetyMarginPpm(builder: flatbuffers.Builder, safetyMarginPpm: int):
    EnsembleForecastAddSafetyMarginPpm(builder, safetyMarginPpm)

def EnsembleForecastAddNetRobustEdgePpm(builder: flatbuffers.Builder, netRobustEdgePpm: int):
    builder.PrependInt64Slot(28, netRobustEdgePpm, 0)

def AddNetRobustEdgePpm(builder: flatbuffers.Builder, netRobustEdgePpm: int):
    EnsembleForecastAddNetRobustEdgePpm(builder, netRobustEdgePpm)

def EnsembleForecastAddAbstain(builder: flatbuffers.Builder, abstain: bool):
    builder.PrependBoolSlot(29, abstain, 1)

def AddAbstain(builder: flatbuffers.Builder, abstain: bool):
    EnsembleForecastAddAbstain(builder, abstain)

def EnsembleForecastAddPrimaryReason(builder: flatbuffers.Builder, primaryReason: int):
    builder.PrependUint8Slot(30, primaryReason, 0)

def AddPrimaryReason(builder: flatbuffers.Builder, primaryReason: int):
    EnsembleForecastAddPrimaryReason(builder, primaryReason)

def EnsembleForecastAddReasonMask(builder: flatbuffers.Builder, reasonMask: int):
    builder.PrependUint64Slot(31, reasonMask, 0)

def AddReasonMask(builder: flatbuffers.Builder, reasonMask: int):
    EnsembleForecastAddReasonMask(builder, reasonMask)

def EnsembleForecastAddDecisionExplanation(builder: flatbuffers.Builder, decisionExplanation: int):
    builder.PrependUOffsetTRelativeSlot(32, flatbuffers.number_types.UOffsetTFlags.py_type(decisionExplanation), 0)

def AddDecisionExplanation(builder: flatbuffers.Builder, decisionExplanation: int):
    EnsembleForecastAddDecisionExplanation(builder, decisionExplanation)

def EnsembleForecastAddEnsembleHash(builder: flatbuffers.Builder, ensembleHash: int):
    builder.PrependUint64Slot(33, ensembleHash, 0)

def AddEnsembleHash(builder: flatbuffers.Builder, ensembleHash: int):
    EnsembleForecastAddEnsembleHash(builder, ensembleHash)

def EnsembleForecastEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return EnsembleForecastEnd(builder)
