# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from aegis.mx.contracts.v1.ForecastId import ForecastId
from aegis.mx.contracts.v1.ModelId import ModelId
from aegis.mx.contracts.v1.ModelVersion import ModelVersion
from typing import Optional
np = import_numpy()

class EnsembleDecisionExplanation(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = EnsembleDecisionExplanation()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsEnsembleDecisionExplanation(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # EnsembleDecisionExplanation
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # EnsembleDecisionExplanation
    def GateKind(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # EnsembleDecisionExplanation
    def MarketState(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # EnsembleDecisionExplanation
    def EventState(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # EnsembleDecisionExplanation
    def InputDataQualityPpm(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # EnsembleDecisionExplanation
    def SuppliedExpertCount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # EnsembleDecisionExplanation
    def EligibleExpertCount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # EnsembleDecisionExplanation
    def DominantForecastId(self) -> Optional[ForecastId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            x = o + self._tab.Pos
            obj = ForecastId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # EnsembleDecisionExplanation
    def DominantModelId(self) -> Optional[ModelId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            x = o + self._tab.Pos
            obj = ModelId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # EnsembleDecisionExplanation
    def DominantModelVersion(self) -> Optional[ModelVersion]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            x = o + self._tab.Pos
            obj = ModelVersion()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # EnsembleDecisionExplanation
    def DominantReason(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # EnsembleDecisionExplanation
    def RequiredEdgePpm(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # EnsembleDecisionExplanation
    def LearnedGateSignatureHash(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # EnsembleDecisionExplanation
    def ExplanationHash(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # EnsembleDecisionExplanation
    def ContributingExpertCount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # EnsembleDecisionExplanation
    def TransactionCostForecastHash(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # EnsembleDecisionExplanation
    def MarketStateSnapshotHash(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # EnsembleDecisionExplanation
    def ConfigurationHash(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def EnsembleDecisionExplanationStart(builder: flatbuffers.Builder):
    builder.StartObject(17)

def Start(builder: flatbuffers.Builder):
    EnsembleDecisionExplanationStart(builder)

def EnsembleDecisionExplanationAddGateKind(builder: flatbuffers.Builder, gateKind: int):
    builder.PrependUint8Slot(0, gateKind, 0)

def AddGateKind(builder: flatbuffers.Builder, gateKind: int):
    EnsembleDecisionExplanationAddGateKind(builder, gateKind)

def EnsembleDecisionExplanationAddMarketState(builder: flatbuffers.Builder, marketState: int):
    builder.PrependUint8Slot(1, marketState, 0)

def AddMarketState(builder: flatbuffers.Builder, marketState: int):
    EnsembleDecisionExplanationAddMarketState(builder, marketState)

def EnsembleDecisionExplanationAddEventState(builder: flatbuffers.Builder, eventState: int):
    builder.PrependUint8Slot(2, eventState, 0)

def AddEventState(builder: flatbuffers.Builder, eventState: int):
    EnsembleDecisionExplanationAddEventState(builder, eventState)

def EnsembleDecisionExplanationAddInputDataQualityPpm(builder: flatbuffers.Builder, inputDataQualityPpm: int):
    builder.PrependUint32Slot(3, inputDataQualityPpm, 0)

def AddInputDataQualityPpm(builder: flatbuffers.Builder, inputDataQualityPpm: int):
    EnsembleDecisionExplanationAddInputDataQualityPpm(builder, inputDataQualityPpm)

def EnsembleDecisionExplanationAddSuppliedExpertCount(builder: flatbuffers.Builder, suppliedExpertCount: int):
    builder.PrependUint32Slot(4, suppliedExpertCount, 0)

def AddSuppliedExpertCount(builder: flatbuffers.Builder, suppliedExpertCount: int):
    EnsembleDecisionExplanationAddSuppliedExpertCount(builder, suppliedExpertCount)

def EnsembleDecisionExplanationAddEligibleExpertCount(builder: flatbuffers.Builder, eligibleExpertCount: int):
    builder.PrependUint32Slot(5, eligibleExpertCount, 0)

def AddEligibleExpertCount(builder: flatbuffers.Builder, eligibleExpertCount: int):
    EnsembleDecisionExplanationAddEligibleExpertCount(builder, eligibleExpertCount)

def EnsembleDecisionExplanationAddDominantForecastId(builder: flatbuffers.Builder, dominantForecastId: Any):
    builder.PrependStructSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(dominantForecastId), 0)

def AddDominantForecastId(builder: flatbuffers.Builder, dominantForecastId: Any):
    EnsembleDecisionExplanationAddDominantForecastId(builder, dominantForecastId)

def EnsembleDecisionExplanationAddDominantModelId(builder: flatbuffers.Builder, dominantModelId: Any):
    builder.PrependStructSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(dominantModelId), 0)

def AddDominantModelId(builder: flatbuffers.Builder, dominantModelId: Any):
    EnsembleDecisionExplanationAddDominantModelId(builder, dominantModelId)

def EnsembleDecisionExplanationAddDominantModelVersion(builder: flatbuffers.Builder, dominantModelVersion: Any):
    builder.PrependStructSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(dominantModelVersion), 0)

def AddDominantModelVersion(builder: flatbuffers.Builder, dominantModelVersion: Any):
    EnsembleDecisionExplanationAddDominantModelVersion(builder, dominantModelVersion)

def EnsembleDecisionExplanationAddDominantReason(builder: flatbuffers.Builder, dominantReason: int):
    builder.PrependUint8Slot(9, dominantReason, 0)

def AddDominantReason(builder: flatbuffers.Builder, dominantReason: int):
    EnsembleDecisionExplanationAddDominantReason(builder, dominantReason)

def EnsembleDecisionExplanationAddRequiredEdgePpm(builder: flatbuffers.Builder, requiredEdgePpm: int):
    builder.PrependUint64Slot(10, requiredEdgePpm, 0)

def AddRequiredEdgePpm(builder: flatbuffers.Builder, requiredEdgePpm: int):
    EnsembleDecisionExplanationAddRequiredEdgePpm(builder, requiredEdgePpm)

def EnsembleDecisionExplanationAddLearnedGateSignatureHash(builder: flatbuffers.Builder, learnedGateSignatureHash: int):
    builder.PrependUint64Slot(11, learnedGateSignatureHash, 0)

def AddLearnedGateSignatureHash(builder: flatbuffers.Builder, learnedGateSignatureHash: int):
    EnsembleDecisionExplanationAddLearnedGateSignatureHash(builder, learnedGateSignatureHash)

def EnsembleDecisionExplanationAddExplanationHash(builder: flatbuffers.Builder, explanationHash: int):
    builder.PrependUint64Slot(12, explanationHash, 0)

def AddExplanationHash(builder: flatbuffers.Builder, explanationHash: int):
    EnsembleDecisionExplanationAddExplanationHash(builder, explanationHash)

def EnsembleDecisionExplanationAddContributingExpertCount(builder: flatbuffers.Builder, contributingExpertCount: int):
    builder.PrependUint32Slot(13, contributingExpertCount, 0)

def AddContributingExpertCount(builder: flatbuffers.Builder, contributingExpertCount: int):
    EnsembleDecisionExplanationAddContributingExpertCount(builder, contributingExpertCount)

def EnsembleDecisionExplanationAddTransactionCostForecastHash(builder: flatbuffers.Builder, transactionCostForecastHash: int):
    builder.PrependUint64Slot(14, transactionCostForecastHash, 0)

def AddTransactionCostForecastHash(builder: flatbuffers.Builder, transactionCostForecastHash: int):
    EnsembleDecisionExplanationAddTransactionCostForecastHash(builder, transactionCostForecastHash)

def EnsembleDecisionExplanationAddMarketStateSnapshotHash(builder: flatbuffers.Builder, marketStateSnapshotHash: int):
    builder.PrependUint64Slot(15, marketStateSnapshotHash, 0)

def AddMarketStateSnapshotHash(builder: flatbuffers.Builder, marketStateSnapshotHash: int):
    EnsembleDecisionExplanationAddMarketStateSnapshotHash(builder, marketStateSnapshotHash)

def EnsembleDecisionExplanationAddConfigurationHash(builder: flatbuffers.Builder, configurationHash: int):
    builder.PrependUint64Slot(16, configurationHash, 0)

def AddConfigurationHash(builder: flatbuffers.Builder, configurationHash: int):
    EnsembleDecisionExplanationAddConfigurationHash(builder, configurationHash)

def EnsembleDecisionExplanationEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return EnsembleDecisionExplanationEnd(builder)
