# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

class EnsembleEventStateCode(object):
    UNKNOWN = 0
    NONE = 1
    SCHEDULED = 2
    BREAKING_NEWS = 3
    PRICE_DISCOVERY = 4
    VOLATILITY_SHOCK = 5
