from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from aegis.mx.contracts.v1.ChannelId import ChannelId
from aegis.mx.contracts.v1.ConfigurationVersion import ConfigurationVersion
from aegis.mx.contracts.v1.DataQualityCode import DataQualityCode
from aegis.mx.contracts.v1.ExchangeEventTimeNs import ExchangeEventTimeNs
from aegis.mx.contracts.v1.GlobalEventId import GlobalEventId
from aegis.mx.contracts.v1.InstrumentId import InstrumentId
from aegis.mx.contracts.v1.IntelligenceAdjudicationCode import IntelligenceAdjudicationCode
from aegis.mx.contracts.v1.IntelligenceDocumentType import IntelligenceDocumentType
from aegis.mx.contracts.v1.IntelligenceEventType import IntelligenceEventType
from aegis.mx.contracts.v1.IntelligenceEvidenceExcerpt import IntelligenceEvidenceExcerpt
from aegis.mx.contracts.v1.IntelligenceFact import IntelligenceFact
from aegis.mx.contracts.v1.IntelligenceResolvedEntity import IntelligenceResolvedEntity
from aegis.mx.contracts.v1.IntelligenceStage import IntelligenceStage
from aegis.mx.contracts.v1.IntelligenceTrustCode import IntelligenceTrustCode
from aegis.mx.contracts.v1.ModelId import ModelId
from aegis.mx.contracts.v1.ModelVersion import ModelVersion
from aegis.mx.contracts.v1.ProcessMonotonicTimeNs import ProcessMonotonicTimeNs
from aegis.mx.contracts.v1.SchemaVersion import SchemaVersion
from aegis.mx.contracts.v1.SessionId import SessionId
from aegis.mx.contracts.v1.Sha256Digest import Sha256Digest
from aegis.mx.contracts.v1.WallClockUtcTimeNs import WallClockUtcTimeNs

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class EventIntelligenceRecord:
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> EventIntelligenceRecord: ...
  @classmethod
  def GetRootAsEventIntelligenceRecord(cls, buf: bytes, offset: int) -> EventIntelligenceRecord: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def SchemaVersion(self) -> SchemaVersion | None: ...
  def GlobalEventId(self) -> GlobalEventId | None: ...
  def SessionId(self) -> SessionId | None: ...
  def SourceChannelId(self) -> ChannelId | None: ...
  def InstrumentId(self) -> InstrumentId | None: ...
  def ModelId(self) -> ModelId | None: ...
  def ModelVersion(self) -> ModelVersion | None: ...
  def ConfigurationVersion(self) -> ConfigurationVersion | None: ...
  def Trust(self) -> typing.Literal[DataQualityCode.UNKNOWN, DataQualityCode.VALID, DataQualityCode.DEGRADED, DataQualityCode.STALE, DataQualityCode.INVALID]: ...
  def TextTrust(self) -> typing.Literal[IntelligenceTrustCode.UNKNOWN, IntelligenceTrustCode.UNTRUSTED, IntelligenceTrustCode.SANITIZED, IntelligenceTrustCode.VERIFIED_SOURCE]: ...
  def ProviderEventTime(self) -> ExchangeEventTimeNs | None: ...
  def ReceivedWallClockUtcTime(self) -> WallClockUtcTimeNs | None: ...
  def ProcessedMonotonicTime(self) -> ProcessMonotonicTimeNs | None: ...
  def RelevancePpm(self) -> int: ...
  def ClassificationCode(self) -> int: ...
  def UntrustedSourceContentSha256(self) -> Sha256Digest | None: ...
  def SanitizedContentSha256(self) -> Sha256Digest | None: ...
  def DocumentType(self) -> typing.Literal[IntelligenceDocumentType.UNKNOWN, IntelligenceDocumentType.NEWS_ARTICLE, IntelligenceDocumentType.FILING, IntelligenceDocumentType.PRESS_RELEASE, IntelligenceDocumentType.REGULATORY_NOTICE, IntelligenceDocumentType.MACRO_RELEASE, IntelligenceDocumentType.CORRECTION]: ...
  def EventType(self) -> typing.Literal[IntelligenceEventType.UNKNOWN, IntelligenceEventType.EARNINGS_RELEASE, IntelligenceEventType.GUIDANCE_UPDATE, IntelligenceEventType.MERGER_ACQUISITION, IntelligenceEventType.PRODUCT_RECALL, IntelligenceEventType.REGULATORY_ACTION, IntelligenceEventType.EXECUTIVE_CHANGE, IntelligenceEventType.FINANCING, IntelligenceEventType.BANKRUPTCY, IntelligenceEventType.LITIGATION, IntelligenceEventType.CYBERSECURITY_INCIDENT, IntelligenceEventType.ANALYST_ACTION, IntelligenceEventType.SUPPLY_CHAIN_DISRUPTION, IntelligenceEventType.TRADING_HALT, IntelligenceEventType.MACRO_RELEASE, IntelligenceEventType.RUMOR, IntelligenceEventType.CORRECTION]: ...
  def Stage(self) -> typing.Literal[IntelligenceStage.UNKNOWN, IntelligenceStage.FAST, IntelligenceStage.DEEP]: ...
  def Adjudication(self) -> typing.Literal[IntelligenceAdjudicationCode.UNKNOWN, IntelligenceAdjudicationCode.PRELIMINARY, IntelligenceAdjudicationCode.CONFIRMED, IntelligenceAdjudicationCode.REFINED, IntelligenceAdjudicationCode.DISPUTED, IntelligenceAdjudicationCode.CORRECTED]: ...
  def Revision(self) -> int: ...
  def ParentFastGlobalEventId(self) -> GlobalEventId | None: ...
  def CorrectionOfGlobalEventId(self) -> GlobalEventId | None: ...
  def LanguageCode(self) -> str | None: ...
  def SourceProviderId(self) -> str | None: ...
  def SourceDocumentId(self) -> str | None: ...
  def SourceAuthenticationSha256(self) -> Sha256Digest | None: ...
  def NoveltyPpm(self) -> int: ...
  def MaterialityPpm(self) -> int: ...
  def SourceTrustPpm(self) -> int: ...
  def UncertaintyPpm(self) -> int: ...
  def PromptInjectionDetected(self) -> bool: ...
  def Entities(self, i: int) -> IntelligenceResolvedEntity | None: ...
  def EntitiesLength(self) -> int: ...
  def EntitiesIsNone(self) -> bool: ...
  def Facts(self, i: int) -> IntelligenceFact | None: ...
  def FactsLength(self) -> int: ...
  def FactsIsNone(self) -> bool: ...
  def Evidence(self, i: int) -> IntelligenceEvidenceExcerpt | None: ...
  def EvidenceLength(self) -> int: ...
  def EvidenceIsNone(self) -> bool: ...
  def ContradictsGlobalEventIds(self, i: int) -> GlobalEventId | None: ...
  def ContradictsGlobalEventIdsLength(self) -> int: ...
  def ContradictsGlobalEventIdsIsNone(self) -> bool: ...
def EventIntelligenceRecordStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def EventIntelligenceRecordAddSchemaVersion(builder: flatbuffers.Builder, schemaVersion: uoffset) -> None: ...
def EventIntelligenceRecordAddGlobalEventId(builder: flatbuffers.Builder, globalEventId: uoffset) -> None: ...
def EventIntelligenceRecordAddSessionId(builder: flatbuffers.Builder, sessionId: uoffset) -> None: ...
def EventIntelligenceRecordAddSourceChannelId(builder: flatbuffers.Builder, sourceChannelId: uoffset) -> None: ...
def EventIntelligenceRecordAddInstrumentId(builder: flatbuffers.Builder, instrumentId: uoffset) -> None: ...
def EventIntelligenceRecordAddModelId(builder: flatbuffers.Builder, modelId: uoffset) -> None: ...
def EventIntelligenceRecordAddModelVersion(builder: flatbuffers.Builder, modelVersion: uoffset) -> None: ...
def EventIntelligenceRecordAddConfigurationVersion(builder: flatbuffers.Builder, configurationVersion: uoffset) -> None: ...
def EventIntelligenceRecordAddTrust(builder: flatbuffers.Builder, trust: typing.Literal[DataQualityCode.UNKNOWN, DataQualityCode.VALID, DataQualityCode.DEGRADED, DataQualityCode.STALE, DataQualityCode.INVALID]) -> None: ...
def EventIntelligenceRecordAddTextTrust(builder: flatbuffers.Builder, textTrust: typing.Literal[IntelligenceTrustCode.UNKNOWN, IntelligenceTrustCode.UNTRUSTED, IntelligenceTrustCode.SANITIZED, IntelligenceTrustCode.VERIFIED_SOURCE]) -> None: ...
def EventIntelligenceRecordAddProviderEventTime(builder: flatbuffers.Builder, providerEventTime: uoffset) -> None: ...
def EventIntelligenceRecordAddReceivedWallClockUtcTime(builder: flatbuffers.Builder, receivedWallClockUtcTime: uoffset) -> None: ...
def EventIntelligenceRecordAddProcessedMonotonicTime(builder: flatbuffers.Builder, processedMonotonicTime: uoffset) -> None: ...
def EventIntelligenceRecordAddRelevancePpm(builder: flatbuffers.Builder, relevancePpm: int) -> None: ...
def EventIntelligenceRecordAddClassificationCode(builder: flatbuffers.Builder, classificationCode: int) -> None: ...
def EventIntelligenceRecordAddUntrustedSourceContentSha256(builder: flatbuffers.Builder, untrustedSourceContentSha256: uoffset) -> None: ...
def EventIntelligenceRecordAddSanitizedContentSha256(builder: flatbuffers.Builder, sanitizedContentSha256: uoffset) -> None: ...
def EventIntelligenceRecordAddDocumentType(builder: flatbuffers.Builder, documentType: typing.Literal[IntelligenceDocumentType.UNKNOWN, IntelligenceDocumentType.NEWS_ARTICLE, IntelligenceDocumentType.FILING, IntelligenceDocumentType.PRESS_RELEASE, IntelligenceDocumentType.REGULATORY_NOTICE, IntelligenceDocumentType.MACRO_RELEASE, IntelligenceDocumentType.CORRECTION]) -> None: ...
def EventIntelligenceRecordAddEventType(builder: flatbuffers.Builder, eventType: typing.Literal[IntelligenceEventType.UNKNOWN, IntelligenceEventType.EARNINGS_RELEASE, IntelligenceEventType.GUIDANCE_UPDATE, IntelligenceEventType.MERGER_ACQUISITION, IntelligenceEventType.PRODUCT_RECALL, IntelligenceEventType.REGULATORY_ACTION, IntelligenceEventType.EXECUTIVE_CHANGE, IntelligenceEventType.FINANCING, IntelligenceEventType.BANKRUPTCY, IntelligenceEventType.LITIGATION, IntelligenceEventType.CYBERSECURITY_INCIDENT, IntelligenceEventType.ANALYST_ACTION, IntelligenceEventType.SUPPLY_CHAIN_DISRUPTION, IntelligenceEventType.TRADING_HALT, IntelligenceEventType.MACRO_RELEASE, IntelligenceEventType.RUMOR, IntelligenceEventType.CORRECTION]) -> None: ...
def EventIntelligenceRecordAddStage(builder: flatbuffers.Builder, stage: typing.Literal[IntelligenceStage.UNKNOWN, IntelligenceStage.FAST, IntelligenceStage.DEEP]) -> None: ...
def EventIntelligenceRecordAddAdjudication(builder: flatbuffers.Builder, adjudication: typing.Literal[IntelligenceAdjudicationCode.UNKNOWN, IntelligenceAdjudicationCode.PRELIMINARY, IntelligenceAdjudicationCode.CONFIRMED, IntelligenceAdjudicationCode.REFINED, IntelligenceAdjudicationCode.DISPUTED, IntelligenceAdjudicationCode.CORRECTED]) -> None: ...
def EventIntelligenceRecordAddRevision(builder: flatbuffers.Builder, revision: int) -> None: ...
def EventIntelligenceRecordAddParentFastGlobalEventId(builder: flatbuffers.Builder, parentFastGlobalEventId: uoffset) -> None: ...
def EventIntelligenceRecordAddCorrectionOfGlobalEventId(builder: flatbuffers.Builder, correctionOfGlobalEventId: uoffset) -> None: ...
def EventIntelligenceRecordAddLanguageCode(builder: flatbuffers.Builder, languageCode: uoffset) -> None: ...
def EventIntelligenceRecordAddSourceProviderId(builder: flatbuffers.Builder, sourceProviderId: uoffset) -> None: ...
def EventIntelligenceRecordAddSourceDocumentId(builder: flatbuffers.Builder, sourceDocumentId: uoffset) -> None: ...
def EventIntelligenceRecordAddSourceAuthenticationSha256(builder: flatbuffers.Builder, sourceAuthenticationSha256: uoffset) -> None: ...
def EventIntelligenceRecordAddNoveltyPpm(builder: flatbuffers.Builder, noveltyPpm: int) -> None: ...
def EventIntelligenceRecordAddMaterialityPpm(builder: flatbuffers.Builder, materialityPpm: int) -> None: ...
def EventIntelligenceRecordAddSourceTrustPpm(builder: flatbuffers.Builder, sourceTrustPpm: int) -> None: ...
def EventIntelligenceRecordAddUncertaintyPpm(builder: flatbuffers.Builder, uncertaintyPpm: int) -> None: ...
def EventIntelligenceRecordAddPromptInjectionDetected(builder: flatbuffers.Builder, promptInjectionDetected: bool) -> None: ...
def EventIntelligenceRecordAddEntities(builder: flatbuffers.Builder, entities: uoffset) -> None: ...
def EventIntelligenceRecordStartEntitiesVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartEntitiesVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def EventIntelligenceRecordAddFacts(builder: flatbuffers.Builder, facts: uoffset) -> None: ...
def EventIntelligenceRecordStartFactsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartFactsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def EventIntelligenceRecordAddEvidence(builder: flatbuffers.Builder, evidence: uoffset) -> None: ...
def EventIntelligenceRecordStartEvidenceVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartEvidenceVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def EventIntelligenceRecordAddContradictsGlobalEventIds(builder: flatbuffers.Builder, contradictsGlobalEventIds: uoffset) -> None: ...
def EventIntelligenceRecordStartContradictsGlobalEventIdsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartContradictsGlobalEventIdsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def EventIntelligenceRecordEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

