# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from aegis.mx.contracts.v1.ChannelId import ChannelId
from aegis.mx.contracts.v1.ConfigurationVersion import ConfigurationVersion
from aegis.mx.contracts.v1.ExchangeEventTimeNs import ExchangeEventTimeNs
from aegis.mx.contracts.v1.GlobalEventId import GlobalEventId
from aegis.mx.contracts.v1.InstrumentId import InstrumentId
from aegis.mx.contracts.v1.IntelligenceEvidenceExcerpt import IntelligenceEvidenceExcerpt
from aegis.mx.contracts.v1.IntelligenceFact import IntelligenceFact
from aegis.mx.contracts.v1.IntelligenceResolvedEntity import IntelligenceResolvedEntity
from aegis.mx.contracts.v1.ModelId import ModelId
from aegis.mx.contracts.v1.ModelVersion import ModelVersion
from aegis.mx.contracts.v1.ProcessMonotonicTimeNs import ProcessMonotonicTimeNs
from aegis.mx.contracts.v1.SchemaVersion import SchemaVersion
from aegis.mx.contracts.v1.SessionId import SessionId
from aegis.mx.contracts.v1.Sha256Digest import Sha256Digest
from aegis.mx.contracts.v1.WallClockUtcTimeNs import WallClockUtcTimeNs
from typing import Optional
np = import_numpy()

class EventIntelligenceRecord(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = EventIntelligenceRecord()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsEventIntelligenceRecord(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # EventIntelligenceRecord
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # EventIntelligenceRecord
    def SchemaVersion(self) -> Optional[SchemaVersion]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            obj = SchemaVersion()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # EventIntelligenceRecord
    def GlobalEventId(self) -> Optional[GlobalEventId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            obj = GlobalEventId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # EventIntelligenceRecord
    def SessionId(self) -> Optional[SessionId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = o + self._tab.Pos
            obj = SessionId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # EventIntelligenceRecord
    def SourceChannelId(self) -> Optional[ChannelId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = o + self._tab.Pos
            obj = ChannelId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # EventIntelligenceRecord
    def InstrumentId(self) -> Optional[InstrumentId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = o + self._tab.Pos
            obj = InstrumentId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # EventIntelligenceRecord
    def ModelId(self) -> Optional[ModelId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = o + self._tab.Pos
            obj = ModelId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # EventIntelligenceRecord
    def ModelVersion(self) -> Optional[ModelVersion]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            x = o + self._tab.Pos
            obj = ModelVersion()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # EventIntelligenceRecord
    def ConfigurationVersion(self) -> Optional[ConfigurationVersion]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            x = o + self._tab.Pos
            obj = ConfigurationVersion()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # EventIntelligenceRecord
    def Trust(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # EventIntelligenceRecord
    def TextTrust(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # EventIntelligenceRecord
    def ProviderEventTime(self) -> Optional[ExchangeEventTimeNs]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            x = o + self._tab.Pos
            obj = ExchangeEventTimeNs()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # EventIntelligenceRecord
    def ReceivedWallClockUtcTime(self) -> Optional[WallClockUtcTimeNs]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            x = o + self._tab.Pos
            obj = WallClockUtcTimeNs()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # EventIntelligenceRecord
    def ProcessedMonotonicTime(self) -> Optional[ProcessMonotonicTimeNs]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            x = o + self._tab.Pos
            obj = ProcessMonotonicTimeNs()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # EventIntelligenceRecord
    def RelevancePpm(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # EventIntelligenceRecord
    def ClassificationCode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # EventIntelligenceRecord
    def UntrustedSourceContentSha256(self) -> Optional[Sha256Digest]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            x = o + self._tab.Pos
            obj = Sha256Digest()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # EventIntelligenceRecord
    def SanitizedContentSha256(self) -> Optional[Sha256Digest]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        if o != 0:
            x = o + self._tab.Pos
            obj = Sha256Digest()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # EventIntelligenceRecord
    def DocumentType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(38))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # EventIntelligenceRecord
    def EventType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(40))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # EventIntelligenceRecord
    def Stage(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(42))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # EventIntelligenceRecord
    def Adjudication(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(44))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # EventIntelligenceRecord
    def Revision(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(46))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # EventIntelligenceRecord
    def ParentFastGlobalEventId(self) -> Optional[GlobalEventId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(48))
        if o != 0:
            x = o + self._tab.Pos
            obj = GlobalEventId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # EventIntelligenceRecord
    def CorrectionOfGlobalEventId(self) -> Optional[GlobalEventId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(50))
        if o != 0:
            x = o + self._tab.Pos
            obj = GlobalEventId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # EventIntelligenceRecord
    def LanguageCode(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(52))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # EventIntelligenceRecord
    def SourceProviderId(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(54))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # EventIntelligenceRecord
    def SourceDocumentId(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(56))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # EventIntelligenceRecord
    def SourceAuthenticationSha256(self) -> Optional[Sha256Digest]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(58))
        if o != 0:
            x = o + self._tab.Pos
            obj = Sha256Digest()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # EventIntelligenceRecord
    def NoveltyPpm(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(60))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # EventIntelligenceRecord
    def MaterialityPpm(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(62))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # EventIntelligenceRecord
    def SourceTrustPpm(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(64))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # EventIntelligenceRecord
    def UncertaintyPpm(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(66))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # EventIntelligenceRecord
    def PromptInjectionDetected(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(68))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # EventIntelligenceRecord
    def Entities(self, j: int) -> Optional[IntelligenceResolvedEntity]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(70))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = IntelligenceResolvedEntity()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # EventIntelligenceRecord
    def EntitiesLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(70))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # EventIntelligenceRecord
    def EntitiesIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(70))
        return o == 0

    # EventIntelligenceRecord
    def Facts(self, j: int) -> Optional[IntelligenceFact]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(72))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = IntelligenceFact()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # EventIntelligenceRecord
    def FactsLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(72))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # EventIntelligenceRecord
    def FactsIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(72))
        return o == 0

    # EventIntelligenceRecord
    def Evidence(self, j: int) -> Optional[IntelligenceEvidenceExcerpt]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(74))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = IntelligenceEvidenceExcerpt()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # EventIntelligenceRecord
    def EvidenceLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(74))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # EventIntelligenceRecord
    def EvidenceIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(74))
        return o == 0

    # EventIntelligenceRecord
    def ContradictsGlobalEventIds(self, j: int) -> Optional[GlobalEventId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(76))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 16
            obj = GlobalEventId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # EventIntelligenceRecord
    def ContradictsGlobalEventIdsLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(76))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # EventIntelligenceRecord
    def ContradictsGlobalEventIdsIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(76))
        return o == 0

def EventIntelligenceRecordStart(builder: flatbuffers.Builder):
    builder.StartObject(37)

def Start(builder: flatbuffers.Builder):
    EventIntelligenceRecordStart(builder)

def EventIntelligenceRecordAddSchemaVersion(builder: flatbuffers.Builder, schemaVersion: Any):
    builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(schemaVersion), 0)

def AddSchemaVersion(builder: flatbuffers.Builder, schemaVersion: Any):
    EventIntelligenceRecordAddSchemaVersion(builder, schemaVersion)

def EventIntelligenceRecordAddGlobalEventId(builder: flatbuffers.Builder, globalEventId: Any):
    builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(globalEventId), 0)

def AddGlobalEventId(builder: flatbuffers.Builder, globalEventId: Any):
    EventIntelligenceRecordAddGlobalEventId(builder, globalEventId)

def EventIntelligenceRecordAddSessionId(builder: flatbuffers.Builder, sessionId: Any):
    builder.PrependStructSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(sessionId), 0)

def AddSessionId(builder: flatbuffers.Builder, sessionId: Any):
    EventIntelligenceRecordAddSessionId(builder, sessionId)

def EventIntelligenceRecordAddSourceChannelId(builder: flatbuffers.Builder, sourceChannelId: Any):
    builder.PrependStructSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(sourceChannelId), 0)

def AddSourceChannelId(builder: flatbuffers.Builder, sourceChannelId: Any):
    EventIntelligenceRecordAddSourceChannelId(builder, sourceChannelId)

def EventIntelligenceRecordAddInstrumentId(builder: flatbuffers.Builder, instrumentId: Any):
    builder.PrependStructSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(instrumentId), 0)

def AddInstrumentId(builder: flatbuffers.Builder, instrumentId: Any):
    EventIntelligenceRecordAddInstrumentId(builder, instrumentId)

def EventIntelligenceRecordAddModelId(builder: flatbuffers.Builder, modelId: Any):
    builder.PrependStructSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(modelId), 0)

def AddModelId(builder: flatbuffers.Builder, modelId: Any):
    EventIntelligenceRecordAddModelId(builder, modelId)

def EventIntelligenceRecordAddModelVersion(builder: flatbuffers.Builder, modelVersion: Any):
    builder.PrependStructSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(modelVersion), 0)

def AddModelVersion(builder: flatbuffers.Builder, modelVersion: Any):
    EventIntelligenceRecordAddModelVersion(builder, modelVersion)

def EventIntelligenceRecordAddConfigurationVersion(builder: flatbuffers.Builder, configurationVersion: Any):
    builder.PrependStructSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(configurationVersion), 0)

def AddConfigurationVersion(builder: flatbuffers.Builder, configurationVersion: Any):
    EventIntelligenceRecordAddConfigurationVersion(builder, configurationVersion)

def EventIntelligenceRecordAddTrust(builder: flatbuffers.Builder, trust: int):
    builder.PrependUint8Slot(8, trust, 0)

def AddTrust(builder: flatbuffers.Builder, trust: int):
    EventIntelligenceRecordAddTrust(builder, trust)

def EventIntelligenceRecordAddTextTrust(builder: flatbuffers.Builder, textTrust: int):
    builder.PrependUint8Slot(9, textTrust, 0)

def AddTextTrust(builder: flatbuffers.Builder, textTrust: int):
    EventIntelligenceRecordAddTextTrust(builder, textTrust)

def EventIntelligenceRecordAddProviderEventTime(builder: flatbuffers.Builder, providerEventTime: Any):
    builder.PrependStructSlot(10, flatbuffers.number_types.UOffsetTFlags.py_type(providerEventTime), 0)

def AddProviderEventTime(builder: flatbuffers.Builder, providerEventTime: Any):
    EventIntelligenceRecordAddProviderEventTime(builder, providerEventTime)

def EventIntelligenceRecordAddReceivedWallClockUtcTime(builder: flatbuffers.Builder, receivedWallClockUtcTime: Any):
    builder.PrependStructSlot(11, flatbuffers.number_types.UOffsetTFlags.py_type(receivedWallClockUtcTime), 0)

def AddReceivedWallClockUtcTime(builder: flatbuffers.Builder, receivedWallClockUtcTime: Any):
    EventIntelligenceRecordAddReceivedWallClockUtcTime(builder, receivedWallClockUtcTime)

def EventIntelligenceRecordAddProcessedMonotonicTime(builder: flatbuffers.Builder, processedMonotonicTime: Any):
    builder.PrependStructSlot(12, flatbuffers.number_types.UOffsetTFlags.py_type(processedMonotonicTime), 0)

def AddProcessedMonotonicTime(builder: flatbuffers.Builder, processedMonotonicTime: Any):
    EventIntelligenceRecordAddProcessedMonotonicTime(builder, processedMonotonicTime)

def EventIntelligenceRecordAddRelevancePpm(builder: flatbuffers.Builder, relevancePpm: int):
    builder.PrependUint32Slot(13, relevancePpm, 0)

def AddRelevancePpm(builder: flatbuffers.Builder, relevancePpm: int):
    EventIntelligenceRecordAddRelevancePpm(builder, relevancePpm)

def EventIntelligenceRecordAddClassificationCode(builder: flatbuffers.Builder, classificationCode: int):
    builder.PrependUint32Slot(14, classificationCode, 0)

def AddClassificationCode(builder: flatbuffers.Builder, classificationCode: int):
    EventIntelligenceRecordAddClassificationCode(builder, classificationCode)

def EventIntelligenceRecordAddUntrustedSourceContentSha256(builder: flatbuffers.Builder, untrustedSourceContentSha256: Any):
    builder.PrependStructSlot(15, flatbuffers.number_types.UOffsetTFlags.py_type(untrustedSourceContentSha256), 0)

def AddUntrustedSourceContentSha256(builder: flatbuffers.Builder, untrustedSourceContentSha256: Any):
    EventIntelligenceRecordAddUntrustedSourceContentSha256(builder, untrustedSourceContentSha256)

def EventIntelligenceRecordAddSanitizedContentSha256(builder: flatbuffers.Builder, sanitizedContentSha256: Any):
    builder.PrependStructSlot(16, flatbuffers.number_types.UOffsetTFlags.py_type(sanitizedContentSha256), 0)

def AddSanitizedContentSha256(builder: flatbuffers.Builder, sanitizedContentSha256: Any):
    EventIntelligenceRecordAddSanitizedContentSha256(builder, sanitizedContentSha256)

def EventIntelligenceRecordAddDocumentType(builder: flatbuffers.Builder, documentType: int):
    builder.PrependUint8Slot(17, documentType, 0)

def AddDocumentType(builder: flatbuffers.Builder, documentType: int):
    EventIntelligenceRecordAddDocumentType(builder, documentType)

def EventIntelligenceRecordAddEventType(builder: flatbuffers.Builder, eventType: int):
    builder.PrependUint8Slot(18, eventType, 0)

def AddEventType(builder: flatbuffers.Builder, eventType: int):
    EventIntelligenceRecordAddEventType(builder, eventType)

def EventIntelligenceRecordAddStage(builder: flatbuffers.Builder, stage: int):
    builder.PrependUint8Slot(19, stage, 0)

def AddStage(builder: flatbuffers.Builder, stage: int):
    EventIntelligenceRecordAddStage(builder, stage)

def EventIntelligenceRecordAddAdjudication(builder: flatbuffers.Builder, adjudication: int):
    builder.PrependUint8Slot(20, adjudication, 0)

def AddAdjudication(builder: flatbuffers.Builder, adjudication: int):
    EventIntelligenceRecordAddAdjudication(builder, adjudication)

def EventIntelligenceRecordAddRevision(builder: flatbuffers.Builder, revision: int):
    builder.PrependUint32Slot(21, revision, 0)

def AddRevision(builder: flatbuffers.Builder, revision: int):
    EventIntelligenceRecordAddRevision(builder, revision)

def EventIntelligenceRecordAddParentFastGlobalEventId(builder: flatbuffers.Builder, parentFastGlobalEventId: Any):
    builder.PrependStructSlot(22, flatbuffers.number_types.UOffsetTFlags.py_type(parentFastGlobalEventId), 0)

def AddParentFastGlobalEventId(builder: flatbuffers.Builder, parentFastGlobalEventId: Any):
    EventIntelligenceRecordAddParentFastGlobalEventId(builder, parentFastGlobalEventId)

def EventIntelligenceRecordAddCorrectionOfGlobalEventId(builder: flatbuffers.Builder, correctionOfGlobalEventId: Any):
    builder.PrependStructSlot(23, flatbuffers.number_types.UOffsetTFlags.py_type(correctionOfGlobalEventId), 0)

def AddCorrectionOfGlobalEventId(builder: flatbuffers.Builder, correctionOfGlobalEventId: Any):
    EventIntelligenceRecordAddCorrectionOfGlobalEventId(builder, correctionOfGlobalEventId)

def EventIntelligenceRecordAddLanguageCode(builder: flatbuffers.Builder, languageCode: int):
    builder.PrependUOffsetTRelativeSlot(24, flatbuffers.number_types.UOffsetTFlags.py_type(languageCode), 0)

def AddLanguageCode(builder: flatbuffers.Builder, languageCode: int):
    EventIntelligenceRecordAddLanguageCode(builder, languageCode)

def EventIntelligenceRecordAddSourceProviderId(builder: flatbuffers.Builder, sourceProviderId: int):
    builder.PrependUOffsetTRelativeSlot(25, flatbuffers.number_types.UOffsetTFlags.py_type(sourceProviderId), 0)

def AddSourceProviderId(builder: flatbuffers.Builder, sourceProviderId: int):
    EventIntelligenceRecordAddSourceProviderId(builder, sourceProviderId)

def EventIntelligenceRecordAddSourceDocumentId(builder: flatbuffers.Builder, sourceDocumentId: int):
    builder.PrependUOffsetTRelativeSlot(26, flatbuffers.number_types.UOffsetTFlags.py_type(sourceDocumentId), 0)

def AddSourceDocumentId(builder: flatbuffers.Builder, sourceDocumentId: int):
    EventIntelligenceRecordAddSourceDocumentId(builder, sourceDocumentId)

def EventIntelligenceRecordAddSourceAuthenticationSha256(builder: flatbuffers.Builder, sourceAuthenticationSha256: Any):
    builder.PrependStructSlot(27, flatbuffers.number_types.UOffsetTFlags.py_type(sourceAuthenticationSha256), 0)

def AddSourceAuthenticationSha256(builder: flatbuffers.Builder, sourceAuthenticationSha256: Any):
    EventIntelligenceRecordAddSourceAuthenticationSha256(builder, sourceAuthenticationSha256)

def EventIntelligenceRecordAddNoveltyPpm(builder: flatbuffers.Builder, noveltyPpm: int):
    builder.PrependUint32Slot(28, noveltyPpm, 0)

def AddNoveltyPpm(builder: flatbuffers.Builder, noveltyPpm: int):
    EventIntelligenceRecordAddNoveltyPpm(builder, noveltyPpm)

def EventIntelligenceRecordAddMaterialityPpm(builder: flatbuffers.Builder, materialityPpm: int):
    builder.PrependUint32Slot(29, materialityPpm, 0)

def AddMaterialityPpm(builder: flatbuffers.Builder, materialityPpm: int):
    EventIntelligenceRecordAddMaterialityPpm(builder, materialityPpm)

def EventIntelligenceRecordAddSourceTrustPpm(builder: flatbuffers.Builder, sourceTrustPpm: int):
    builder.PrependUint32Slot(30, sourceTrustPpm, 0)

def AddSourceTrustPpm(builder: flatbuffers.Builder, sourceTrustPpm: int):
    EventIntelligenceRecordAddSourceTrustPpm(builder, sourceTrustPpm)

def EventIntelligenceRecordAddUncertaintyPpm(builder: flatbuffers.Builder, uncertaintyPpm: int):
    builder.PrependUint32Slot(31, uncertaintyPpm, 0)

def AddUncertaintyPpm(builder: flatbuffers.Builder, uncertaintyPpm: int):
    EventIntelligenceRecordAddUncertaintyPpm(builder, uncertaintyPpm)

def EventIntelligenceRecordAddPromptInjectionDetected(builder: flatbuffers.Builder, promptInjectionDetected: bool):
    builder.PrependBoolSlot(32, promptInjectionDetected, 0)

def AddPromptInjectionDetected(builder: flatbuffers.Builder, promptInjectionDetected: bool):
    EventIntelligenceRecordAddPromptInjectionDetected(builder, promptInjectionDetected)

def EventIntelligenceRecordAddEntities(builder: flatbuffers.Builder, entities: int):
    builder.PrependUOffsetTRelativeSlot(33, flatbuffers.number_types.UOffsetTFlags.py_type(entities), 0)

def AddEntities(builder: flatbuffers.Builder, entities: int):
    EventIntelligenceRecordAddEntities(builder, entities)

def EventIntelligenceRecordStartEntitiesVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartEntitiesVector(builder, numElems: int) -> int:
    return EventIntelligenceRecordStartEntitiesVector(builder, numElems)

def EventIntelligenceRecordAddFacts(builder: flatbuffers.Builder, facts: int):
    builder.PrependUOffsetTRelativeSlot(34, flatbuffers.number_types.UOffsetTFlags.py_type(facts), 0)

def AddFacts(builder: flatbuffers.Builder, facts: int):
    EventIntelligenceRecordAddFacts(builder, facts)

def EventIntelligenceRecordStartFactsVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartFactsVector(builder, numElems: int) -> int:
    return EventIntelligenceRecordStartFactsVector(builder, numElems)

def EventIntelligenceRecordAddEvidence(builder: flatbuffers.Builder, evidence: int):
    builder.PrependUOffsetTRelativeSlot(35, flatbuffers.number_types.UOffsetTFlags.py_type(evidence), 0)

def AddEvidence(builder: flatbuffers.Builder, evidence: int):
    EventIntelligenceRecordAddEvidence(builder, evidence)

def EventIntelligenceRecordStartEvidenceVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartEvidenceVector(builder, numElems: int) -> int:
    return EventIntelligenceRecordStartEvidenceVector(builder, numElems)

def EventIntelligenceRecordAddContradictsGlobalEventIds(builder: flatbuffers.Builder, contradictsGlobalEventIds: int):
    builder.PrependUOffsetTRelativeSlot(36, flatbuffers.number_types.UOffsetTFlags.py_type(contradictsGlobalEventIds), 0)

def AddContradictsGlobalEventIds(builder: flatbuffers.Builder, contradictsGlobalEventIds: int):
    EventIntelligenceRecordAddContradictsGlobalEventIds(builder, contradictsGlobalEventIds)

def EventIntelligenceRecordStartContradictsGlobalEventIdsVector(builder, numElems: int) -> int:
    return builder.StartVector(16, numElems, 8)

def StartContradictsGlobalEventIdsVector(builder, numElems: int) -> int:
    return EventIntelligenceRecordStartContradictsGlobalEventIdsVector(builder, numElems)

def EventIntelligenceRecordEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return EventIntelligenceRecordEnd(builder)
