from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from aegis.mx.contracts.v1.ConfigurationVersion import ConfigurationVersion
from aegis.mx.contracts.v1.ExchangeEventTimeNs import ExchangeEventTimeNs
from aegis.mx.contracts.v1.FeatureSnapshotId import FeatureSnapshotId
from aegis.mx.contracts.v1.GlobalEventId import GlobalEventId
from aegis.mx.contracts.v1.InstrumentId import InstrumentId
from aegis.mx.contracts.v1.ProcessMonotonicTimeNs import ProcessMonotonicTimeNs
from aegis.mx.contracts.v1.SchemaVersion import SchemaVersion
from aegis.mx.contracts.v1.SessionId import SessionId
from aegis.mx.contracts.v1.Sha256Digest import Sha256Digest

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class FeatureSnapshotMetadata:
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> FeatureSnapshotMetadata: ...
  @classmethod
  def GetRootAsFeatureSnapshotMetadata(cls, buf: bytes, offset: int) -> FeatureSnapshotMetadata: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def SchemaVersion(self) -> SchemaVersion | None: ...
  def FeatureSnapshotId(self) -> FeatureSnapshotId | None: ...
  def SessionId(self) -> SessionId | None: ...
  def InstrumentId(self) -> InstrumentId | None: ...
  def FeatureDefinitionVersion(self) -> ConfigurationVersion | None: ...
  def SourceFirstGlobalEventId(self) -> GlobalEventId | None: ...
  def SourceLastGlobalEventId(self) -> GlobalEventId | None: ...
  def AsOfExchangeEventTime(self) -> ExchangeEventTimeNs | None: ...
  def CreatedProcessMonotonicTime(self) -> ProcessMonotonicTimeNs | None: ...
  def FeatureCount(self) -> int: ...
  def FeaturePayloadSha256(self) -> Sha256Digest | None: ...
def FeatureSnapshotMetadataStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def FeatureSnapshotMetadataAddSchemaVersion(builder: flatbuffers.Builder, schemaVersion: uoffset) -> None: ...
def FeatureSnapshotMetadataAddFeatureSnapshotId(builder: flatbuffers.Builder, featureSnapshotId: uoffset) -> None: ...
def FeatureSnapshotMetadataAddSessionId(builder: flatbuffers.Builder, sessionId: uoffset) -> None: ...
def FeatureSnapshotMetadataAddInstrumentId(builder: flatbuffers.Builder, instrumentId: uoffset) -> None: ...
def FeatureSnapshotMetadataAddFeatureDefinitionVersion(builder: flatbuffers.Builder, featureDefinitionVersion: uoffset) -> None: ...
def FeatureSnapshotMetadataAddSourceFirstGlobalEventId(builder: flatbuffers.Builder, sourceFirstGlobalEventId: uoffset) -> None: ...
def FeatureSnapshotMetadataAddSourceLastGlobalEventId(builder: flatbuffers.Builder, sourceLastGlobalEventId: uoffset) -> None: ...
def FeatureSnapshotMetadataAddAsOfExchangeEventTime(builder: flatbuffers.Builder, asOfExchangeEventTime: uoffset) -> None: ...
def FeatureSnapshotMetadataAddCreatedProcessMonotonicTime(builder: flatbuffers.Builder, createdProcessMonotonicTime: uoffset) -> None: ...
def FeatureSnapshotMetadataAddFeatureCount(builder: flatbuffers.Builder, featureCount: int) -> None: ...
def FeatureSnapshotMetadataAddFeaturePayloadSha256(builder: flatbuffers.Builder, featurePayloadSha256: uoffset) -> None: ...
def FeatureSnapshotMetadataEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

