# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from aegis.mx.contracts.v1.ConfigurationVersion import ConfigurationVersion
from aegis.mx.contracts.v1.ExchangeEventTimeNs import ExchangeEventTimeNs
from aegis.mx.contracts.v1.FeatureSnapshotId import FeatureSnapshotId
from aegis.mx.contracts.v1.GlobalEventId import GlobalEventId
from aegis.mx.contracts.v1.InstrumentId import InstrumentId
from aegis.mx.contracts.v1.ProcessMonotonicTimeNs import ProcessMonotonicTimeNs
from aegis.mx.contracts.v1.SchemaVersion import SchemaVersion
from aegis.mx.contracts.v1.SessionId import SessionId
from aegis.mx.contracts.v1.Sha256Digest import Sha256Digest
from typing import Optional
np = import_numpy()

class FeatureSnapshotMetadata(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FeatureSnapshotMetadata()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFeatureSnapshotMetadata(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # FeatureSnapshotMetadata
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FeatureSnapshotMetadata
    def SchemaVersion(self) -> Optional[SchemaVersion]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            obj = SchemaVersion()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # FeatureSnapshotMetadata
    def FeatureSnapshotId(self) -> Optional[FeatureSnapshotId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            obj = FeatureSnapshotId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # FeatureSnapshotMetadata
    def SessionId(self) -> Optional[SessionId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = o + self._tab.Pos
            obj = SessionId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # FeatureSnapshotMetadata
    def InstrumentId(self) -> Optional[InstrumentId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = o + self._tab.Pos
            obj = InstrumentId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # FeatureSnapshotMetadata
    def FeatureDefinitionVersion(self) -> Optional[ConfigurationVersion]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = o + self._tab.Pos
            obj = ConfigurationVersion()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # FeatureSnapshotMetadata
    def SourceFirstGlobalEventId(self) -> Optional[GlobalEventId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = o + self._tab.Pos
            obj = GlobalEventId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # FeatureSnapshotMetadata
    def SourceLastGlobalEventId(self) -> Optional[GlobalEventId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            x = o + self._tab.Pos
            obj = GlobalEventId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # FeatureSnapshotMetadata
    def AsOfExchangeEventTime(self) -> Optional[ExchangeEventTimeNs]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            x = o + self._tab.Pos
            obj = ExchangeEventTimeNs()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # FeatureSnapshotMetadata
    def CreatedProcessMonotonicTime(self) -> Optional[ProcessMonotonicTimeNs]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            x = o + self._tab.Pos
            obj = ProcessMonotonicTimeNs()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # FeatureSnapshotMetadata
    def FeatureCount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # FeatureSnapshotMetadata
    def FeaturePayloadSha256(self) -> Optional[Sha256Digest]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            x = o + self._tab.Pos
            obj = Sha256Digest()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def FeatureSnapshotMetadataStart(builder: flatbuffers.Builder):
    builder.StartObject(11)

def Start(builder: flatbuffers.Builder):
    FeatureSnapshotMetadataStart(builder)

def FeatureSnapshotMetadataAddSchemaVersion(builder: flatbuffers.Builder, schemaVersion: Any):
    builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(schemaVersion), 0)

def AddSchemaVersion(builder: flatbuffers.Builder, schemaVersion: Any):
    FeatureSnapshotMetadataAddSchemaVersion(builder, schemaVersion)

def FeatureSnapshotMetadataAddFeatureSnapshotId(builder: flatbuffers.Builder, featureSnapshotId: Any):
    builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(featureSnapshotId), 0)

def AddFeatureSnapshotId(builder: flatbuffers.Builder, featureSnapshotId: Any):
    FeatureSnapshotMetadataAddFeatureSnapshotId(builder, featureSnapshotId)

def FeatureSnapshotMetadataAddSessionId(builder: flatbuffers.Builder, sessionId: Any):
    builder.PrependStructSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(sessionId), 0)

def AddSessionId(builder: flatbuffers.Builder, sessionId: Any):
    FeatureSnapshotMetadataAddSessionId(builder, sessionId)

def FeatureSnapshotMetadataAddInstrumentId(builder: flatbuffers.Builder, instrumentId: Any):
    builder.PrependStructSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(instrumentId), 0)

def AddInstrumentId(builder: flatbuffers.Builder, instrumentId: Any):
    FeatureSnapshotMetadataAddInstrumentId(builder, instrumentId)

def FeatureSnapshotMetadataAddFeatureDefinitionVersion(builder: flatbuffers.Builder, featureDefinitionVersion: Any):
    builder.PrependStructSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(featureDefinitionVersion), 0)

def AddFeatureDefinitionVersion(builder: flatbuffers.Builder, featureDefinitionVersion: Any):
    FeatureSnapshotMetadataAddFeatureDefinitionVersion(builder, featureDefinitionVersion)

def FeatureSnapshotMetadataAddSourceFirstGlobalEventId(builder: flatbuffers.Builder, sourceFirstGlobalEventId: Any):
    builder.PrependStructSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(sourceFirstGlobalEventId), 0)

def AddSourceFirstGlobalEventId(builder: flatbuffers.Builder, sourceFirstGlobalEventId: Any):
    FeatureSnapshotMetadataAddSourceFirstGlobalEventId(builder, sourceFirstGlobalEventId)

def FeatureSnapshotMetadataAddSourceLastGlobalEventId(builder: flatbuffers.Builder, sourceLastGlobalEventId: Any):
    builder.PrependStructSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(sourceLastGlobalEventId), 0)

def AddSourceLastGlobalEventId(builder: flatbuffers.Builder, sourceLastGlobalEventId: Any):
    FeatureSnapshotMetadataAddSourceLastGlobalEventId(builder, sourceLastGlobalEventId)

def FeatureSnapshotMetadataAddAsOfExchangeEventTime(builder: flatbuffers.Builder, asOfExchangeEventTime: Any):
    builder.PrependStructSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(asOfExchangeEventTime), 0)

def AddAsOfExchangeEventTime(builder: flatbuffers.Builder, asOfExchangeEventTime: Any):
    FeatureSnapshotMetadataAddAsOfExchangeEventTime(builder, asOfExchangeEventTime)

def FeatureSnapshotMetadataAddCreatedProcessMonotonicTime(builder: flatbuffers.Builder, createdProcessMonotonicTime: Any):
    builder.PrependStructSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(createdProcessMonotonicTime), 0)

def AddCreatedProcessMonotonicTime(builder: flatbuffers.Builder, createdProcessMonotonicTime: Any):
    FeatureSnapshotMetadataAddCreatedProcessMonotonicTime(builder, createdProcessMonotonicTime)

def FeatureSnapshotMetadataAddFeatureCount(builder: flatbuffers.Builder, featureCount: int):
    builder.PrependUint32Slot(9, featureCount, 0)

def AddFeatureCount(builder: flatbuffers.Builder, featureCount: int):
    FeatureSnapshotMetadataAddFeatureCount(builder, featureCount)

def FeatureSnapshotMetadataAddFeaturePayloadSha256(builder: flatbuffers.Builder, featurePayloadSha256: Any):
    builder.PrependStructSlot(10, flatbuffers.number_types.UOffsetTFlags.py_type(featurePayloadSha256), 0)

def AddFeaturePayloadSha256(builder: flatbuffers.Builder, featurePayloadSha256: Any):
    FeatureSnapshotMetadataAddFeaturePayloadSha256(builder, featurePayloadSha256)

def FeatureSnapshotMetadataEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return FeatureSnapshotMetadataEnd(builder)
