from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from aegis.mx.contracts.v1.CurrencyUnit import CurrencyUnit
from aegis.mx.contracts.v1.ExchangeEventTimeNs import ExchangeEventTimeNs
from aegis.mx.contracts.v1.GlobalEventId import GlobalEventId
from aegis.mx.contracts.v1.InstrumentId import InstrumentId
from aegis.mx.contracts.v1.IntentId import IntentId
from aegis.mx.contracts.v1.NicReceiveTimeNs import NicReceiveTimeNs
from aegis.mx.contracts.v1.OrderId import OrderId
from aegis.mx.contracts.v1.PriceUnit import PriceUnit
from aegis.mx.contracts.v1.ProcessMonotonicTimeNs import ProcessMonotonicTimeNs
from aegis.mx.contracts.v1.QuantityUnit import QuantityUnit
from aegis.mx.contracts.v1.SchemaVersion import SchemaVersion
from aegis.mx.contracts.v1.SessionId import SessionId
from aegis.mx.contracts.v1.VenueId import VenueId

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class FillEvent:
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> FillEvent: ...
  @classmethod
  def GetRootAsFillEvent(cls, buf: bytes, offset: int) -> FillEvent: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def SchemaVersion(self) -> SchemaVersion | None: ...
  def GlobalEventId(self) -> GlobalEventId | None: ...
  def OrderId(self) -> OrderId | None: ...
  def IntentId(self) -> IntentId | None: ...
  def SessionId(self) -> SessionId | None: ...
  def VenueId(self) -> VenueId | None: ...
  def InstrumentId(self) -> InstrumentId | None: ...
  def VenueTradeId(self) -> int: ...
  def PriceUnit(self) -> typing.Literal[PriceUnit.UNKNOWN, PriceUnit.TICKS]: ...
  def FillPriceTicks(self) -> int: ...
  def QuantityUnit(self) -> typing.Literal[QuantityUnit.UNKNOWN, QuantityUnit.INSTRUMENT_UNITS]: ...
  def FillQuantityUnits(self) -> int: ...
  def CurrencyUnit(self) -> typing.Literal[CurrencyUnit.UNKNOWN, CurrencyUnit.CURRENCY_NANOS]: ...
  def FeeCurrencyNanos(self) -> int: ...
  def ExchangeEventTime(self) -> ExchangeEventTimeNs | None: ...
  def NicReceiveTime(self) -> NicReceiveTimeNs | None: ...
  def ProcessMonotonicTime(self) -> ProcessMonotonicTimeNs | None: ...
def FillEventStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def FillEventAddSchemaVersion(builder: flatbuffers.Builder, schemaVersion: uoffset) -> None: ...
def FillEventAddGlobalEventId(builder: flatbuffers.Builder, globalEventId: uoffset) -> None: ...
def FillEventAddOrderId(builder: flatbuffers.Builder, orderId: uoffset) -> None: ...
def FillEventAddIntentId(builder: flatbuffers.Builder, intentId: uoffset) -> None: ...
def FillEventAddSessionId(builder: flatbuffers.Builder, sessionId: uoffset) -> None: ...
def FillEventAddVenueId(builder: flatbuffers.Builder, venueId: uoffset) -> None: ...
def FillEventAddInstrumentId(builder: flatbuffers.Builder, instrumentId: uoffset) -> None: ...
def FillEventAddVenueTradeId(builder: flatbuffers.Builder, venueTradeId: int) -> None: ...
def FillEventAddPriceUnit(builder: flatbuffers.Builder, priceUnit: typing.Literal[PriceUnit.UNKNOWN, PriceUnit.TICKS]) -> None: ...
def FillEventAddFillPriceTicks(builder: flatbuffers.Builder, fillPriceTicks: int) -> None: ...
def FillEventAddQuantityUnit(builder: flatbuffers.Builder, quantityUnit: typing.Literal[QuantityUnit.UNKNOWN, QuantityUnit.INSTRUMENT_UNITS]) -> None: ...
def FillEventAddFillQuantityUnits(builder: flatbuffers.Builder, fillQuantityUnits: int) -> None: ...
def FillEventAddCurrencyUnit(builder: flatbuffers.Builder, currencyUnit: typing.Literal[CurrencyUnit.UNKNOWN, CurrencyUnit.CURRENCY_NANOS]) -> None: ...
def FillEventAddFeeCurrencyNanos(builder: flatbuffers.Builder, feeCurrencyNanos: int) -> None: ...
def FillEventAddExchangeEventTime(builder: flatbuffers.Builder, exchangeEventTime: uoffset) -> None: ...
def FillEventAddNicReceiveTime(builder: flatbuffers.Builder, nicReceiveTime: uoffset) -> None: ...
def FillEventAddProcessMonotonicTime(builder: flatbuffers.Builder, processMonotonicTime: uoffset) -> None: ...
def FillEventEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

