# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from aegis.mx.contracts.v1.ExchangeEventTimeNs import ExchangeEventTimeNs
from aegis.mx.contracts.v1.GlobalEventId import GlobalEventId
from aegis.mx.contracts.v1.InstrumentId import InstrumentId
from aegis.mx.contracts.v1.IntentId import IntentId
from aegis.mx.contracts.v1.NicReceiveTimeNs import NicReceiveTimeNs
from aegis.mx.contracts.v1.OrderId import OrderId
from aegis.mx.contracts.v1.ProcessMonotonicTimeNs import ProcessMonotonicTimeNs
from aegis.mx.contracts.v1.SchemaVersion import SchemaVersion
from aegis.mx.contracts.v1.SessionId import SessionId
from aegis.mx.contracts.v1.VenueId import VenueId
from typing import Optional
np = import_numpy()

class FillEvent(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FillEvent()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFillEvent(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # FillEvent
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FillEvent
    def SchemaVersion(self) -> Optional[SchemaVersion]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            obj = SchemaVersion()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # FillEvent
    def GlobalEventId(self) -> Optional[GlobalEventId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            obj = GlobalEventId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # FillEvent
    def OrderId(self) -> Optional[OrderId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = o + self._tab.Pos
            obj = OrderId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # FillEvent
    def IntentId(self) -> Optional[IntentId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = o + self._tab.Pos
            obj = IntentId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # FillEvent
    def SessionId(self) -> Optional[SessionId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = o + self._tab.Pos
            obj = SessionId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # FillEvent
    def VenueId(self) -> Optional[VenueId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = o + self._tab.Pos
            obj = VenueId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # FillEvent
    def InstrumentId(self) -> Optional[InstrumentId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            x = o + self._tab.Pos
            obj = InstrumentId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # FillEvent
    def VenueTradeId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # FillEvent
    def PriceUnit(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # FillEvent
    def FillPriceTicks(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # FillEvent
    def QuantityUnit(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # FillEvent
    def FillQuantityUnits(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # FillEvent
    def CurrencyUnit(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # FillEvent
    def FeeCurrencyNanos(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # FillEvent
    def ExchangeEventTime(self) -> Optional[ExchangeEventTimeNs]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            x = o + self._tab.Pos
            obj = ExchangeEventTimeNs()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # FillEvent
    def NicReceiveTime(self) -> Optional[NicReceiveTimeNs]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            x = o + self._tab.Pos
            obj = NicReceiveTimeNs()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # FillEvent
    def ProcessMonotonicTime(self) -> Optional[ProcessMonotonicTimeNs]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        if o != 0:
            x = o + self._tab.Pos
            obj = ProcessMonotonicTimeNs()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def FillEventStart(builder: flatbuffers.Builder):
    builder.StartObject(17)

def Start(builder: flatbuffers.Builder):
    FillEventStart(builder)

def FillEventAddSchemaVersion(builder: flatbuffers.Builder, schemaVersion: Any):
    builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(schemaVersion), 0)

def AddSchemaVersion(builder: flatbuffers.Builder, schemaVersion: Any):
    FillEventAddSchemaVersion(builder, schemaVersion)

def FillEventAddGlobalEventId(builder: flatbuffers.Builder, globalEventId: Any):
    builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(globalEventId), 0)

def AddGlobalEventId(builder: flatbuffers.Builder, globalEventId: Any):
    FillEventAddGlobalEventId(builder, globalEventId)

def FillEventAddOrderId(builder: flatbuffers.Builder, orderId: Any):
    builder.PrependStructSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(orderId), 0)

def AddOrderId(builder: flatbuffers.Builder, orderId: Any):
    FillEventAddOrderId(builder, orderId)

def FillEventAddIntentId(builder: flatbuffers.Builder, intentId: Any):
    builder.PrependStructSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(intentId), 0)

def AddIntentId(builder: flatbuffers.Builder, intentId: Any):
    FillEventAddIntentId(builder, intentId)

def FillEventAddSessionId(builder: flatbuffers.Builder, sessionId: Any):
    builder.PrependStructSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(sessionId), 0)

def AddSessionId(builder: flatbuffers.Builder, sessionId: Any):
    FillEventAddSessionId(builder, sessionId)

def FillEventAddVenueId(builder: flatbuffers.Builder, venueId: Any):
    builder.PrependStructSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(venueId), 0)

def AddVenueId(builder: flatbuffers.Builder, venueId: Any):
    FillEventAddVenueId(builder, venueId)

def FillEventAddInstrumentId(builder: flatbuffers.Builder, instrumentId: Any):
    builder.PrependStructSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(instrumentId), 0)

def AddInstrumentId(builder: flatbuffers.Builder, instrumentId: Any):
    FillEventAddInstrumentId(builder, instrumentId)

def FillEventAddVenueTradeId(builder: flatbuffers.Builder, venueTradeId: int):
    builder.PrependUint64Slot(7, venueTradeId, 0)

def AddVenueTradeId(builder: flatbuffers.Builder, venueTradeId: int):
    FillEventAddVenueTradeId(builder, venueTradeId)

def FillEventAddPriceUnit(builder: flatbuffers.Builder, priceUnit: int):
    builder.PrependUint8Slot(8, priceUnit, 0)

def AddPriceUnit(builder: flatbuffers.Builder, priceUnit: int):
    FillEventAddPriceUnit(builder, priceUnit)

def FillEventAddFillPriceTicks(builder: flatbuffers.Builder, fillPriceTicks: int):
    builder.PrependInt64Slot(9, fillPriceTicks, 0)

def AddFillPriceTicks(builder: flatbuffers.Builder, fillPriceTicks: int):
    FillEventAddFillPriceTicks(builder, fillPriceTicks)

def FillEventAddQuantityUnit(builder: flatbuffers.Builder, quantityUnit: int):
    builder.PrependUint8Slot(10, quantityUnit, 0)

def AddQuantityUnit(builder: flatbuffers.Builder, quantityUnit: int):
    FillEventAddQuantityUnit(builder, quantityUnit)

def FillEventAddFillQuantityUnits(builder: flatbuffers.Builder, fillQuantityUnits: int):
    builder.PrependUint64Slot(11, fillQuantityUnits, 0)

def AddFillQuantityUnits(builder: flatbuffers.Builder, fillQuantityUnits: int):
    FillEventAddFillQuantityUnits(builder, fillQuantityUnits)

def FillEventAddCurrencyUnit(builder: flatbuffers.Builder, currencyUnit: int):
    builder.PrependUint8Slot(12, currencyUnit, 0)

def AddCurrencyUnit(builder: flatbuffers.Builder, currencyUnit: int):
    FillEventAddCurrencyUnit(builder, currencyUnit)

def FillEventAddFeeCurrencyNanos(builder: flatbuffers.Builder, feeCurrencyNanos: int):
    builder.PrependInt64Slot(13, feeCurrencyNanos, 0)

def AddFeeCurrencyNanos(builder: flatbuffers.Builder, feeCurrencyNanos: int):
    FillEventAddFeeCurrencyNanos(builder, feeCurrencyNanos)

def FillEventAddExchangeEventTime(builder: flatbuffers.Builder, exchangeEventTime: Any):
    builder.PrependStructSlot(14, flatbuffers.number_types.UOffsetTFlags.py_type(exchangeEventTime), 0)

def AddExchangeEventTime(builder: flatbuffers.Builder, exchangeEventTime: Any):
    FillEventAddExchangeEventTime(builder, exchangeEventTime)

def FillEventAddNicReceiveTime(builder: flatbuffers.Builder, nicReceiveTime: Any):
    builder.PrependStructSlot(15, flatbuffers.number_types.UOffsetTFlags.py_type(nicReceiveTime), 0)

def AddNicReceiveTime(builder: flatbuffers.Builder, nicReceiveTime: Any):
    FillEventAddNicReceiveTime(builder, nicReceiveTime)

def FillEventAddProcessMonotonicTime(builder: flatbuffers.Builder, processMonotonicTime: Any):
    builder.PrependStructSlot(16, flatbuffers.number_types.UOffsetTFlags.py_type(processMonotonicTime), 0)

def AddProcessMonotonicTime(builder: flatbuffers.Builder, processMonotonicTime: Any):
    FillEventAddProcessMonotonicTime(builder, processMonotonicTime)

def FillEventEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return FillEventEnd(builder)
