# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

class ForecastHorizonUnit(object):
    UNKNOWN = 0
    ELAPSED_NANOSECONDS = 1
    TRADING_MINUTES = 2
    TRADING_SESSIONS = 3
