# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

class ForecastUnit(object):
    UNKNOWN = 0
    RETURN_TICKS = 1
    FAIR_VALUE_TICKS = 2
    PROBABILITY_PPM = 3
    QUANTITY_UNITS = 4
    RETURN_PPM = 5
    VOLATILITY_PPM = 6
    VOLUME_UNITS = 7
    SPREAD_TICKS = 8
    FACTOR_PPM = 9
