# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

class ForecastTarget(object):
    UNKNOWN = 0
    RETURN = 1
    REALIZED_VOLATILITY = 2
    VOLUME = 3
    SPREAD = 4
    MARKET_FACTOR = 5
    SECTOR_FACTOR = 6
