# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from aegis.mx.contracts.v1.ConfigurationVersion import ConfigurationVersion
from typing import Optional
np = import_numpy()

class HorizonSpec(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = HorizonSpec()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsHorizonSpec(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # HorizonSpec
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # HorizonSpec
    def Unit(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # HorizonSpec
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # HorizonSpec
    def HaltPolicy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # HorizonSpec
    def SessionEndpoint(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # HorizonSpec
    def CalendarVersion(self) -> Optional[ConfigurationVersion]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = o + self._tab.Pos
            obj = ConfigurationVersion()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def HorizonSpecStart(builder: flatbuffers.Builder):
    builder.StartObject(5)

def Start(builder: flatbuffers.Builder):
    HorizonSpecStart(builder)

def HorizonSpecAddUnit(builder: flatbuffers.Builder, unit: int):
    builder.PrependUint8Slot(0, unit, 0)

def AddUnit(builder: flatbuffers.Builder, unit: int):
    HorizonSpecAddUnit(builder, unit)

def HorizonSpecAddValue(builder: flatbuffers.Builder, value: int):
    builder.PrependUint64Slot(1, value, 0)

def AddValue(builder: flatbuffers.Builder, value: int):
    HorizonSpecAddValue(builder, value)

def HorizonSpecAddHaltPolicy(builder: flatbuffers.Builder, haltPolicy: int):
    builder.PrependUint8Slot(2, haltPolicy, 0)

def AddHaltPolicy(builder: flatbuffers.Builder, haltPolicy: int):
    HorizonSpecAddHaltPolicy(builder, haltPolicy)

def HorizonSpecAddSessionEndpoint(builder: flatbuffers.Builder, sessionEndpoint: int):
    builder.PrependUint8Slot(3, sessionEndpoint, 0)

def AddSessionEndpoint(builder: flatbuffers.Builder, sessionEndpoint: int):
    HorizonSpecAddSessionEndpoint(builder, sessionEndpoint)

def HorizonSpecAddCalendarVersion(builder: flatbuffers.Builder, calendarVersion: Any):
    builder.PrependStructSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(calendarVersion), 0)

def AddCalendarVersion(builder: flatbuffers.Builder, calendarVersion: Any):
    HorizonSpecAddCalendarVersion(builder, calendarVersion)

def HorizonSpecEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return HorizonSpecEnd(builder)
