# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

class HorizonHaltPolicy(object):
    UNKNOWN = 0
    NOT_APPLICABLE = 1
    REJECT = 2
    PAUSE = 3
    COUNT_SCHEDULED = 4
