from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from aegis.mx.contracts.v1.ConfigurationVersion import ConfigurationVersion
from aegis.mx.contracts.v1.ForecastHorizonUnit import ForecastHorizonUnit
from aegis.mx.contracts.v1.HorizonHaltPolicy import HorizonHaltPolicy
from aegis.mx.contracts.v1.HorizonSessionEndpoint import HorizonSessionEndpoint

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class HorizonSpec:
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> HorizonSpec: ...
  @classmethod
  def GetRootAsHorizonSpec(cls, buf: bytes, offset: int) -> HorizonSpec: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Unit(self) -> typing.Literal[ForecastHorizonUnit.UNKNOWN, ForecastHorizonUnit.ELAPSED_NANOSECONDS, ForecastHorizonUnit.TRADING_MINUTES, ForecastHorizonUnit.TRADING_SESSIONS]: ...
  def Value(self) -> int: ...
  def HaltPolicy(self) -> typing.Literal[HorizonHaltPolicy.UNKNOWN, HorizonHaltPolicy.NOT_APPLICABLE, HorizonHaltPolicy.REJECT, HorizonHaltPolicy.PAUSE, HorizonHaltPolicy.COUNT_SCHEDULED]: ...
  def SessionEndpoint(self) -> typing.Literal[HorizonSessionEndpoint.UNKNOWN, HorizonSessionEndpoint.NOT_APPLICABLE, HorizonSessionEndpoint.REGULAR_SESSION_CLOSE]: ...
  def CalendarVersion(self) -> ConfigurationVersion | None: ...
def HorizonSpecStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def HorizonSpecAddUnit(builder: flatbuffers.Builder, unit: typing.Literal[ForecastHorizonUnit.UNKNOWN, ForecastHorizonUnit.ELAPSED_NANOSECONDS, ForecastHorizonUnit.TRADING_MINUTES, ForecastHorizonUnit.TRADING_SESSIONS]) -> None: ...
def HorizonSpecAddValue(builder: flatbuffers.Builder, value: int) -> None: ...
def HorizonSpecAddHaltPolicy(builder: flatbuffers.Builder, haltPolicy: typing.Literal[HorizonHaltPolicy.UNKNOWN, HorizonHaltPolicy.NOT_APPLICABLE, HorizonHaltPolicy.REJECT, HorizonHaltPolicy.PAUSE, HorizonHaltPolicy.COUNT_SCHEDULED]) -> None: ...
def HorizonSpecAddSessionEndpoint(builder: flatbuffers.Builder, sessionEndpoint: typing.Literal[HorizonSessionEndpoint.UNKNOWN, HorizonSessionEndpoint.NOT_APPLICABLE, HorizonSessionEndpoint.REGULAR_SESSION_CLOSE]) -> None: ...
def HorizonSpecAddCalendarVersion(builder: flatbuffers.Builder, calendarVersion: uoffset) -> None: ...
def HorizonSpecEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

