from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from aegis.mx.contracts.v1.ConfigurationVersion import ConfigurationVersion
from aegis.mx.contracts.v1.ExchangeEventTimeNs import ExchangeEventTimeNs
from aegis.mx.contracts.v1.InstrumentId import InstrumentId
from aegis.mx.contracts.v1.PriceUnit import PriceUnit
from aegis.mx.contracts.v1.QuantityUnit import QuantityUnit
from aegis.mx.contracts.v1.SchemaVersion import SchemaVersion
from aegis.mx.contracts.v1.VenueId import VenueId

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class InstrumentReferenceData:
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> InstrumentReferenceData: ...
  @classmethod
  def GetRootAsInstrumentReferenceData(cls, buf: bytes, offset: int) -> InstrumentReferenceData: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def SchemaVersion(self) -> SchemaVersion | None: ...
  def InstrumentId(self) -> InstrumentId | None: ...
  def VenueId(self) -> VenueId | None: ...
  def Symbol(self) -> str | None: ...
  def CurrencyCode(self) -> str | None: ...
  def PriceUnit(self) -> typing.Literal[PriceUnit.UNKNOWN, PriceUnit.TICKS]: ...
  def QuantityUnit(self) -> typing.Literal[QuantityUnit.UNKNOWN, QuantityUnit.INSTRUMENT_UNITS]: ...
  def TickValueCurrencyNanos(self) -> int: ...
  def LotSizeQuantityUnits(self) -> int: ...
  def MinimumOrderQuantityUnits(self) -> int: ...
  def MaximumOrderQuantityUnits(self) -> int: ...
  def ValidFromExchangeEventTime(self) -> ExchangeEventTimeNs | None: ...
  def ReferenceDataVersion(self) -> ConfigurationVersion | None: ...
  def Active(self) -> bool: ...
def InstrumentReferenceDataStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def InstrumentReferenceDataAddSchemaVersion(builder: flatbuffers.Builder, schemaVersion: uoffset) -> None: ...
def InstrumentReferenceDataAddInstrumentId(builder: flatbuffers.Builder, instrumentId: uoffset) -> None: ...
def InstrumentReferenceDataAddVenueId(builder: flatbuffers.Builder, venueId: uoffset) -> None: ...
def InstrumentReferenceDataAddSymbol(builder: flatbuffers.Builder, symbol: uoffset) -> None: ...
def InstrumentReferenceDataAddCurrencyCode(builder: flatbuffers.Builder, currencyCode: uoffset) -> None: ...
def InstrumentReferenceDataAddPriceUnit(builder: flatbuffers.Builder, priceUnit: typing.Literal[PriceUnit.UNKNOWN, PriceUnit.TICKS]) -> None: ...
def InstrumentReferenceDataAddQuantityUnit(builder: flatbuffers.Builder, quantityUnit: typing.Literal[QuantityUnit.UNKNOWN, QuantityUnit.INSTRUMENT_UNITS]) -> None: ...
def InstrumentReferenceDataAddTickValueCurrencyNanos(builder: flatbuffers.Builder, tickValueCurrencyNanos: int) -> None: ...
def InstrumentReferenceDataAddLotSizeQuantityUnits(builder: flatbuffers.Builder, lotSizeQuantityUnits: int) -> None: ...
def InstrumentReferenceDataAddMinimumOrderQuantityUnits(builder: flatbuffers.Builder, minimumOrderQuantityUnits: int) -> None: ...
def InstrumentReferenceDataAddMaximumOrderQuantityUnits(builder: flatbuffers.Builder, maximumOrderQuantityUnits: int) -> None: ...
def InstrumentReferenceDataAddValidFromExchangeEventTime(builder: flatbuffers.Builder, validFromExchangeEventTime: uoffset) -> None: ...
def InstrumentReferenceDataAddReferenceDataVersion(builder: flatbuffers.Builder, referenceDataVersion: uoffset) -> None: ...
def InstrumentReferenceDataAddActive(builder: flatbuffers.Builder, active: bool) -> None: ...
def InstrumentReferenceDataEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

