# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from aegis.mx.contracts.v1.ConfigurationVersion import ConfigurationVersion
from aegis.mx.contracts.v1.ExchangeEventTimeNs import ExchangeEventTimeNs
from aegis.mx.contracts.v1.InstrumentId import InstrumentId
from aegis.mx.contracts.v1.SchemaVersion import SchemaVersion
from aegis.mx.contracts.v1.VenueId import VenueId
from typing import Optional
np = import_numpy()

class InstrumentReferenceData(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = InstrumentReferenceData()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsInstrumentReferenceData(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # InstrumentReferenceData
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # InstrumentReferenceData
    def SchemaVersion(self) -> Optional[SchemaVersion]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            obj = SchemaVersion()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # InstrumentReferenceData
    def InstrumentId(self) -> Optional[InstrumentId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            obj = InstrumentId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # InstrumentReferenceData
    def VenueId(self) -> Optional[VenueId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = o + self._tab.Pos
            obj = VenueId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # InstrumentReferenceData
    def Symbol(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # InstrumentReferenceData
    def CurrencyCode(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # InstrumentReferenceData
    def PriceUnit(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # InstrumentReferenceData
    def QuantityUnit(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # InstrumentReferenceData
    def TickValueCurrencyNanos(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # InstrumentReferenceData
    def LotSizeQuantityUnits(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # InstrumentReferenceData
    def MinimumOrderQuantityUnits(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # InstrumentReferenceData
    def MaximumOrderQuantityUnits(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # InstrumentReferenceData
    def ValidFromExchangeEventTime(self) -> Optional[ExchangeEventTimeNs]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            x = o + self._tab.Pos
            obj = ExchangeEventTimeNs()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # InstrumentReferenceData
    def ReferenceDataVersion(self) -> Optional[ConfigurationVersion]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            x = o + self._tab.Pos
            obj = ConfigurationVersion()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # InstrumentReferenceData
    def Active(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def InstrumentReferenceDataStart(builder: flatbuffers.Builder):
    builder.StartObject(14)

def Start(builder: flatbuffers.Builder):
    InstrumentReferenceDataStart(builder)

def InstrumentReferenceDataAddSchemaVersion(builder: flatbuffers.Builder, schemaVersion: Any):
    builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(schemaVersion), 0)

def AddSchemaVersion(builder: flatbuffers.Builder, schemaVersion: Any):
    InstrumentReferenceDataAddSchemaVersion(builder, schemaVersion)

def InstrumentReferenceDataAddInstrumentId(builder: flatbuffers.Builder, instrumentId: Any):
    builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(instrumentId), 0)

def AddInstrumentId(builder: flatbuffers.Builder, instrumentId: Any):
    InstrumentReferenceDataAddInstrumentId(builder, instrumentId)

def InstrumentReferenceDataAddVenueId(builder: flatbuffers.Builder, venueId: Any):
    builder.PrependStructSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(venueId), 0)

def AddVenueId(builder: flatbuffers.Builder, venueId: Any):
    InstrumentReferenceDataAddVenueId(builder, venueId)

def InstrumentReferenceDataAddSymbol(builder: flatbuffers.Builder, symbol: int):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(symbol), 0)

def AddSymbol(builder: flatbuffers.Builder, symbol: int):
    InstrumentReferenceDataAddSymbol(builder, symbol)

def InstrumentReferenceDataAddCurrencyCode(builder: flatbuffers.Builder, currencyCode: int):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(currencyCode), 0)

def AddCurrencyCode(builder: flatbuffers.Builder, currencyCode: int):
    InstrumentReferenceDataAddCurrencyCode(builder, currencyCode)

def InstrumentReferenceDataAddPriceUnit(builder: flatbuffers.Builder, priceUnit: int):
    builder.PrependUint8Slot(5, priceUnit, 0)

def AddPriceUnit(builder: flatbuffers.Builder, priceUnit: int):
    InstrumentReferenceDataAddPriceUnit(builder, priceUnit)

def InstrumentReferenceDataAddQuantityUnit(builder: flatbuffers.Builder, quantityUnit: int):
    builder.PrependUint8Slot(6, quantityUnit, 0)

def AddQuantityUnit(builder: flatbuffers.Builder, quantityUnit: int):
    InstrumentReferenceDataAddQuantityUnit(builder, quantityUnit)

def InstrumentReferenceDataAddTickValueCurrencyNanos(builder: flatbuffers.Builder, tickValueCurrencyNanos: int):
    builder.PrependInt64Slot(7, tickValueCurrencyNanos, 0)

def AddTickValueCurrencyNanos(builder: flatbuffers.Builder, tickValueCurrencyNanos: int):
    InstrumentReferenceDataAddTickValueCurrencyNanos(builder, tickValueCurrencyNanos)

def InstrumentReferenceDataAddLotSizeQuantityUnits(builder: flatbuffers.Builder, lotSizeQuantityUnits: int):
    builder.PrependUint64Slot(8, lotSizeQuantityUnits, 0)

def AddLotSizeQuantityUnits(builder: flatbuffers.Builder, lotSizeQuantityUnits: int):
    InstrumentReferenceDataAddLotSizeQuantityUnits(builder, lotSizeQuantityUnits)

def InstrumentReferenceDataAddMinimumOrderQuantityUnits(builder: flatbuffers.Builder, minimumOrderQuantityUnits: int):
    builder.PrependUint64Slot(9, minimumOrderQuantityUnits, 0)

def AddMinimumOrderQuantityUnits(builder: flatbuffers.Builder, minimumOrderQuantityUnits: int):
    InstrumentReferenceDataAddMinimumOrderQuantityUnits(builder, minimumOrderQuantityUnits)

def InstrumentReferenceDataAddMaximumOrderQuantityUnits(builder: flatbuffers.Builder, maximumOrderQuantityUnits: int):
    builder.PrependUint64Slot(10, maximumOrderQuantityUnits, 0)

def AddMaximumOrderQuantityUnits(builder: flatbuffers.Builder, maximumOrderQuantityUnits: int):
    InstrumentReferenceDataAddMaximumOrderQuantityUnits(builder, maximumOrderQuantityUnits)

def InstrumentReferenceDataAddValidFromExchangeEventTime(builder: flatbuffers.Builder, validFromExchangeEventTime: Any):
    builder.PrependStructSlot(11, flatbuffers.number_types.UOffsetTFlags.py_type(validFromExchangeEventTime), 0)

def AddValidFromExchangeEventTime(builder: flatbuffers.Builder, validFromExchangeEventTime: Any):
    InstrumentReferenceDataAddValidFromExchangeEventTime(builder, validFromExchangeEventTime)

def InstrumentReferenceDataAddReferenceDataVersion(builder: flatbuffers.Builder, referenceDataVersion: Any):
    builder.PrependStructSlot(12, flatbuffers.number_types.UOffsetTFlags.py_type(referenceDataVersion), 0)

def AddReferenceDataVersion(builder: flatbuffers.Builder, referenceDataVersion: Any):
    InstrumentReferenceDataAddReferenceDataVersion(builder, referenceDataVersion)

def InstrumentReferenceDataAddActive(builder: flatbuffers.Builder, active: bool):
    builder.PrependBoolSlot(13, active, 0)

def AddActive(builder: flatbuffers.Builder, active: bool):
    InstrumentReferenceDataAddActive(builder, active)

def InstrumentReferenceDataEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return InstrumentReferenceDataEnd(builder)
