# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

class IntelligenceDocumentType(object):
    UNKNOWN = 0
    NEWS_ARTICLE = 1
    FILING = 2
    PRESS_RELEASE = 3
    REGULATORY_NOTICE = 4
    MACRO_RELEASE = 5
    CORRECTION = 6
