from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class IntelligenceFact:
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> IntelligenceFact: ...
  @classmethod
  def GetRootAsIntelligenceFact(cls, buf: bytes, offset: int) -> IntelligenceFact: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Name(self) -> str | None: ...
  def Value(self) -> str | None: ...
  def Unit(self) -> str | None: ...
  def UncertaintyPpm(self) -> int: ...
  def EvidenceExcerptIds(self, i: int) -> typing.List[int]: ...
  def EvidenceExcerptIdsAsNumpy(self) -> np.ndarray: ...
  def EvidenceExcerptIdsLength(self) -> int: ...
  def EvidenceExcerptIdsIsNone(self) -> bool: ...
def IntelligenceFactStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def IntelligenceFactAddName(builder: flatbuffers.Builder, name: uoffset) -> None: ...
def IntelligenceFactAddValue(builder: flatbuffers.Builder, value: uoffset) -> None: ...
def IntelligenceFactAddUnit(builder: flatbuffers.Builder, unit: uoffset) -> None: ...
def IntelligenceFactAddUncertaintyPpm(builder: flatbuffers.Builder, uncertaintyPpm: int) -> None: ...
def IntelligenceFactAddEvidenceExcerptIds(builder: flatbuffers.Builder, evidenceExcerptIds: uoffset) -> None: ...
def IntelligenceFactStartEvidenceExcerptIdsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartEvidenceExcerptIdsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def IntelligenceFactEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

