# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

class IntelligenceTrustCode(object):
    UNKNOWN = 0
    UNTRUSTED = 1
    SANITIZED = 2
    VERIFIED_SOURCE = 3
