# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

class IntelligenceAdjudicationCode(object):
    UNKNOWN = 0
    PRELIMINARY = 1
    CONFIRMED = 2
    REFINED = 3
    DISPUTED = 4
    CORRECTED = 5
