# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from aegis.mx.contracts.v1.InstrumentId import InstrumentId
from aegis.mx.contracts.v1.Sha256Digest import Sha256Digest
from typing import Optional
np = import_numpy()

class IntelligenceResolvedEntity(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = IntelligenceResolvedEntity()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsIntelligenceResolvedEntity(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # IntelligenceResolvedEntity
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # IntelligenceResolvedEntity
    def EntitySha256(self) -> Optional[Sha256Digest]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            obj = Sha256Digest()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # IntelligenceResolvedEntity
    def CanonicalName(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # IntelligenceResolvedEntity
    def Relationship(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # IntelligenceResolvedEntity
    def InstrumentId(self) -> Optional[InstrumentId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = o + self._tab.Pos
            obj = InstrumentId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # IntelligenceResolvedEntity
    def ConfidencePpm(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def IntelligenceResolvedEntityStart(builder: flatbuffers.Builder):
    builder.StartObject(5)

def Start(builder: flatbuffers.Builder):
    IntelligenceResolvedEntityStart(builder)

def IntelligenceResolvedEntityAddEntitySha256(builder: flatbuffers.Builder, entitySha256: Any):
    builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(entitySha256), 0)

def AddEntitySha256(builder: flatbuffers.Builder, entitySha256: Any):
    IntelligenceResolvedEntityAddEntitySha256(builder, entitySha256)

def IntelligenceResolvedEntityAddCanonicalName(builder: flatbuffers.Builder, canonicalName: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(canonicalName), 0)

def AddCanonicalName(builder: flatbuffers.Builder, canonicalName: int):
    IntelligenceResolvedEntityAddCanonicalName(builder, canonicalName)

def IntelligenceResolvedEntityAddRelationship(builder: flatbuffers.Builder, relationship: int):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(relationship), 0)

def AddRelationship(builder: flatbuffers.Builder, relationship: int):
    IntelligenceResolvedEntityAddRelationship(builder, relationship)

def IntelligenceResolvedEntityAddInstrumentId(builder: flatbuffers.Builder, instrumentId: Any):
    builder.PrependStructSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(instrumentId), 0)

def AddInstrumentId(builder: flatbuffers.Builder, instrumentId: Any):
    IntelligenceResolvedEntityAddInstrumentId(builder, instrumentId)

def IntelligenceResolvedEntityAddConfidencePpm(builder: flatbuffers.Builder, confidencePpm: int):
    builder.PrependUint32Slot(4, confidencePpm, 0)

def AddConfidencePpm(builder: flatbuffers.Builder, confidencePpm: int):
    IntelligenceResolvedEntityAddConfidencePpm(builder, confidencePpm)

def IntelligenceResolvedEntityEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return IntelligenceResolvedEntityEnd(builder)
