from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from aegis.mx.contracts.v1.Sha256Digest import Sha256Digest

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class IntelligenceEvidenceExcerpt:
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> IntelligenceEvidenceExcerpt: ...
  @classmethod
  def GetRootAsIntelligenceEvidenceExcerpt(cls, buf: bytes, offset: int) -> IntelligenceEvidenceExcerpt: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def ExcerptId(self) -> int: ...
  def SourceStartUtf8Offset(self) -> int: ...
  def SourceEndUtf8Offset(self) -> int: ...
  def ExactText(self) -> str | None: ...
  def ExactTextSha256(self) -> Sha256Digest | None: ...
def IntelligenceEvidenceExcerptStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def IntelligenceEvidenceExcerptAddExcerptId(builder: flatbuffers.Builder, excerptId: int) -> None: ...
def IntelligenceEvidenceExcerptAddSourceStartUtf8Offset(builder: flatbuffers.Builder, sourceStartUtf8Offset: int) -> None: ...
def IntelligenceEvidenceExcerptAddSourceEndUtf8Offset(builder: flatbuffers.Builder, sourceEndUtf8Offset: int) -> None: ...
def IntelligenceEvidenceExcerptAddExactText(builder: flatbuffers.Builder, exactText: uoffset) -> None: ...
def IntelligenceEvidenceExcerptAddExactTextSha256(builder: flatbuffers.Builder, exactTextSha256: uoffset) -> None: ...
def IntelligenceEvidenceExcerptEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

