# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from aegis.mx.contracts.v1.Sha256Digest import Sha256Digest
from typing import Optional
np = import_numpy()

class IntelligenceEvidenceExcerpt(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = IntelligenceEvidenceExcerpt()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsIntelligenceEvidenceExcerpt(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # IntelligenceEvidenceExcerpt
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # IntelligenceEvidenceExcerpt
    def ExcerptId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # IntelligenceEvidenceExcerpt
    def SourceStartUtf8Offset(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # IntelligenceEvidenceExcerpt
    def SourceEndUtf8Offset(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # IntelligenceEvidenceExcerpt
    def ExactText(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # IntelligenceEvidenceExcerpt
    def ExactTextSha256(self) -> Optional[Sha256Digest]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = o + self._tab.Pos
            obj = Sha256Digest()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def IntelligenceEvidenceExcerptStart(builder: flatbuffers.Builder):
    builder.StartObject(5)

def Start(builder: flatbuffers.Builder):
    IntelligenceEvidenceExcerptStart(builder)

def IntelligenceEvidenceExcerptAddExcerptId(builder: flatbuffers.Builder, excerptId: int):
    builder.PrependUint32Slot(0, excerptId, 0)

def AddExcerptId(builder: flatbuffers.Builder, excerptId: int):
    IntelligenceEvidenceExcerptAddExcerptId(builder, excerptId)

def IntelligenceEvidenceExcerptAddSourceStartUtf8Offset(builder: flatbuffers.Builder, sourceStartUtf8Offset: int):
    builder.PrependUint32Slot(1, sourceStartUtf8Offset, 0)

def AddSourceStartUtf8Offset(builder: flatbuffers.Builder, sourceStartUtf8Offset: int):
    IntelligenceEvidenceExcerptAddSourceStartUtf8Offset(builder, sourceStartUtf8Offset)

def IntelligenceEvidenceExcerptAddSourceEndUtf8Offset(builder: flatbuffers.Builder, sourceEndUtf8Offset: int):
    builder.PrependUint32Slot(2, sourceEndUtf8Offset, 0)

def AddSourceEndUtf8Offset(builder: flatbuffers.Builder, sourceEndUtf8Offset: int):
    IntelligenceEvidenceExcerptAddSourceEndUtf8Offset(builder, sourceEndUtf8Offset)

def IntelligenceEvidenceExcerptAddExactText(builder: flatbuffers.Builder, exactText: int):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(exactText), 0)

def AddExactText(builder: flatbuffers.Builder, exactText: int):
    IntelligenceEvidenceExcerptAddExactText(builder, exactText)

def IntelligenceEvidenceExcerptAddExactTextSha256(builder: flatbuffers.Builder, exactTextSha256: Any):
    builder.PrependStructSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(exactTextSha256), 0)

def AddExactTextSha256(builder: flatbuffers.Builder, exactTextSha256: Any):
    IntelligenceEvidenceExcerptAddExactTextSha256(builder, exactTextSha256)

def IntelligenceEvidenceExcerptEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return IntelligenceEvidenceExcerptEnd(builder)
