from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from aegis.mx.contracts.v1.InstrumentId import InstrumentId
from aegis.mx.contracts.v1.Sha256Digest import Sha256Digest

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class IntelligenceResolvedEntity:
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> IntelligenceResolvedEntity: ...
  @classmethod
  def GetRootAsIntelligenceResolvedEntity(cls, buf: bytes, offset: int) -> IntelligenceResolvedEntity: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def EntitySha256(self) -> Sha256Digest | None: ...
  def CanonicalName(self) -> str | None: ...
  def Relationship(self) -> str | None: ...
  def InstrumentId(self) -> InstrumentId | None: ...
  def ConfidencePpm(self) -> int: ...
def IntelligenceResolvedEntityStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def IntelligenceResolvedEntityAddEntitySha256(builder: flatbuffers.Builder, entitySha256: uoffset) -> None: ...
def IntelligenceResolvedEntityAddCanonicalName(builder: flatbuffers.Builder, canonicalName: uoffset) -> None: ...
def IntelligenceResolvedEntityAddRelationship(builder: flatbuffers.Builder, relationship: uoffset) -> None: ...
def IntelligenceResolvedEntityAddInstrumentId(builder: flatbuffers.Builder, instrumentId: uoffset) -> None: ...
def IntelligenceResolvedEntityAddConfidencePpm(builder: flatbuffers.Builder, confidencePpm: int) -> None: ...
def IntelligenceResolvedEntityEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

