# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

class IntelligenceEventType(object):
    UNKNOWN = 0
    EARNINGS_RELEASE = 1
    GUIDANCE_UPDATE = 2
    MERGER_ACQUISITION = 3
    PRODUCT_RECALL = 4
    REGULATORY_ACTION = 5
    EXECUTIVE_CHANGE = 6
    FINANCING = 7
    BANKRUPTCY = 8
    LITIGATION = 9
    CYBERSECURITY_INCIDENT = 10
    ANALYST_ACTION = 11
    SUPPLY_CHAIN_DISRUPTION = 12
    TRADING_HALT = 13
    MACRO_RELEASE = 14
    RUMOR = 15
    CORRECTION = 16
