# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from typing import Optional
np = import_numpy()

class IntelligenceFact(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = IntelligenceFact()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsIntelligenceFact(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # IntelligenceFact
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # IntelligenceFact
    def Name(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # IntelligenceFact
    def Value(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # IntelligenceFact
    def Unit(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # IntelligenceFact
    def UncertaintyPpm(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # IntelligenceFact
    def EvidenceExcerptIds(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # IntelligenceFact
    def EvidenceExcerptIdsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint32Flags, o)
        return 0

    # IntelligenceFact
    def EvidenceExcerptIdsLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # IntelligenceFact
    def EvidenceExcerptIdsIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

def IntelligenceFactStart(builder: flatbuffers.Builder):
    builder.StartObject(5)

def Start(builder: flatbuffers.Builder):
    IntelligenceFactStart(builder)

def IntelligenceFactAddName(builder: flatbuffers.Builder, name: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def AddName(builder: flatbuffers.Builder, name: int):
    IntelligenceFactAddName(builder, name)

def IntelligenceFactAddValue(builder: flatbuffers.Builder, value: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(value), 0)

def AddValue(builder: flatbuffers.Builder, value: int):
    IntelligenceFactAddValue(builder, value)

def IntelligenceFactAddUnit(builder: flatbuffers.Builder, unit: int):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(unit), 0)

def AddUnit(builder: flatbuffers.Builder, unit: int):
    IntelligenceFactAddUnit(builder, unit)

def IntelligenceFactAddUncertaintyPpm(builder: flatbuffers.Builder, uncertaintyPpm: int):
    builder.PrependUint32Slot(3, uncertaintyPpm, 0)

def AddUncertaintyPpm(builder: flatbuffers.Builder, uncertaintyPpm: int):
    IntelligenceFactAddUncertaintyPpm(builder, uncertaintyPpm)

def IntelligenceFactAddEvidenceExcerptIds(builder: flatbuffers.Builder, evidenceExcerptIds: int):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(evidenceExcerptIds), 0)

def AddEvidenceExcerptIds(builder: flatbuffers.Builder, evidenceExcerptIds: int):
    IntelligenceFactAddEvidenceExcerptIds(builder, evidenceExcerptIds)

def IntelligenceFactStartEvidenceExcerptIdsVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartEvidenceExcerptIdsVector(builder, numElems: int) -> int:
    return IntelligenceFactStartEvidenceExcerptIdsVector(builder, numElems)

def IntelligenceFactEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return IntelligenceFactEnd(builder)
