from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from aegis.mx.contracts.v1.AccountId import AccountId
from aegis.mx.contracts.v1.ConfigurationVersion import ConfigurationVersion
from aegis.mx.contracts.v1.GlobalEventId import GlobalEventId
from aegis.mx.contracts.v1.InstrumentId import InstrumentId
from aegis.mx.contracts.v1.KillSwitchReasonCode import KillSwitchReasonCode
from aegis.mx.contracts.v1.KillSwitchScope import KillSwitchScope
from aegis.mx.contracts.v1.KillSwitchStateCode import KillSwitchStateCode
from aegis.mx.contracts.v1.ProcessMonotonicTimeNs import ProcessMonotonicTimeNs
from aegis.mx.contracts.v1.SchemaVersion import SchemaVersion
from aegis.mx.contracts.v1.SessionId import SessionId
from aegis.mx.contracts.v1.Sha256Digest import Sha256Digest
from aegis.mx.contracts.v1.StrategyId import StrategyId
from aegis.mx.contracts.v1.VenueId import VenueId
from aegis.mx.contracts.v1.WallClockUtcTimeNs import WallClockUtcTimeNs

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class KillSwitchEvent:
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> KillSwitchEvent: ...
  @classmethod
  def GetRootAsKillSwitchEvent(cls, buf: bytes, offset: int) -> KillSwitchEvent: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def SchemaVersion(self) -> SchemaVersion | None: ...
  def GlobalEventId(self) -> GlobalEventId | None: ...
  def SessionId(self) -> SessionId | None: ...
  def ConfigurationVersion(self) -> ConfigurationVersion | None: ...
  def State(self) -> typing.Literal[KillSwitchStateCode.UNKNOWN, KillSwitchStateCode.ENGAGED, KillSwitchStateCode.RESET]: ...
  def Scope(self) -> typing.Literal[KillSwitchScope.UNKNOWN, KillSwitchScope.GLOBAL, KillSwitchScope.VENUE, KillSwitchScope.STRATEGY, KillSwitchScope.SYMBOL, KillSwitchScope.ACCOUNT]: ...
  def TargetVenueId(self) -> VenueId | None: ...
  def TargetStrategyId(self) -> StrategyId | None: ...
  def Reason(self) -> typing.Literal[KillSwitchReasonCode.UNKNOWN, KillSwitchReasonCode.OPERATOR, KillSwitchReasonCode.RISK_SERVICE, KillSwitchReasonCode.CLOCK_QUALITY, KillSwitchReasonCode.MARKET_DATA_QUALITY, KillSwitchReasonCode.SPLIT_BRAIN, KillSwitchReasonCode.TRADING_HALT, KillSwitchReasonCode.INTERNAL_FAULT]: ...
  def EffectiveProcessMonotonicTime(self) -> ProcessMonotonicTimeNs | None: ...
  def RecordedWallClockUtcTime(self) -> WallClockUtcTimeNs | None: ...
  def OperatorAuthorizationSha256(self) -> Sha256Digest | None: ...
  def TargetInstrumentId(self) -> InstrumentId | None: ...
  def TargetAccountId(self) -> AccountId | None: ...
  def CommandSequence(self) -> int: ...
  def AuthorityEpoch(self) -> int: ...
def KillSwitchEventStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def KillSwitchEventAddSchemaVersion(builder: flatbuffers.Builder, schemaVersion: uoffset) -> None: ...
def KillSwitchEventAddGlobalEventId(builder: flatbuffers.Builder, globalEventId: uoffset) -> None: ...
def KillSwitchEventAddSessionId(builder: flatbuffers.Builder, sessionId: uoffset) -> None: ...
def KillSwitchEventAddConfigurationVersion(builder: flatbuffers.Builder, configurationVersion: uoffset) -> None: ...
def KillSwitchEventAddState(builder: flatbuffers.Builder, state: typing.Literal[KillSwitchStateCode.UNKNOWN, KillSwitchStateCode.ENGAGED, KillSwitchStateCode.RESET]) -> None: ...
def KillSwitchEventAddScope(builder: flatbuffers.Builder, scope: typing.Literal[KillSwitchScope.UNKNOWN, KillSwitchScope.GLOBAL, KillSwitchScope.VENUE, KillSwitchScope.STRATEGY, KillSwitchScope.SYMBOL, KillSwitchScope.ACCOUNT]) -> None: ...
def KillSwitchEventAddTargetVenueId(builder: flatbuffers.Builder, targetVenueId: uoffset) -> None: ...
def KillSwitchEventAddTargetStrategyId(builder: flatbuffers.Builder, targetStrategyId: uoffset) -> None: ...
def KillSwitchEventAddReason(builder: flatbuffers.Builder, reason: typing.Literal[KillSwitchReasonCode.UNKNOWN, KillSwitchReasonCode.OPERATOR, KillSwitchReasonCode.RISK_SERVICE, KillSwitchReasonCode.CLOCK_QUALITY, KillSwitchReasonCode.MARKET_DATA_QUALITY, KillSwitchReasonCode.SPLIT_BRAIN, KillSwitchReasonCode.TRADING_HALT, KillSwitchReasonCode.INTERNAL_FAULT]) -> None: ...
def KillSwitchEventAddEffectiveProcessMonotonicTime(builder: flatbuffers.Builder, effectiveProcessMonotonicTime: uoffset) -> None: ...
def KillSwitchEventAddRecordedWallClockUtcTime(builder: flatbuffers.Builder, recordedWallClockUtcTime: uoffset) -> None: ...
def KillSwitchEventAddOperatorAuthorizationSha256(builder: flatbuffers.Builder, operatorAuthorizationSha256: uoffset) -> None: ...
def KillSwitchEventAddTargetInstrumentId(builder: flatbuffers.Builder, targetInstrumentId: uoffset) -> None: ...
def KillSwitchEventAddTargetAccountId(builder: flatbuffers.Builder, targetAccountId: uoffset) -> None: ...
def KillSwitchEventAddCommandSequence(builder: flatbuffers.Builder, commandSequence: int) -> None: ...
def KillSwitchEventAddAuthorityEpoch(builder: flatbuffers.Builder, authorityEpoch: int) -> None: ...
def KillSwitchEventEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

