# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

class KillSwitchScope(object):
    UNKNOWN = 0
    GLOBAL = 1
    VENUE = 2
    STRATEGY = 3
    SYMBOL = 4
    ACCOUNT = 5
