# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from aegis.mx.contracts.v1.AccountId import AccountId
from aegis.mx.contracts.v1.ConfigurationVersion import ConfigurationVersion
from aegis.mx.contracts.v1.GlobalEventId import GlobalEventId
from aegis.mx.contracts.v1.InstrumentId import InstrumentId
from aegis.mx.contracts.v1.ProcessMonotonicTimeNs import ProcessMonotonicTimeNs
from aegis.mx.contracts.v1.SchemaVersion import SchemaVersion
from aegis.mx.contracts.v1.SessionId import SessionId
from aegis.mx.contracts.v1.Sha256Digest import Sha256Digest
from aegis.mx.contracts.v1.StrategyId import StrategyId
from aegis.mx.contracts.v1.VenueId import VenueId
from aegis.mx.contracts.v1.WallClockUtcTimeNs import WallClockUtcTimeNs
from typing import Optional
np = import_numpy()

class KillSwitchEvent(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = KillSwitchEvent()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsKillSwitchEvent(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # KillSwitchEvent
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # KillSwitchEvent
    def SchemaVersion(self) -> Optional[SchemaVersion]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            obj = SchemaVersion()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # KillSwitchEvent
    def GlobalEventId(self) -> Optional[GlobalEventId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            obj = GlobalEventId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # KillSwitchEvent
    def SessionId(self) -> Optional[SessionId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = o + self._tab.Pos
            obj = SessionId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # KillSwitchEvent
    def ConfigurationVersion(self) -> Optional[ConfigurationVersion]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = o + self._tab.Pos
            obj = ConfigurationVersion()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # KillSwitchEvent
    def State(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # KillSwitchEvent
    def Scope(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # KillSwitchEvent
    def TargetVenueId(self) -> Optional[VenueId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            x = o + self._tab.Pos
            obj = VenueId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # KillSwitchEvent
    def TargetStrategyId(self) -> Optional[StrategyId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            x = o + self._tab.Pos
            obj = StrategyId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # KillSwitchEvent
    def Reason(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # KillSwitchEvent
    def EffectiveProcessMonotonicTime(self) -> Optional[ProcessMonotonicTimeNs]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            x = o + self._tab.Pos
            obj = ProcessMonotonicTimeNs()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # KillSwitchEvent
    def RecordedWallClockUtcTime(self) -> Optional[WallClockUtcTimeNs]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            x = o + self._tab.Pos
            obj = WallClockUtcTimeNs()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # KillSwitchEvent
    def OperatorAuthorizationSha256(self) -> Optional[Sha256Digest]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            x = o + self._tab.Pos
            obj = Sha256Digest()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # KillSwitchEvent
    def TargetInstrumentId(self) -> Optional[InstrumentId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            x = o + self._tab.Pos
            obj = InstrumentId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # KillSwitchEvent
    def TargetAccountId(self) -> Optional[AccountId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            x = o + self._tab.Pos
            obj = AccountId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # KillSwitchEvent
    def CommandSequence(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # KillSwitchEvent
    def AuthorityEpoch(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def KillSwitchEventStart(builder: flatbuffers.Builder):
    builder.StartObject(16)

def Start(builder: flatbuffers.Builder):
    KillSwitchEventStart(builder)

def KillSwitchEventAddSchemaVersion(builder: flatbuffers.Builder, schemaVersion: Any):
    builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(schemaVersion), 0)

def AddSchemaVersion(builder: flatbuffers.Builder, schemaVersion: Any):
    KillSwitchEventAddSchemaVersion(builder, schemaVersion)

def KillSwitchEventAddGlobalEventId(builder: flatbuffers.Builder, globalEventId: Any):
    builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(globalEventId), 0)

def AddGlobalEventId(builder: flatbuffers.Builder, globalEventId: Any):
    KillSwitchEventAddGlobalEventId(builder, globalEventId)

def KillSwitchEventAddSessionId(builder: flatbuffers.Builder, sessionId: Any):
    builder.PrependStructSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(sessionId), 0)

def AddSessionId(builder: flatbuffers.Builder, sessionId: Any):
    KillSwitchEventAddSessionId(builder, sessionId)

def KillSwitchEventAddConfigurationVersion(builder: flatbuffers.Builder, configurationVersion: Any):
    builder.PrependStructSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(configurationVersion), 0)

def AddConfigurationVersion(builder: flatbuffers.Builder, configurationVersion: Any):
    KillSwitchEventAddConfigurationVersion(builder, configurationVersion)

def KillSwitchEventAddState(builder: flatbuffers.Builder, state: int):
    builder.PrependUint8Slot(4, state, 0)

def AddState(builder: flatbuffers.Builder, state: int):
    KillSwitchEventAddState(builder, state)

def KillSwitchEventAddScope(builder: flatbuffers.Builder, scope: int):
    builder.PrependUint8Slot(5, scope, 0)

def AddScope(builder: flatbuffers.Builder, scope: int):
    KillSwitchEventAddScope(builder, scope)

def KillSwitchEventAddTargetVenueId(builder: flatbuffers.Builder, targetVenueId: Any):
    builder.PrependStructSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(targetVenueId), 0)

def AddTargetVenueId(builder: flatbuffers.Builder, targetVenueId: Any):
    KillSwitchEventAddTargetVenueId(builder, targetVenueId)

def KillSwitchEventAddTargetStrategyId(builder: flatbuffers.Builder, targetStrategyId: Any):
    builder.PrependStructSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(targetStrategyId), 0)

def AddTargetStrategyId(builder: flatbuffers.Builder, targetStrategyId: Any):
    KillSwitchEventAddTargetStrategyId(builder, targetStrategyId)

def KillSwitchEventAddReason(builder: flatbuffers.Builder, reason: int):
    builder.PrependUint16Slot(8, reason, 0)

def AddReason(builder: flatbuffers.Builder, reason: int):
    KillSwitchEventAddReason(builder, reason)

def KillSwitchEventAddEffectiveProcessMonotonicTime(builder: flatbuffers.Builder, effectiveProcessMonotonicTime: Any):
    builder.PrependStructSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(effectiveProcessMonotonicTime), 0)

def AddEffectiveProcessMonotonicTime(builder: flatbuffers.Builder, effectiveProcessMonotonicTime: Any):
    KillSwitchEventAddEffectiveProcessMonotonicTime(builder, effectiveProcessMonotonicTime)

def KillSwitchEventAddRecordedWallClockUtcTime(builder: flatbuffers.Builder, recordedWallClockUtcTime: Any):
    builder.PrependStructSlot(10, flatbuffers.number_types.UOffsetTFlags.py_type(recordedWallClockUtcTime), 0)

def AddRecordedWallClockUtcTime(builder: flatbuffers.Builder, recordedWallClockUtcTime: Any):
    KillSwitchEventAddRecordedWallClockUtcTime(builder, recordedWallClockUtcTime)

def KillSwitchEventAddOperatorAuthorizationSha256(builder: flatbuffers.Builder, operatorAuthorizationSha256: Any):
    builder.PrependStructSlot(11, flatbuffers.number_types.UOffsetTFlags.py_type(operatorAuthorizationSha256), 0)

def AddOperatorAuthorizationSha256(builder: flatbuffers.Builder, operatorAuthorizationSha256: Any):
    KillSwitchEventAddOperatorAuthorizationSha256(builder, operatorAuthorizationSha256)

def KillSwitchEventAddTargetInstrumentId(builder: flatbuffers.Builder, targetInstrumentId: Any):
    builder.PrependStructSlot(12, flatbuffers.number_types.UOffsetTFlags.py_type(targetInstrumentId), 0)

def AddTargetInstrumentId(builder: flatbuffers.Builder, targetInstrumentId: Any):
    KillSwitchEventAddTargetInstrumentId(builder, targetInstrumentId)

def KillSwitchEventAddTargetAccountId(builder: flatbuffers.Builder, targetAccountId: Any):
    builder.PrependStructSlot(13, flatbuffers.number_types.UOffsetTFlags.py_type(targetAccountId), 0)

def AddTargetAccountId(builder: flatbuffers.Builder, targetAccountId: Any):
    KillSwitchEventAddTargetAccountId(builder, targetAccountId)

def KillSwitchEventAddCommandSequence(builder: flatbuffers.Builder, commandSequence: int):
    builder.PrependUint64Slot(14, commandSequence, 0)

def AddCommandSequence(builder: flatbuffers.Builder, commandSequence: int):
    KillSwitchEventAddCommandSequence(builder, commandSequence)

def KillSwitchEventAddAuthorityEpoch(builder: flatbuffers.Builder, authorityEpoch: int):
    builder.PrependUint64Slot(15, authorityEpoch, 0)

def AddAuthorityEpoch(builder: flatbuffers.Builder, authorityEpoch: int):
    KillSwitchEventAddAuthorityEpoch(builder, authorityEpoch)

def KillSwitchEventEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return KillSwitchEventEnd(builder)
