# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

class KillSwitchReasonCode(object):
    UNKNOWN = 0
    OPERATOR = 1
    RISK_SERVICE = 2
    CLOCK_QUALITY = 3
    MARKET_DATA_QUALITY = 4
    SPLIT_BRAIN = 5
    TRADING_HALT = 6
    INTERNAL_FAULT = 7
