from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from aegis.mx.contracts.v1.ChannelId import ChannelId
from aegis.mx.contracts.v1.ClockQualityState import ClockQualityState
from aegis.mx.contracts.v1.DataQualityState import DataQualityState
from aegis.mx.contracts.v1.ExchangeEventTimeNs import ExchangeEventTimeNs
from aegis.mx.contracts.v1.GlobalEventId import GlobalEventId
from aegis.mx.contracts.v1.InstrumentId import InstrumentId
from aegis.mx.contracts.v1.MarketPayload import MarketPayload
from aegis.mx.contracts.v1.NicReceiveTimeNs import NicReceiveTimeNs
from aegis.mx.contracts.v1.ProcessMonotonicTimeNs import ProcessMonotonicTimeNs
from aegis.mx.contracts.v1.SchemaVersion import SchemaVersion
from aegis.mx.contracts.v1.SessionId import SessionId
from aegis.mx.contracts.v1.VenueId import VenueId
from flatbuffers import table

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class MarketEvent:
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> MarketEvent: ...
  @classmethod
  def GetRootAsMarketEvent(cls, buf: bytes, offset: int) -> MarketEvent: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def SchemaVersion(self) -> SchemaVersion | None: ...
  def GlobalEventId(self) -> GlobalEventId | None: ...
  def SessionId(self) -> SessionId | None: ...
  def VenueId(self) -> VenueId | None: ...
  def InstrumentId(self) -> InstrumentId | None: ...
  def ChannelId(self) -> ChannelId | None: ...
  def ChannelSequence(self) -> int: ...
  def ExchangeEventTime(self) -> ExchangeEventTimeNs | None: ...
  def NicReceiveTime(self) -> NicReceiveTimeNs | None: ...
  def ProcessMonotonicTime(self) -> ProcessMonotonicTimeNs | None: ...
  def DataQualityState(self) -> DataQualityState | None: ...
  def ClockQualityState(self) -> ClockQualityState | None: ...
  def MarketPayloadType(self) -> typing.Literal[MarketPayload.NONE, MarketPayload.BookUpdate, MarketPayload.TradeEvent, MarketPayload.QuoteEvent, MarketPayload.AuctionImbalance, MarketPayload.TradingStatus]: ...
  def MarketPayload(self) -> table.Table | None: ...
def MarketEventStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def MarketEventAddSchemaVersion(builder: flatbuffers.Builder, schemaVersion: uoffset) -> None: ...
def MarketEventAddGlobalEventId(builder: flatbuffers.Builder, globalEventId: uoffset) -> None: ...
def MarketEventAddSessionId(builder: flatbuffers.Builder, sessionId: uoffset) -> None: ...
def MarketEventAddVenueId(builder: flatbuffers.Builder, venueId: uoffset) -> None: ...
def MarketEventAddInstrumentId(builder: flatbuffers.Builder, instrumentId: uoffset) -> None: ...
def MarketEventAddChannelId(builder: flatbuffers.Builder, channelId: uoffset) -> None: ...
def MarketEventAddChannelSequence(builder: flatbuffers.Builder, channelSequence: int) -> None: ...
def MarketEventAddExchangeEventTime(builder: flatbuffers.Builder, exchangeEventTime: uoffset) -> None: ...
def MarketEventAddNicReceiveTime(builder: flatbuffers.Builder, nicReceiveTime: uoffset) -> None: ...
def MarketEventAddProcessMonotonicTime(builder: flatbuffers.Builder, processMonotonicTime: uoffset) -> None: ...
def MarketEventAddDataQualityState(builder: flatbuffers.Builder, dataQualityState: uoffset) -> None: ...
def MarketEventAddClockQualityState(builder: flatbuffers.Builder, clockQualityState: uoffset) -> None: ...
def MarketEventAddMarketPayloadType(builder: flatbuffers.Builder, marketPayloadType: typing.Literal[MarketPayload.NONE, MarketPayload.BookUpdate, MarketPayload.TradeEvent, MarketPayload.QuoteEvent, MarketPayload.AuctionImbalance, MarketPayload.TradingStatus]) -> None: ...
def MarketEventAddMarketPayload(builder: flatbuffers.Builder, marketPayload: uoffset) -> None: ...
def MarketEventEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

