# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

class MarketPayload(object):
    NONE = 0
    BookUpdate = 1
    TradeEvent = 2
    QuoteEvent = 3
    AuctionImbalance = 4
    TradingStatus = 5
