# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from aegis.mx.contracts.v1.ConfigurationVersion import ConfigurationVersion
from aegis.mx.contracts.v1.ExchangeEventTimeNs import ExchangeEventTimeNs
from aegis.mx.contracts.v1.FeatureSnapshotId import FeatureSnapshotId
from aegis.mx.contracts.v1.ForecastId import ForecastId
from aegis.mx.contracts.v1.InstrumentId import InstrumentId
from aegis.mx.contracts.v1.ModelId import ModelId
from aegis.mx.contracts.v1.ModelVersion import ModelVersion
from aegis.mx.contracts.v1.ProcessMonotonicTimeNs import ProcessMonotonicTimeNs
from aegis.mx.contracts.v1.SchemaVersion import SchemaVersion
from aegis.mx.contracts.v1.SessionId import SessionId
from typing import Optional
np = import_numpy()

class ModelForecast(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ModelForecast()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsModelForecast(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ModelForecast
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ModelForecast
    def SchemaVersion(self) -> Optional[SchemaVersion]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            obj = SchemaVersion()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ModelForecast
    def ForecastId(self) -> Optional[ForecastId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            obj = ForecastId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ModelForecast
    def SessionId(self) -> Optional[SessionId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = o + self._tab.Pos
            obj = SessionId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ModelForecast
    def ModelId(self) -> Optional[ModelId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = o + self._tab.Pos
            obj = ModelId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ModelForecast
    def ModelVersion(self) -> Optional[ModelVersion]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = o + self._tab.Pos
            obj = ModelVersion()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ModelForecast
    def InstrumentId(self) -> Optional[InstrumentId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = o + self._tab.Pos
            obj = InstrumentId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ModelForecast
    def FeatureSnapshotId(self) -> Optional[FeatureSnapshotId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            x = o + self._tab.Pos
            obj = FeatureSnapshotId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ModelForecast
    def ConfigurationVersion(self) -> Optional[ConfigurationVersion]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            x = o + self._tab.Pos
            obj = ConfigurationVersion()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ModelForecast
    def ForecastUnit(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # ModelForecast
    def ForecastValue(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ModelForecast
    def ConfidencePpm(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # ModelForecast
    def HorizonNs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # ModelForecast
    def CreatedProcessMonotonicTime(self) -> Optional[ProcessMonotonicTimeNs]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            x = o + self._tab.Pos
            obj = ProcessMonotonicTimeNs()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ModelForecast
    def ValidUntilProcessMonotonicTime(self) -> Optional[ProcessMonotonicTimeNs]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            x = o + self._tab.Pos
            obj = ProcessMonotonicTimeNs()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ModelForecast
    def AsOfExchangeEventTime(self) -> Optional[ExchangeEventTimeNs]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            x = o + self._tab.Pos
            obj = ExchangeEventTimeNs()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ModelForecast
    def ExpectedReturnPpm(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ModelForecast
    def ReturnP10Ppm(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ModelForecast
    def ReturnP50Ppm(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(38))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ModelForecast
    def ReturnP90Ppm(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(40))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ModelForecast
    def ProbabilityDownPpm(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(42))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # ModelForecast
    def ProbabilityFlatPpm(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(44))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # ModelForecast
    def ProbabilityUpPpm(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(46))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # ModelForecast
    def VolatilityPpm(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(48))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # ModelForecast
    def CalibrationScorePpm(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(50))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # ModelForecast
    def DataQualityScorePpm(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(52))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # ModelForecast
    def OodScorePpm(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(54))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # ModelForecast
    def HasTransactionCostEstimate(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(56))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # ModelForecast
    def EstimatedSpreadCostPpm(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(58))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # ModelForecast
    def EstimatedMarketImpactPpm(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(60))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # ModelForecast
    def EstimatedFeeCostPpm(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(62))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # ModelForecast
    def EstimatedSlippageCostPpm(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(64))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # ModelForecast
    def EstimatedAdverseSelectionCostPpm(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(66))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # ModelForecast
    def ForecastTarget(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(68))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # ModelForecast
    def TargetValue(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(70))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ModelForecast
    def TargetP10(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(72))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ModelForecast
    def TargetP50(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(74))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ModelForecast
    def TargetP90(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(76))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

def ModelForecastStart(builder: flatbuffers.Builder):
    builder.StartObject(37)

def Start(builder: flatbuffers.Builder):
    ModelForecastStart(builder)

def ModelForecastAddSchemaVersion(builder: flatbuffers.Builder, schemaVersion: Any):
    builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(schemaVersion), 0)

def AddSchemaVersion(builder: flatbuffers.Builder, schemaVersion: Any):
    ModelForecastAddSchemaVersion(builder, schemaVersion)

def ModelForecastAddForecastId(builder: flatbuffers.Builder, forecastId: Any):
    builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(forecastId), 0)

def AddForecastId(builder: flatbuffers.Builder, forecastId: Any):
    ModelForecastAddForecastId(builder, forecastId)

def ModelForecastAddSessionId(builder: flatbuffers.Builder, sessionId: Any):
    builder.PrependStructSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(sessionId), 0)

def AddSessionId(builder: flatbuffers.Builder, sessionId: Any):
    ModelForecastAddSessionId(builder, sessionId)

def ModelForecastAddModelId(builder: flatbuffers.Builder, modelId: Any):
    builder.PrependStructSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(modelId), 0)

def AddModelId(builder: flatbuffers.Builder, modelId: Any):
    ModelForecastAddModelId(builder, modelId)

def ModelForecastAddModelVersion(builder: flatbuffers.Builder, modelVersion: Any):
    builder.PrependStructSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(modelVersion), 0)

def AddModelVersion(builder: flatbuffers.Builder, modelVersion: Any):
    ModelForecastAddModelVersion(builder, modelVersion)

def ModelForecastAddInstrumentId(builder: flatbuffers.Builder, instrumentId: Any):
    builder.PrependStructSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(instrumentId), 0)

def AddInstrumentId(builder: flatbuffers.Builder, instrumentId: Any):
    ModelForecastAddInstrumentId(builder, instrumentId)

def ModelForecastAddFeatureSnapshotId(builder: flatbuffers.Builder, featureSnapshotId: Any):
    builder.PrependStructSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(featureSnapshotId), 0)

def AddFeatureSnapshotId(builder: flatbuffers.Builder, featureSnapshotId: Any):
    ModelForecastAddFeatureSnapshotId(builder, featureSnapshotId)

def ModelForecastAddConfigurationVersion(builder: flatbuffers.Builder, configurationVersion: Any):
    builder.PrependStructSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(configurationVersion), 0)

def AddConfigurationVersion(builder: flatbuffers.Builder, configurationVersion: Any):
    ModelForecastAddConfigurationVersion(builder, configurationVersion)

def ModelForecastAddForecastUnit(builder: flatbuffers.Builder, forecastUnit: int):
    builder.PrependUint8Slot(8, forecastUnit, 0)

def AddForecastUnit(builder: flatbuffers.Builder, forecastUnit: int):
    ModelForecastAddForecastUnit(builder, forecastUnit)

def ModelForecastAddForecastValue(builder: flatbuffers.Builder, forecastValue: int):
    builder.PrependInt64Slot(9, forecastValue, 0)

def AddForecastValue(builder: flatbuffers.Builder, forecastValue: int):
    ModelForecastAddForecastValue(builder, forecastValue)

def ModelForecastAddConfidencePpm(builder: flatbuffers.Builder, confidencePpm: int):
    builder.PrependUint32Slot(10, confidencePpm, 0)

def AddConfidencePpm(builder: flatbuffers.Builder, confidencePpm: int):
    ModelForecastAddConfidencePpm(builder, confidencePpm)

def ModelForecastAddHorizonNs(builder: flatbuffers.Builder, horizonNs: int):
    builder.PrependUint64Slot(11, horizonNs, 0)

def AddHorizonNs(builder: flatbuffers.Builder, horizonNs: int):
    ModelForecastAddHorizonNs(builder, horizonNs)

def ModelForecastAddCreatedProcessMonotonicTime(builder: flatbuffers.Builder, createdProcessMonotonicTime: Any):
    builder.PrependStructSlot(12, flatbuffers.number_types.UOffsetTFlags.py_type(createdProcessMonotonicTime), 0)

def AddCreatedProcessMonotonicTime(builder: flatbuffers.Builder, createdProcessMonotonicTime: Any):
    ModelForecastAddCreatedProcessMonotonicTime(builder, createdProcessMonotonicTime)

def ModelForecastAddValidUntilProcessMonotonicTime(builder: flatbuffers.Builder, validUntilProcessMonotonicTime: Any):
    builder.PrependStructSlot(13, flatbuffers.number_types.UOffsetTFlags.py_type(validUntilProcessMonotonicTime), 0)

def AddValidUntilProcessMonotonicTime(builder: flatbuffers.Builder, validUntilProcessMonotonicTime: Any):
    ModelForecastAddValidUntilProcessMonotonicTime(builder, validUntilProcessMonotonicTime)

def ModelForecastAddAsOfExchangeEventTime(builder: flatbuffers.Builder, asOfExchangeEventTime: Any):
    builder.PrependStructSlot(14, flatbuffers.number_types.UOffsetTFlags.py_type(asOfExchangeEventTime), 0)

def AddAsOfExchangeEventTime(builder: flatbuffers.Builder, asOfExchangeEventTime: Any):
    ModelForecastAddAsOfExchangeEventTime(builder, asOfExchangeEventTime)

def ModelForecastAddExpectedReturnPpm(builder: flatbuffers.Builder, expectedReturnPpm: int):
    builder.PrependInt64Slot(15, expectedReturnPpm, 0)

def AddExpectedReturnPpm(builder: flatbuffers.Builder, expectedReturnPpm: int):
    ModelForecastAddExpectedReturnPpm(builder, expectedReturnPpm)

def ModelForecastAddReturnP10Ppm(builder: flatbuffers.Builder, returnP10Ppm: int):
    builder.PrependInt64Slot(16, returnP10Ppm, 0)

def AddReturnP10Ppm(builder: flatbuffers.Builder, returnP10Ppm: int):
    ModelForecastAddReturnP10Ppm(builder, returnP10Ppm)

def ModelForecastAddReturnP50Ppm(builder: flatbuffers.Builder, returnP50Ppm: int):
    builder.PrependInt64Slot(17, returnP50Ppm, 0)

def AddReturnP50Ppm(builder: flatbuffers.Builder, returnP50Ppm: int):
    ModelForecastAddReturnP50Ppm(builder, returnP50Ppm)

def ModelForecastAddReturnP90Ppm(builder: flatbuffers.Builder, returnP90Ppm: int):
    builder.PrependInt64Slot(18, returnP90Ppm, 0)

def AddReturnP90Ppm(builder: flatbuffers.Builder, returnP90Ppm: int):
    ModelForecastAddReturnP90Ppm(builder, returnP90Ppm)

def ModelForecastAddProbabilityDownPpm(builder: flatbuffers.Builder, probabilityDownPpm: int):
    builder.PrependUint32Slot(19, probabilityDownPpm, 0)

def AddProbabilityDownPpm(builder: flatbuffers.Builder, probabilityDownPpm: int):
    ModelForecastAddProbabilityDownPpm(builder, probabilityDownPpm)

def ModelForecastAddProbabilityFlatPpm(builder: flatbuffers.Builder, probabilityFlatPpm: int):
    builder.PrependUint32Slot(20, probabilityFlatPpm, 0)

def AddProbabilityFlatPpm(builder: flatbuffers.Builder, probabilityFlatPpm: int):
    ModelForecastAddProbabilityFlatPpm(builder, probabilityFlatPpm)

def ModelForecastAddProbabilityUpPpm(builder: flatbuffers.Builder, probabilityUpPpm: int):
    builder.PrependUint32Slot(21, probabilityUpPpm, 0)

def AddProbabilityUpPpm(builder: flatbuffers.Builder, probabilityUpPpm: int):
    ModelForecastAddProbabilityUpPpm(builder, probabilityUpPpm)

def ModelForecastAddVolatilityPpm(builder: flatbuffers.Builder, volatilityPpm: int):
    builder.PrependUint64Slot(22, volatilityPpm, 0)

def AddVolatilityPpm(builder: flatbuffers.Builder, volatilityPpm: int):
    ModelForecastAddVolatilityPpm(builder, volatilityPpm)

def ModelForecastAddCalibrationScorePpm(builder: flatbuffers.Builder, calibrationScorePpm: int):
    builder.PrependUint32Slot(23, calibrationScorePpm, 0)

def AddCalibrationScorePpm(builder: flatbuffers.Builder, calibrationScorePpm: int):
    ModelForecastAddCalibrationScorePpm(builder, calibrationScorePpm)

def ModelForecastAddDataQualityScorePpm(builder: flatbuffers.Builder, dataQualityScorePpm: int):
    builder.PrependUint32Slot(24, dataQualityScorePpm, 0)

def AddDataQualityScorePpm(builder: flatbuffers.Builder, dataQualityScorePpm: int):
    ModelForecastAddDataQualityScorePpm(builder, dataQualityScorePpm)

def ModelForecastAddOodScorePpm(builder: flatbuffers.Builder, oodScorePpm: int):
    builder.PrependUint32Slot(25, oodScorePpm, 0)

def AddOodScorePpm(builder: flatbuffers.Builder, oodScorePpm: int):
    ModelForecastAddOodScorePpm(builder, oodScorePpm)

def ModelForecastAddHasTransactionCostEstimate(builder: flatbuffers.Builder, hasTransactionCostEstimate: bool):
    builder.PrependBoolSlot(26, hasTransactionCostEstimate, 0)

def AddHasTransactionCostEstimate(builder: flatbuffers.Builder, hasTransactionCostEstimate: bool):
    ModelForecastAddHasTransactionCostEstimate(builder, hasTransactionCostEstimate)

def ModelForecastAddEstimatedSpreadCostPpm(builder: flatbuffers.Builder, estimatedSpreadCostPpm: int):
    builder.PrependUint64Slot(27, estimatedSpreadCostPpm, 0)

def AddEstimatedSpreadCostPpm(builder: flatbuffers.Builder, estimatedSpreadCostPpm: int):
    ModelForecastAddEstimatedSpreadCostPpm(builder, estimatedSpreadCostPpm)

def ModelForecastAddEstimatedMarketImpactPpm(builder: flatbuffers.Builder, estimatedMarketImpactPpm: int):
    builder.PrependUint64Slot(28, estimatedMarketImpactPpm, 0)

def AddEstimatedMarketImpactPpm(builder: flatbuffers.Builder, estimatedMarketImpactPpm: int):
    ModelForecastAddEstimatedMarketImpactPpm(builder, estimatedMarketImpactPpm)

def ModelForecastAddEstimatedFeeCostPpm(builder: flatbuffers.Builder, estimatedFeeCostPpm: int):
    builder.PrependUint64Slot(29, estimatedFeeCostPpm, 0)

def AddEstimatedFeeCostPpm(builder: flatbuffers.Builder, estimatedFeeCostPpm: int):
    ModelForecastAddEstimatedFeeCostPpm(builder, estimatedFeeCostPpm)

def ModelForecastAddEstimatedSlippageCostPpm(builder: flatbuffers.Builder, estimatedSlippageCostPpm: int):
    builder.PrependUint64Slot(30, estimatedSlippageCostPpm, 0)

def AddEstimatedSlippageCostPpm(builder: flatbuffers.Builder, estimatedSlippageCostPpm: int):
    ModelForecastAddEstimatedSlippageCostPpm(builder, estimatedSlippageCostPpm)

def ModelForecastAddEstimatedAdverseSelectionCostPpm(builder: flatbuffers.Builder, estimatedAdverseSelectionCostPpm: int):
    builder.PrependUint64Slot(31, estimatedAdverseSelectionCostPpm, 0)

def AddEstimatedAdverseSelectionCostPpm(builder: flatbuffers.Builder, estimatedAdverseSelectionCostPpm: int):
    ModelForecastAddEstimatedAdverseSelectionCostPpm(builder, estimatedAdverseSelectionCostPpm)

def ModelForecastAddForecastTarget(builder: flatbuffers.Builder, forecastTarget: int):
    builder.PrependUint8Slot(32, forecastTarget, 0)

def AddForecastTarget(builder: flatbuffers.Builder, forecastTarget: int):
    ModelForecastAddForecastTarget(builder, forecastTarget)

def ModelForecastAddTargetValue(builder: flatbuffers.Builder, targetValue: int):
    builder.PrependInt64Slot(33, targetValue, 0)

def AddTargetValue(builder: flatbuffers.Builder, targetValue: int):
    ModelForecastAddTargetValue(builder, targetValue)

def ModelForecastAddTargetP10(builder: flatbuffers.Builder, targetP10: int):
    builder.PrependInt64Slot(34, targetP10, 0)

def AddTargetP10(builder: flatbuffers.Builder, targetP10: int):
    ModelForecastAddTargetP10(builder, targetP10)

def ModelForecastAddTargetP50(builder: flatbuffers.Builder, targetP50: int):
    builder.PrependInt64Slot(35, targetP50, 0)

def AddTargetP50(builder: flatbuffers.Builder, targetP50: int):
    ModelForecastAddTargetP50(builder, targetP50)

def ModelForecastAddTargetP90(builder: flatbuffers.Builder, targetP90: int):
    builder.PrependInt64Slot(36, targetP90, 0)

def AddTargetP90(builder: flatbuffers.Builder, targetP90: int):
    ModelForecastAddTargetP90(builder, targetP90)

def ModelForecastEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return ModelForecastEnd(builder)
