from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from aegis.mx.contracts.v1.ConfigurationVersion import ConfigurationVersion
from aegis.mx.contracts.v1.ExchangeEventTimeNs import ExchangeEventTimeNs
from aegis.mx.contracts.v1.FeatureSnapshotId import FeatureSnapshotId
from aegis.mx.contracts.v1.ForecastId import ForecastId
from aegis.mx.contracts.v1.ForecastTarget import ForecastTarget
from aegis.mx.contracts.v1.ForecastUnit import ForecastUnit
from aegis.mx.contracts.v1.InstrumentId import InstrumentId
from aegis.mx.contracts.v1.ModelId import ModelId
from aegis.mx.contracts.v1.ModelVersion import ModelVersion
from aegis.mx.contracts.v1.ProcessMonotonicTimeNs import ProcessMonotonicTimeNs
from aegis.mx.contracts.v1.SchemaVersion import SchemaVersion
from aegis.mx.contracts.v1.SessionId import SessionId

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class ModelForecast:
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> ModelForecast: ...
  @classmethod
  def GetRootAsModelForecast(cls, buf: bytes, offset: int) -> ModelForecast: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def SchemaVersion(self) -> SchemaVersion | None: ...
  def ForecastId(self) -> ForecastId | None: ...
  def SessionId(self) -> SessionId | None: ...
  def ModelId(self) -> ModelId | None: ...
  def ModelVersion(self) -> ModelVersion | None: ...
  def InstrumentId(self) -> InstrumentId | None: ...
  def FeatureSnapshotId(self) -> FeatureSnapshotId | None: ...
  def ConfigurationVersion(self) -> ConfigurationVersion | None: ...
  def ForecastUnit(self) -> typing.Literal[ForecastUnit.UNKNOWN, ForecastUnit.RETURN_TICKS, ForecastUnit.FAIR_VALUE_TICKS, ForecastUnit.PROBABILITY_PPM, ForecastUnit.QUANTITY_UNITS, ForecastUnit.RETURN_PPM, ForecastUnit.VOLATILITY_PPM, ForecastUnit.VOLUME_UNITS, ForecastUnit.SPREAD_TICKS, ForecastUnit.FACTOR_PPM]: ...
  def ForecastValue(self) -> int: ...
  def ConfidencePpm(self) -> int: ...
  def HorizonNs(self) -> int: ...
  def CreatedProcessMonotonicTime(self) -> ProcessMonotonicTimeNs | None: ...
  def ValidUntilProcessMonotonicTime(self) -> ProcessMonotonicTimeNs | None: ...
  def AsOfExchangeEventTime(self) -> ExchangeEventTimeNs | None: ...
  def ExpectedReturnPpm(self) -> int: ...
  def ReturnP10Ppm(self) -> int: ...
  def ReturnP50Ppm(self) -> int: ...
  def ReturnP90Ppm(self) -> int: ...
  def ProbabilityDownPpm(self) -> int: ...
  def ProbabilityFlatPpm(self) -> int: ...
  def ProbabilityUpPpm(self) -> int: ...
  def VolatilityPpm(self) -> int: ...
  def CalibrationScorePpm(self) -> int: ...
  def DataQualityScorePpm(self) -> int: ...
  def OodScorePpm(self) -> int: ...
  def HasTransactionCostEstimate(self) -> bool: ...
  def EstimatedSpreadCostPpm(self) -> int: ...
  def EstimatedMarketImpactPpm(self) -> int: ...
  def EstimatedFeeCostPpm(self) -> int: ...
  def EstimatedSlippageCostPpm(self) -> int: ...
  def EstimatedAdverseSelectionCostPpm(self) -> int: ...
  def ForecastTarget(self) -> typing.Literal[ForecastTarget.UNKNOWN, ForecastTarget.RETURN, ForecastTarget.REALIZED_VOLATILITY, ForecastTarget.VOLUME, ForecastTarget.SPREAD, ForecastTarget.MARKET_FACTOR, ForecastTarget.SECTOR_FACTOR]: ...
  def TargetValue(self) -> int: ...
  def TargetP10(self) -> int: ...
  def TargetP50(self) -> int: ...
  def TargetP90(self) -> int: ...
def ModelForecastStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def ModelForecastAddSchemaVersion(builder: flatbuffers.Builder, schemaVersion: uoffset) -> None: ...
def ModelForecastAddForecastId(builder: flatbuffers.Builder, forecastId: uoffset) -> None: ...
def ModelForecastAddSessionId(builder: flatbuffers.Builder, sessionId: uoffset) -> None: ...
def ModelForecastAddModelId(builder: flatbuffers.Builder, modelId: uoffset) -> None: ...
def ModelForecastAddModelVersion(builder: flatbuffers.Builder, modelVersion: uoffset) -> None: ...
def ModelForecastAddInstrumentId(builder: flatbuffers.Builder, instrumentId: uoffset) -> None: ...
def ModelForecastAddFeatureSnapshotId(builder: flatbuffers.Builder, featureSnapshotId: uoffset) -> None: ...
def ModelForecastAddConfigurationVersion(builder: flatbuffers.Builder, configurationVersion: uoffset) -> None: ...
def ModelForecastAddForecastUnit(builder: flatbuffers.Builder, forecastUnit: typing.Literal[ForecastUnit.UNKNOWN, ForecastUnit.RETURN_TICKS, ForecastUnit.FAIR_VALUE_TICKS, ForecastUnit.PROBABILITY_PPM, ForecastUnit.QUANTITY_UNITS, ForecastUnit.RETURN_PPM, ForecastUnit.VOLATILITY_PPM, ForecastUnit.VOLUME_UNITS, ForecastUnit.SPREAD_TICKS, ForecastUnit.FACTOR_PPM]) -> None: ...
def ModelForecastAddForecastValue(builder: flatbuffers.Builder, forecastValue: int) -> None: ...
def ModelForecastAddConfidencePpm(builder: flatbuffers.Builder, confidencePpm: int) -> None: ...
def ModelForecastAddHorizonNs(builder: flatbuffers.Builder, horizonNs: int) -> None: ...
def ModelForecastAddCreatedProcessMonotonicTime(builder: flatbuffers.Builder, createdProcessMonotonicTime: uoffset) -> None: ...
def ModelForecastAddValidUntilProcessMonotonicTime(builder: flatbuffers.Builder, validUntilProcessMonotonicTime: uoffset) -> None: ...
def ModelForecastAddAsOfExchangeEventTime(builder: flatbuffers.Builder, asOfExchangeEventTime: uoffset) -> None: ...
def ModelForecastAddExpectedReturnPpm(builder: flatbuffers.Builder, expectedReturnPpm: int) -> None: ...
def ModelForecastAddReturnP10Ppm(builder: flatbuffers.Builder, returnP10Ppm: int) -> None: ...
def ModelForecastAddReturnP50Ppm(builder: flatbuffers.Builder, returnP50Ppm: int) -> None: ...
def ModelForecastAddReturnP90Ppm(builder: flatbuffers.Builder, returnP90Ppm: int) -> None: ...
def ModelForecastAddProbabilityDownPpm(builder: flatbuffers.Builder, probabilityDownPpm: int) -> None: ...
def ModelForecastAddProbabilityFlatPpm(builder: flatbuffers.Builder, probabilityFlatPpm: int) -> None: ...
def ModelForecastAddProbabilityUpPpm(builder: flatbuffers.Builder, probabilityUpPpm: int) -> None: ...
def ModelForecastAddVolatilityPpm(builder: flatbuffers.Builder, volatilityPpm: int) -> None: ...
def ModelForecastAddCalibrationScorePpm(builder: flatbuffers.Builder, calibrationScorePpm: int) -> None: ...
def ModelForecastAddDataQualityScorePpm(builder: flatbuffers.Builder, dataQualityScorePpm: int) -> None: ...
def ModelForecastAddOodScorePpm(builder: flatbuffers.Builder, oodScorePpm: int) -> None: ...
def ModelForecastAddHasTransactionCostEstimate(builder: flatbuffers.Builder, hasTransactionCostEstimate: bool) -> None: ...
def ModelForecastAddEstimatedSpreadCostPpm(builder: flatbuffers.Builder, estimatedSpreadCostPpm: int) -> None: ...
def ModelForecastAddEstimatedMarketImpactPpm(builder: flatbuffers.Builder, estimatedMarketImpactPpm: int) -> None: ...
def ModelForecastAddEstimatedFeeCostPpm(builder: flatbuffers.Builder, estimatedFeeCostPpm: int) -> None: ...
def ModelForecastAddEstimatedSlippageCostPpm(builder: flatbuffers.Builder, estimatedSlippageCostPpm: int) -> None: ...
def ModelForecastAddEstimatedAdverseSelectionCostPpm(builder: flatbuffers.Builder, estimatedAdverseSelectionCostPpm: int) -> None: ...
def ModelForecastAddForecastTarget(builder: flatbuffers.Builder, forecastTarget: typing.Literal[ForecastTarget.UNKNOWN, ForecastTarget.RETURN, ForecastTarget.REALIZED_VOLATILITY, ForecastTarget.VOLUME, ForecastTarget.SPREAD, ForecastTarget.MARKET_FACTOR, ForecastTarget.SECTOR_FACTOR]) -> None: ...
def ModelForecastAddTargetValue(builder: flatbuffers.Builder, targetValue: int) -> None: ...
def ModelForecastAddTargetP10(builder: flatbuffers.Builder, targetP10: int) -> None: ...
def ModelForecastAddTargetP50(builder: flatbuffers.Builder, targetP50: int) -> None: ...
def ModelForecastAddTargetP90(builder: flatbuffers.Builder, targetP90: int) -> None: ...
def ModelForecastEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

