# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

class OmsApplyStatusCode(object):
    UNKNOWN = 0
    APPLIED = 1
    DUPLICATE = 2
    RECONCILED = 3
    OUT_OF_ORDER_APPLIED = 4
    FORBIDDEN_TRANSITION = 5
    INVALID = 6
    NOT_FOUND = 7
    CAPACITY_EXHAUSTED = 8
    JOURNAL_UNAVAILABLE = 9
    FENCED = 10
    INHIBITED = 11
    BUSY = 12
    STOPPED = 13
