# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

class OmsEventSourceCode(object):
    UNKNOWN = 0
    INTERNAL = 1
    GATEWAY = 2
    DROP_COPY = 3
    RECOVERY = 4
