# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

class OmsInputKindCode(object):
    UNKNOWN = 0
    ACCEPT_INTENT = 1
    MARK_READY = 2
    DISPATCH = 3
    CANCEL_INTENT = 4
    REPLACE_INTENT = 5
    ACKNOWLEDGEMENT = 6
    REJECTION = 7
    FILL = 8
    CANCEL_ACKNOWLEDGEMENT = 9
    CANCEL_REJECTION = 10
    REPLACE_ACKNOWLEDGEMENT = 11
    REPLACE_REJECTION = 12
    EXPIRE = 13
    RECOVERY_BEGIN = 14
    RECOVERY_OBSERVATION = 15
    AUTHORITY_UPDATE = 16
