# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

class OmsOrderStateCode(object):
    UNKNOWN = 0
    CREATED = 1
    READY = 2
    PENDING_ACK = 3
    WORKING = 4
    PARTIALLY_FILLED = 5
    PENDING_CANCEL = 6
    PENDING_REPLACE = 7
    FILLED = 8
    CANCELED = 9
    REJECTED = 10
    EXPIRED = 11
    UNKNOWN_RECOVERY = 12
