# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from aegis.mx.contracts.v1.AccountId import AccountId
from aegis.mx.contracts.v1.ConfigurationVersion import ConfigurationVersion
from aegis.mx.contracts.v1.FeatureSnapshotId import FeatureSnapshotId
from aegis.mx.contracts.v1.ForecastId import ForecastId
from aegis.mx.contracts.v1.InstrumentId import InstrumentId
from aegis.mx.contracts.v1.IntentId import IntentId
from aegis.mx.contracts.v1.OrderId import OrderId
from aegis.mx.contracts.v1.ProcessMonotonicTimeNs import ProcessMonotonicTimeNs
from aegis.mx.contracts.v1.SchemaVersion import SchemaVersion
from aegis.mx.contracts.v1.SessionId import SessionId
from aegis.mx.contracts.v1.StrategyId import StrategyId
from aegis.mx.contracts.v1.VenueId import VenueId
from typing import Optional
np = import_numpy()

class OrderIntent(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = OrderIntent()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsOrderIntent(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # OrderIntent
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # OrderIntent
    def SchemaVersion(self) -> Optional[SchemaVersion]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            obj = SchemaVersion()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # OrderIntent
    def IntentId(self) -> Optional[IntentId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            obj = IntentId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # OrderIntent
    def SessionId(self) -> Optional[SessionId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = o + self._tab.Pos
            obj = SessionId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # OrderIntent
    def StrategyId(self) -> Optional[StrategyId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = o + self._tab.Pos
            obj = StrategyId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # OrderIntent
    def InstrumentId(self) -> Optional[InstrumentId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = o + self._tab.Pos
            obj = InstrumentId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # OrderIntent
    def SourceForecastId(self) -> Optional[ForecastId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = o + self._tab.Pos
            obj = ForecastId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # OrderIntent
    def TargetOrderId(self) -> Optional[OrderId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            x = o + self._tab.Pos
            obj = OrderId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # OrderIntent
    def FeatureSnapshotId(self) -> Optional[FeatureSnapshotId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            x = o + self._tab.Pos
            obj = FeatureSnapshotId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # OrderIntent
    def ConfigurationVersion(self) -> Optional[ConfigurationVersion]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            x = o + self._tab.Pos
            obj = ConfigurationVersion()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # OrderIntent
    def Action(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # OrderIntent
    def PriceUnit(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # OrderIntent
    def HasLimitPrice(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # OrderIntent
    def LimitPriceTicks(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # OrderIntent
    def QuantityUnit(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # OrderIntent
    def QuantityUnits(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # OrderIntent
    def CreatedProcessMonotonicTime(self) -> Optional[ProcessMonotonicTimeNs]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            x = o + self._tab.Pos
            obj = ProcessMonotonicTimeNs()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # OrderIntent
    def ExpireProcessMonotonicTime(self) -> Optional[ProcessMonotonicTimeNs]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        if o != 0:
            x = o + self._tab.Pos
            obj = ProcessMonotonicTimeNs()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # OrderIntent
    def VenueId(self) -> Optional[VenueId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(38))
        if o != 0:
            x = o + self._tab.Pos
            obj = VenueId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # OrderIntent
    def AccountId(self) -> Optional[AccountId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(40))
        if o != 0:
            x = o + self._tab.Pos
            obj = AccountId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # OrderIntent
    def IntentHash(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(42))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def OrderIntentStart(builder: flatbuffers.Builder):
    builder.StartObject(20)

def Start(builder: flatbuffers.Builder):
    OrderIntentStart(builder)

def OrderIntentAddSchemaVersion(builder: flatbuffers.Builder, schemaVersion: Any):
    builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(schemaVersion), 0)

def AddSchemaVersion(builder: flatbuffers.Builder, schemaVersion: Any):
    OrderIntentAddSchemaVersion(builder, schemaVersion)

def OrderIntentAddIntentId(builder: flatbuffers.Builder, intentId: Any):
    builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(intentId), 0)

def AddIntentId(builder: flatbuffers.Builder, intentId: Any):
    OrderIntentAddIntentId(builder, intentId)

def OrderIntentAddSessionId(builder: flatbuffers.Builder, sessionId: Any):
    builder.PrependStructSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(sessionId), 0)

def AddSessionId(builder: flatbuffers.Builder, sessionId: Any):
    OrderIntentAddSessionId(builder, sessionId)

def OrderIntentAddStrategyId(builder: flatbuffers.Builder, strategyId: Any):
    builder.PrependStructSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(strategyId), 0)

def AddStrategyId(builder: flatbuffers.Builder, strategyId: Any):
    OrderIntentAddStrategyId(builder, strategyId)

def OrderIntentAddInstrumentId(builder: flatbuffers.Builder, instrumentId: Any):
    builder.PrependStructSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(instrumentId), 0)

def AddInstrumentId(builder: flatbuffers.Builder, instrumentId: Any):
    OrderIntentAddInstrumentId(builder, instrumentId)

def OrderIntentAddSourceForecastId(builder: flatbuffers.Builder, sourceForecastId: Any):
    builder.PrependStructSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(sourceForecastId), 0)

def AddSourceForecastId(builder: flatbuffers.Builder, sourceForecastId: Any):
    OrderIntentAddSourceForecastId(builder, sourceForecastId)

def OrderIntentAddTargetOrderId(builder: flatbuffers.Builder, targetOrderId: Any):
    builder.PrependStructSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(targetOrderId), 0)

def AddTargetOrderId(builder: flatbuffers.Builder, targetOrderId: Any):
    OrderIntentAddTargetOrderId(builder, targetOrderId)

def OrderIntentAddFeatureSnapshotId(builder: flatbuffers.Builder, featureSnapshotId: Any):
    builder.PrependStructSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(featureSnapshotId), 0)

def AddFeatureSnapshotId(builder: flatbuffers.Builder, featureSnapshotId: Any):
    OrderIntentAddFeatureSnapshotId(builder, featureSnapshotId)

def OrderIntentAddConfigurationVersion(builder: flatbuffers.Builder, configurationVersion: Any):
    builder.PrependStructSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(configurationVersion), 0)

def AddConfigurationVersion(builder: flatbuffers.Builder, configurationVersion: Any):
    OrderIntentAddConfigurationVersion(builder, configurationVersion)

def OrderIntentAddAction(builder: flatbuffers.Builder, action: int):
    builder.PrependUint8Slot(9, action, 0)

def AddAction(builder: flatbuffers.Builder, action: int):
    OrderIntentAddAction(builder, action)

def OrderIntentAddPriceUnit(builder: flatbuffers.Builder, priceUnit: int):
    builder.PrependUint8Slot(10, priceUnit, 0)

def AddPriceUnit(builder: flatbuffers.Builder, priceUnit: int):
    OrderIntentAddPriceUnit(builder, priceUnit)

def OrderIntentAddHasLimitPrice(builder: flatbuffers.Builder, hasLimitPrice: bool):
    builder.PrependBoolSlot(11, hasLimitPrice, 0)

def AddHasLimitPrice(builder: flatbuffers.Builder, hasLimitPrice: bool):
    OrderIntentAddHasLimitPrice(builder, hasLimitPrice)

def OrderIntentAddLimitPriceTicks(builder: flatbuffers.Builder, limitPriceTicks: int):
    builder.PrependInt64Slot(12, limitPriceTicks, 0)

def AddLimitPriceTicks(builder: flatbuffers.Builder, limitPriceTicks: int):
    OrderIntentAddLimitPriceTicks(builder, limitPriceTicks)

def OrderIntentAddQuantityUnit(builder: flatbuffers.Builder, quantityUnit: int):
    builder.PrependUint8Slot(13, quantityUnit, 0)

def AddQuantityUnit(builder: flatbuffers.Builder, quantityUnit: int):
    OrderIntentAddQuantityUnit(builder, quantityUnit)

def OrderIntentAddQuantityUnits(builder: flatbuffers.Builder, quantityUnits: int):
    builder.PrependUint64Slot(14, quantityUnits, 0)

def AddQuantityUnits(builder: flatbuffers.Builder, quantityUnits: int):
    OrderIntentAddQuantityUnits(builder, quantityUnits)

def OrderIntentAddCreatedProcessMonotonicTime(builder: flatbuffers.Builder, createdProcessMonotonicTime: Any):
    builder.PrependStructSlot(15, flatbuffers.number_types.UOffsetTFlags.py_type(createdProcessMonotonicTime), 0)

def AddCreatedProcessMonotonicTime(builder: flatbuffers.Builder, createdProcessMonotonicTime: Any):
    OrderIntentAddCreatedProcessMonotonicTime(builder, createdProcessMonotonicTime)

def OrderIntentAddExpireProcessMonotonicTime(builder: flatbuffers.Builder, expireProcessMonotonicTime: Any):
    builder.PrependStructSlot(16, flatbuffers.number_types.UOffsetTFlags.py_type(expireProcessMonotonicTime), 0)

def AddExpireProcessMonotonicTime(builder: flatbuffers.Builder, expireProcessMonotonicTime: Any):
    OrderIntentAddExpireProcessMonotonicTime(builder, expireProcessMonotonicTime)

def OrderIntentAddVenueId(builder: flatbuffers.Builder, venueId: Any):
    builder.PrependStructSlot(17, flatbuffers.number_types.UOffsetTFlags.py_type(venueId), 0)

def AddVenueId(builder: flatbuffers.Builder, venueId: Any):
    OrderIntentAddVenueId(builder, venueId)

def OrderIntentAddAccountId(builder: flatbuffers.Builder, accountId: Any):
    builder.PrependStructSlot(18, flatbuffers.number_types.UOffsetTFlags.py_type(accountId), 0)

def AddAccountId(builder: flatbuffers.Builder, accountId: Any):
    OrderIntentAddAccountId(builder, accountId)

def OrderIntentAddIntentHash(builder: flatbuffers.Builder, intentHash: int):
    builder.PrependUint64Slot(19, intentHash, 0)

def AddIntentHash(builder: flatbuffers.Builder, intentHash: int):
    OrderIntentAddIntentHash(builder, intentHash)

def OrderIntentEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return OrderIntentEnd(builder)
