from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from aegis.mx.contracts.v1.AccountId import AccountId
from aegis.mx.contracts.v1.ConfigurationVersion import ConfigurationVersion
from aegis.mx.contracts.v1.ExchangeEventTimeNs import ExchangeEventTimeNs
from aegis.mx.contracts.v1.GlobalEventId import GlobalEventId
from aegis.mx.contracts.v1.InstrumentId import InstrumentId
from aegis.mx.contracts.v1.IntentId import IntentId
from aegis.mx.contracts.v1.NicReceiveTimeNs import NicReceiveTimeNs
from aegis.mx.contracts.v1.OmsApplyStatusCode import OmsApplyStatusCode
from aegis.mx.contracts.v1.OmsEventSourceCode import OmsEventSourceCode
from aegis.mx.contracts.v1.OmsInputKindCode import OmsInputKindCode
from aegis.mx.contracts.v1.OmsOrderStateCode import OmsOrderStateCode
from aegis.mx.contracts.v1.OrderEventCode import OrderEventCode
from aegis.mx.contracts.v1.OrderId import OrderId
from aegis.mx.contracts.v1.PriceUnit import PriceUnit
from aegis.mx.contracts.v1.ProcessMonotonicTimeNs import ProcessMonotonicTimeNs
from aegis.mx.contracts.v1.QuantityUnit import QuantityUnit
from aegis.mx.contracts.v1.SchemaVersion import SchemaVersion
from aegis.mx.contracts.v1.SessionId import SessionId
from aegis.mx.contracts.v1.StrategyId import StrategyId
from aegis.mx.contracts.v1.VenueId import VenueId

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class OrderEvent:
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> OrderEvent: ...
  @classmethod
  def GetRootAsOrderEvent(cls, buf: bytes, offset: int) -> OrderEvent: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def SchemaVersion(self) -> SchemaVersion | None: ...
  def GlobalEventId(self) -> GlobalEventId | None: ...
  def OrderId(self) -> OrderId | None: ...
  def IntentId(self) -> IntentId | None: ...
  def SessionId(self) -> SessionId | None: ...
  def VenueId(self) -> VenueId | None: ...
  def InstrumentId(self) -> InstrumentId | None: ...
  def ConfigurationVersion(self) -> ConfigurationVersion | None: ...
  def Event(self) -> typing.Literal[OrderEventCode.UNKNOWN, OrderEventCode.ACCEPTED_BY_OMS, OrderEventCode.SUBMITTED_TO_GATEWAY, OrderEventCode.ACKNOWLEDGED, OrderEventCode.PARTIALLY_FILLED, OrderEventCode.FILLED, OrderEventCode.CANCEL_PENDING, OrderEventCode.CANCELLED, OrderEventCode.REJECTED]: ...
  def PriceUnit(self) -> typing.Literal[PriceUnit.UNKNOWN, PriceUnit.TICKS]: ...
  def PriceTicks(self) -> int: ...
  def QuantityUnit(self) -> typing.Literal[QuantityUnit.UNKNOWN, QuantityUnit.INSTRUMENT_UNITS]: ...
  def OrderQuantityUnits(self) -> int: ...
  def CumulativeFillQuantityUnits(self) -> int: ...
  def RemainingQuantityUnits(self) -> int: ...
  def ExchangeEventTime(self) -> ExchangeEventTimeNs | None: ...
  def NicReceiveTime(self) -> NicReceiveTimeNs | None: ...
  def ProcessMonotonicTime(self) -> ProcessMonotonicTimeNs | None: ...
  def ReasonCode(self) -> int: ...
  def AccountId(self) -> AccountId | None: ...
  def StrategyId(self) -> StrategyId | None: ...
  def InputKind(self) -> typing.Literal[OmsInputKindCode.UNKNOWN, OmsInputKindCode.ACCEPT_INTENT, OmsInputKindCode.MARK_READY, OmsInputKindCode.DISPATCH, OmsInputKindCode.CANCEL_INTENT, OmsInputKindCode.REPLACE_INTENT, OmsInputKindCode.ACKNOWLEDGEMENT, OmsInputKindCode.REJECTION, OmsInputKindCode.FILL, OmsInputKindCode.CANCEL_ACKNOWLEDGEMENT, OmsInputKindCode.CANCEL_REJECTION, OmsInputKindCode.REPLACE_ACKNOWLEDGEMENT, OmsInputKindCode.REPLACE_REJECTION, OmsInputKindCode.EXPIRE, OmsInputKindCode.RECOVERY_BEGIN, OmsInputKindCode.RECOVERY_OBSERVATION, OmsInputKindCode.AUTHORITY_UPDATE]: ...
  def Source(self) -> typing.Literal[OmsEventSourceCode.UNKNOWN, OmsEventSourceCode.INTERNAL, OmsEventSourceCode.GATEWAY, OmsEventSourceCode.DROP_COPY, OmsEventSourceCode.RECOVERY]: ...
  def Outcome(self) -> typing.Literal[OmsApplyStatusCode.UNKNOWN, OmsApplyStatusCode.APPLIED, OmsApplyStatusCode.DUPLICATE, OmsApplyStatusCode.RECONCILED, OmsApplyStatusCode.OUT_OF_ORDER_APPLIED, OmsApplyStatusCode.FORBIDDEN_TRANSITION, OmsApplyStatusCode.INVALID, OmsApplyStatusCode.NOT_FOUND, OmsApplyStatusCode.CAPACITY_EXHAUSTED, OmsApplyStatusCode.JOURNAL_UNAVAILABLE, OmsApplyStatusCode.FENCED, OmsApplyStatusCode.INHIBITED, OmsApplyStatusCode.BUSY, OmsApplyStatusCode.STOPPED]: ...
  def PreviousState(self) -> typing.Literal[OmsOrderStateCode.UNKNOWN, OmsOrderStateCode.CREATED, OmsOrderStateCode.READY, OmsOrderStateCode.PENDING_ACK, OmsOrderStateCode.WORKING, OmsOrderStateCode.PARTIALLY_FILLED, OmsOrderStateCode.PENDING_CANCEL, OmsOrderStateCode.PENDING_REPLACE, OmsOrderStateCode.FILLED, OmsOrderStateCode.CANCELED, OmsOrderStateCode.REJECTED, OmsOrderStateCode.EXPIRED, OmsOrderStateCode.UNKNOWN_RECOVERY]: ...
  def CurrentState(self) -> typing.Literal[OmsOrderStateCode.UNKNOWN, OmsOrderStateCode.CREATED, OmsOrderStateCode.READY, OmsOrderStateCode.PENDING_ACK, OmsOrderStateCode.WORKING, OmsOrderStateCode.PARTIALLY_FILLED, OmsOrderStateCode.PENDING_CANCEL, OmsOrderStateCode.PENDING_REPLACE, OmsOrderStateCode.FILLED, OmsOrderStateCode.CANCELED, OmsOrderStateCode.REJECTED, OmsOrderStateCode.EXPIRED, OmsOrderStateCode.UNKNOWN_RECOVERY]: ...
  def StateVersion(self) -> int: ...
  def ExchangeSessionEpoch(self) -> int: ...
  def ActiveFencingToken(self) -> int: ...
  def ExternalOrderIdHigh(self) -> int: ...
  def ExternalOrderIdLow(self) -> int: ...
  def ClientOrderId(self) -> str | None: ...
  def RiskDecisionHash(self) -> int: ...
  def JournalSequence(self) -> int: ...
  def SnapshotSequence(self) -> int: ...
  def SnapshotHash(self) -> int: ...
  def OrderEventHash(self) -> int: ...
  def JournalRecordHash(self) -> int: ...
def OrderEventStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def OrderEventAddSchemaVersion(builder: flatbuffers.Builder, schemaVersion: uoffset) -> None: ...
def OrderEventAddGlobalEventId(builder: flatbuffers.Builder, globalEventId: uoffset) -> None: ...
def OrderEventAddOrderId(builder: flatbuffers.Builder, orderId: uoffset) -> None: ...
def OrderEventAddIntentId(builder: flatbuffers.Builder, intentId: uoffset) -> None: ...
def OrderEventAddSessionId(builder: flatbuffers.Builder, sessionId: uoffset) -> None: ...
def OrderEventAddVenueId(builder: flatbuffers.Builder, venueId: uoffset) -> None: ...
def OrderEventAddInstrumentId(builder: flatbuffers.Builder, instrumentId: uoffset) -> None: ...
def OrderEventAddConfigurationVersion(builder: flatbuffers.Builder, configurationVersion: uoffset) -> None: ...
def OrderEventAddEvent(builder: flatbuffers.Builder, event: typing.Literal[OrderEventCode.UNKNOWN, OrderEventCode.ACCEPTED_BY_OMS, OrderEventCode.SUBMITTED_TO_GATEWAY, OrderEventCode.ACKNOWLEDGED, OrderEventCode.PARTIALLY_FILLED, OrderEventCode.FILLED, OrderEventCode.CANCEL_PENDING, OrderEventCode.CANCELLED, OrderEventCode.REJECTED]) -> None: ...
def OrderEventAddPriceUnit(builder: flatbuffers.Builder, priceUnit: typing.Literal[PriceUnit.UNKNOWN, PriceUnit.TICKS]) -> None: ...
def OrderEventAddPriceTicks(builder: flatbuffers.Builder, priceTicks: int) -> None: ...
def OrderEventAddQuantityUnit(builder: flatbuffers.Builder, quantityUnit: typing.Literal[QuantityUnit.UNKNOWN, QuantityUnit.INSTRUMENT_UNITS]) -> None: ...
def OrderEventAddOrderQuantityUnits(builder: flatbuffers.Builder, orderQuantityUnits: int) -> None: ...
def OrderEventAddCumulativeFillQuantityUnits(builder: flatbuffers.Builder, cumulativeFillQuantityUnits: int) -> None: ...
def OrderEventAddRemainingQuantityUnits(builder: flatbuffers.Builder, remainingQuantityUnits: int) -> None: ...
def OrderEventAddExchangeEventTime(builder: flatbuffers.Builder, exchangeEventTime: uoffset) -> None: ...
def OrderEventAddNicReceiveTime(builder: flatbuffers.Builder, nicReceiveTime: uoffset) -> None: ...
def OrderEventAddProcessMonotonicTime(builder: flatbuffers.Builder, processMonotonicTime: uoffset) -> None: ...
def OrderEventAddReasonCode(builder: flatbuffers.Builder, reasonCode: int) -> None: ...
def OrderEventAddAccountId(builder: flatbuffers.Builder, accountId: uoffset) -> None: ...
def OrderEventAddStrategyId(builder: flatbuffers.Builder, strategyId: uoffset) -> None: ...
def OrderEventAddInputKind(builder: flatbuffers.Builder, inputKind: typing.Literal[OmsInputKindCode.UNKNOWN, OmsInputKindCode.ACCEPT_INTENT, OmsInputKindCode.MARK_READY, OmsInputKindCode.DISPATCH, OmsInputKindCode.CANCEL_INTENT, OmsInputKindCode.REPLACE_INTENT, OmsInputKindCode.ACKNOWLEDGEMENT, OmsInputKindCode.REJECTION, OmsInputKindCode.FILL, OmsInputKindCode.CANCEL_ACKNOWLEDGEMENT, OmsInputKindCode.CANCEL_REJECTION, OmsInputKindCode.REPLACE_ACKNOWLEDGEMENT, OmsInputKindCode.REPLACE_REJECTION, OmsInputKindCode.EXPIRE, OmsInputKindCode.RECOVERY_BEGIN, OmsInputKindCode.RECOVERY_OBSERVATION, OmsInputKindCode.AUTHORITY_UPDATE]) -> None: ...
def OrderEventAddSource(builder: flatbuffers.Builder, source: typing.Literal[OmsEventSourceCode.UNKNOWN, OmsEventSourceCode.INTERNAL, OmsEventSourceCode.GATEWAY, OmsEventSourceCode.DROP_COPY, OmsEventSourceCode.RECOVERY]) -> None: ...
def OrderEventAddOutcome(builder: flatbuffers.Builder, outcome: typing.Literal[OmsApplyStatusCode.UNKNOWN, OmsApplyStatusCode.APPLIED, OmsApplyStatusCode.DUPLICATE, OmsApplyStatusCode.RECONCILED, OmsApplyStatusCode.OUT_OF_ORDER_APPLIED, OmsApplyStatusCode.FORBIDDEN_TRANSITION, OmsApplyStatusCode.INVALID, OmsApplyStatusCode.NOT_FOUND, OmsApplyStatusCode.CAPACITY_EXHAUSTED, OmsApplyStatusCode.JOURNAL_UNAVAILABLE, OmsApplyStatusCode.FENCED, OmsApplyStatusCode.INHIBITED, OmsApplyStatusCode.BUSY, OmsApplyStatusCode.STOPPED]) -> None: ...
def OrderEventAddPreviousState(builder: flatbuffers.Builder, previousState: typing.Literal[OmsOrderStateCode.UNKNOWN, OmsOrderStateCode.CREATED, OmsOrderStateCode.READY, OmsOrderStateCode.PENDING_ACK, OmsOrderStateCode.WORKING, OmsOrderStateCode.PARTIALLY_FILLED, OmsOrderStateCode.PENDING_CANCEL, OmsOrderStateCode.PENDING_REPLACE, OmsOrderStateCode.FILLED, OmsOrderStateCode.CANCELED, OmsOrderStateCode.REJECTED, OmsOrderStateCode.EXPIRED, OmsOrderStateCode.UNKNOWN_RECOVERY]) -> None: ...
def OrderEventAddCurrentState(builder: flatbuffers.Builder, currentState: typing.Literal[OmsOrderStateCode.UNKNOWN, OmsOrderStateCode.CREATED, OmsOrderStateCode.READY, OmsOrderStateCode.PENDING_ACK, OmsOrderStateCode.WORKING, OmsOrderStateCode.PARTIALLY_FILLED, OmsOrderStateCode.PENDING_CANCEL, OmsOrderStateCode.PENDING_REPLACE, OmsOrderStateCode.FILLED, OmsOrderStateCode.CANCELED, OmsOrderStateCode.REJECTED, OmsOrderStateCode.EXPIRED, OmsOrderStateCode.UNKNOWN_RECOVERY]) -> None: ...
def OrderEventAddStateVersion(builder: flatbuffers.Builder, stateVersion: int) -> None: ...
def OrderEventAddExchangeSessionEpoch(builder: flatbuffers.Builder, exchangeSessionEpoch: int) -> None: ...
def OrderEventAddActiveFencingToken(builder: flatbuffers.Builder, activeFencingToken: int) -> None: ...
def OrderEventAddExternalOrderIdHigh(builder: flatbuffers.Builder, externalOrderIdHigh: int) -> None: ...
def OrderEventAddExternalOrderIdLow(builder: flatbuffers.Builder, externalOrderIdLow: int) -> None: ...
def OrderEventAddClientOrderId(builder: flatbuffers.Builder, clientOrderId: uoffset) -> None: ...
def OrderEventAddRiskDecisionHash(builder: flatbuffers.Builder, riskDecisionHash: int) -> None: ...
def OrderEventAddJournalSequence(builder: flatbuffers.Builder, journalSequence: int) -> None: ...
def OrderEventAddSnapshotSequence(builder: flatbuffers.Builder, snapshotSequence: int) -> None: ...
def OrderEventAddSnapshotHash(builder: flatbuffers.Builder, snapshotHash: int) -> None: ...
def OrderEventAddOrderEventHash(builder: flatbuffers.Builder, orderEventHash: int) -> None: ...
def OrderEventAddJournalRecordHash(builder: flatbuffers.Builder, journalRecordHash: int) -> None: ...
def OrderEventEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

