# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

class OrderEventCode(object):
    UNKNOWN = 0
    ACCEPTED_BY_OMS = 1
    SUBMITTED_TO_GATEWAY = 2
    ACKNOWLEDGED = 3
    PARTIALLY_FILLED = 4
    FILLED = 5
    CANCEL_PENDING = 6
    CANCELLED = 7
    REJECTED = 8
