from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from aegis.mx.contracts.v1.AccountId import AccountId
from aegis.mx.contracts.v1.ConfigurationVersion import ConfigurationVersion
from aegis.mx.contracts.v1.FeatureSnapshotId import FeatureSnapshotId
from aegis.mx.contracts.v1.ForecastId import ForecastId
from aegis.mx.contracts.v1.InstrumentId import InstrumentId
from aegis.mx.contracts.v1.IntentAction import IntentAction
from aegis.mx.contracts.v1.IntentId import IntentId
from aegis.mx.contracts.v1.OrderId import OrderId
from aegis.mx.contracts.v1.PriceUnit import PriceUnit
from aegis.mx.contracts.v1.ProcessMonotonicTimeNs import ProcessMonotonicTimeNs
from aegis.mx.contracts.v1.QuantityUnit import QuantityUnit
from aegis.mx.contracts.v1.SchemaVersion import SchemaVersion
from aegis.mx.contracts.v1.SessionId import SessionId
from aegis.mx.contracts.v1.StrategyId import StrategyId
from aegis.mx.contracts.v1.VenueId import VenueId

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class OrderIntent:
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> OrderIntent: ...
  @classmethod
  def GetRootAsOrderIntent(cls, buf: bytes, offset: int) -> OrderIntent: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def SchemaVersion(self) -> SchemaVersion | None: ...
  def IntentId(self) -> IntentId | None: ...
  def SessionId(self) -> SessionId | None: ...
  def StrategyId(self) -> StrategyId | None: ...
  def InstrumentId(self) -> InstrumentId | None: ...
  def SourceForecastId(self) -> ForecastId | None: ...
  def TargetOrderId(self) -> OrderId | None: ...
  def FeatureSnapshotId(self) -> FeatureSnapshotId | None: ...
  def ConfigurationVersion(self) -> ConfigurationVersion | None: ...
  def Action(self) -> typing.Literal[IntentAction.UNKNOWN, IntentAction.BUY, IntentAction.SELL, IntentAction.CANCEL]: ...
  def PriceUnit(self) -> typing.Literal[PriceUnit.UNKNOWN, PriceUnit.TICKS]: ...
  def HasLimitPrice(self) -> bool: ...
  def LimitPriceTicks(self) -> int: ...
  def QuantityUnit(self) -> typing.Literal[QuantityUnit.UNKNOWN, QuantityUnit.INSTRUMENT_UNITS]: ...
  def QuantityUnits(self) -> int: ...
  def CreatedProcessMonotonicTime(self) -> ProcessMonotonicTimeNs | None: ...
  def ExpireProcessMonotonicTime(self) -> ProcessMonotonicTimeNs | None: ...
  def VenueId(self) -> VenueId | None: ...
  def AccountId(self) -> AccountId | None: ...
  def IntentHash(self) -> int: ...
def OrderIntentStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def OrderIntentAddSchemaVersion(builder: flatbuffers.Builder, schemaVersion: uoffset) -> None: ...
def OrderIntentAddIntentId(builder: flatbuffers.Builder, intentId: uoffset) -> None: ...
def OrderIntentAddSessionId(builder: flatbuffers.Builder, sessionId: uoffset) -> None: ...
def OrderIntentAddStrategyId(builder: flatbuffers.Builder, strategyId: uoffset) -> None: ...
def OrderIntentAddInstrumentId(builder: flatbuffers.Builder, instrumentId: uoffset) -> None: ...
def OrderIntentAddSourceForecastId(builder: flatbuffers.Builder, sourceForecastId: uoffset) -> None: ...
def OrderIntentAddTargetOrderId(builder: flatbuffers.Builder, targetOrderId: uoffset) -> None: ...
def OrderIntentAddFeatureSnapshotId(builder: flatbuffers.Builder, featureSnapshotId: uoffset) -> None: ...
def OrderIntentAddConfigurationVersion(builder: flatbuffers.Builder, configurationVersion: uoffset) -> None: ...
def OrderIntentAddAction(builder: flatbuffers.Builder, action: typing.Literal[IntentAction.UNKNOWN, IntentAction.BUY, IntentAction.SELL, IntentAction.CANCEL]) -> None: ...
def OrderIntentAddPriceUnit(builder: flatbuffers.Builder, priceUnit: typing.Literal[PriceUnit.UNKNOWN, PriceUnit.TICKS]) -> None: ...
def OrderIntentAddHasLimitPrice(builder: flatbuffers.Builder, hasLimitPrice: bool) -> None: ...
def OrderIntentAddLimitPriceTicks(builder: flatbuffers.Builder, limitPriceTicks: int) -> None: ...
def OrderIntentAddQuantityUnit(builder: flatbuffers.Builder, quantityUnit: typing.Literal[QuantityUnit.UNKNOWN, QuantityUnit.INSTRUMENT_UNITS]) -> None: ...
def OrderIntentAddQuantityUnits(builder: flatbuffers.Builder, quantityUnits: int) -> None: ...
def OrderIntentAddCreatedProcessMonotonicTime(builder: flatbuffers.Builder, createdProcessMonotonicTime: uoffset) -> None: ...
def OrderIntentAddExpireProcessMonotonicTime(builder: flatbuffers.Builder, expireProcessMonotonicTime: uoffset) -> None: ...
def OrderIntentAddVenueId(builder: flatbuffers.Builder, venueId: uoffset) -> None: ...
def OrderIntentAddAccountId(builder: flatbuffers.Builder, accountId: uoffset) -> None: ...
def OrderIntentAddIntentHash(builder: flatbuffers.Builder, intentHash: int) -> None: ...
def OrderIntentEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

