# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from aegis.mx.contracts.v1.AccountId import AccountId
from aegis.mx.contracts.v1.ConfigurationVersion import ConfigurationVersion
from aegis.mx.contracts.v1.ExchangeEventTimeNs import ExchangeEventTimeNs
from aegis.mx.contracts.v1.GlobalEventId import GlobalEventId
from aegis.mx.contracts.v1.InstrumentId import InstrumentId
from aegis.mx.contracts.v1.IntentId import IntentId
from aegis.mx.contracts.v1.NicReceiveTimeNs import NicReceiveTimeNs
from aegis.mx.contracts.v1.OrderId import OrderId
from aegis.mx.contracts.v1.ProcessMonotonicTimeNs import ProcessMonotonicTimeNs
from aegis.mx.contracts.v1.SchemaVersion import SchemaVersion
from aegis.mx.contracts.v1.SessionId import SessionId
from aegis.mx.contracts.v1.StrategyId import StrategyId
from aegis.mx.contracts.v1.VenueId import VenueId
from typing import Optional
np = import_numpy()

class OrderEvent(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = OrderEvent()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsOrderEvent(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # OrderEvent
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # OrderEvent
    def SchemaVersion(self) -> Optional[SchemaVersion]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            obj = SchemaVersion()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # OrderEvent
    def GlobalEventId(self) -> Optional[GlobalEventId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            obj = GlobalEventId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # OrderEvent
    def OrderId(self) -> Optional[OrderId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = o + self._tab.Pos
            obj = OrderId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # OrderEvent
    def IntentId(self) -> Optional[IntentId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = o + self._tab.Pos
            obj = IntentId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # OrderEvent
    def SessionId(self) -> Optional[SessionId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = o + self._tab.Pos
            obj = SessionId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # OrderEvent
    def VenueId(self) -> Optional[VenueId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = o + self._tab.Pos
            obj = VenueId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # OrderEvent
    def InstrumentId(self) -> Optional[InstrumentId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            x = o + self._tab.Pos
            obj = InstrumentId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # OrderEvent
    def ConfigurationVersion(self) -> Optional[ConfigurationVersion]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            x = o + self._tab.Pos
            obj = ConfigurationVersion()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # OrderEvent
    def Event(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # OrderEvent
    def PriceUnit(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # OrderEvent
    def PriceTicks(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # OrderEvent
    def QuantityUnit(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # OrderEvent
    def OrderQuantityUnits(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # OrderEvent
    def CumulativeFillQuantityUnits(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # OrderEvent
    def RemainingQuantityUnits(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # OrderEvent
    def ExchangeEventTime(self) -> Optional[ExchangeEventTimeNs]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            x = o + self._tab.Pos
            obj = ExchangeEventTimeNs()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # OrderEvent
    def NicReceiveTime(self) -> Optional[NicReceiveTimeNs]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        if o != 0:
            x = o + self._tab.Pos
            obj = NicReceiveTimeNs()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # OrderEvent
    def ProcessMonotonicTime(self) -> Optional[ProcessMonotonicTimeNs]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(38))
        if o != 0:
            x = o + self._tab.Pos
            obj = ProcessMonotonicTimeNs()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # OrderEvent
    def ReasonCode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(40))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # OrderEvent
    def AccountId(self) -> Optional[AccountId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(42))
        if o != 0:
            x = o + self._tab.Pos
            obj = AccountId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # OrderEvent
    def StrategyId(self) -> Optional[StrategyId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(44))
        if o != 0:
            x = o + self._tab.Pos
            obj = StrategyId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # OrderEvent
    def InputKind(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(46))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # OrderEvent
    def Source(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(48))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # OrderEvent
    def Outcome(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(50))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # OrderEvent
    def PreviousState(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(52))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # OrderEvent
    def CurrentState(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(54))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # OrderEvent
    def StateVersion(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(56))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # OrderEvent
    def ExchangeSessionEpoch(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(58))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # OrderEvent
    def ActiveFencingToken(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(60))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # OrderEvent
    def ExternalOrderIdHigh(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(62))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # OrderEvent
    def ExternalOrderIdLow(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(64))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # OrderEvent
    def ClientOrderId(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(66))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # OrderEvent
    def RiskDecisionHash(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(68))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # OrderEvent
    def JournalSequence(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(70))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # OrderEvent
    def SnapshotSequence(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(72))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # OrderEvent
    def SnapshotHash(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(74))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # OrderEvent
    def OrderEventHash(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(76))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # OrderEvent
    def JournalRecordHash(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(78))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def OrderEventStart(builder: flatbuffers.Builder):
    builder.StartObject(38)

def Start(builder: flatbuffers.Builder):
    OrderEventStart(builder)

def OrderEventAddSchemaVersion(builder: flatbuffers.Builder, schemaVersion: Any):
    builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(schemaVersion), 0)

def AddSchemaVersion(builder: flatbuffers.Builder, schemaVersion: Any):
    OrderEventAddSchemaVersion(builder, schemaVersion)

def OrderEventAddGlobalEventId(builder: flatbuffers.Builder, globalEventId: Any):
    builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(globalEventId), 0)

def AddGlobalEventId(builder: flatbuffers.Builder, globalEventId: Any):
    OrderEventAddGlobalEventId(builder, globalEventId)

def OrderEventAddOrderId(builder: flatbuffers.Builder, orderId: Any):
    builder.PrependStructSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(orderId), 0)

def AddOrderId(builder: flatbuffers.Builder, orderId: Any):
    OrderEventAddOrderId(builder, orderId)

def OrderEventAddIntentId(builder: flatbuffers.Builder, intentId: Any):
    builder.PrependStructSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(intentId), 0)

def AddIntentId(builder: flatbuffers.Builder, intentId: Any):
    OrderEventAddIntentId(builder, intentId)

def OrderEventAddSessionId(builder: flatbuffers.Builder, sessionId: Any):
    builder.PrependStructSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(sessionId), 0)

def AddSessionId(builder: flatbuffers.Builder, sessionId: Any):
    OrderEventAddSessionId(builder, sessionId)

def OrderEventAddVenueId(builder: flatbuffers.Builder, venueId: Any):
    builder.PrependStructSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(venueId), 0)

def AddVenueId(builder: flatbuffers.Builder, venueId: Any):
    OrderEventAddVenueId(builder, venueId)

def OrderEventAddInstrumentId(builder: flatbuffers.Builder, instrumentId: Any):
    builder.PrependStructSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(instrumentId), 0)

def AddInstrumentId(builder: flatbuffers.Builder, instrumentId: Any):
    OrderEventAddInstrumentId(builder, instrumentId)

def OrderEventAddConfigurationVersion(builder: flatbuffers.Builder, configurationVersion: Any):
    builder.PrependStructSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(configurationVersion), 0)

def AddConfigurationVersion(builder: flatbuffers.Builder, configurationVersion: Any):
    OrderEventAddConfigurationVersion(builder, configurationVersion)

def OrderEventAddEvent(builder: flatbuffers.Builder, event: int):
    builder.PrependUint8Slot(8, event, 0)

def AddEvent(builder: flatbuffers.Builder, event: int):
    OrderEventAddEvent(builder, event)

def OrderEventAddPriceUnit(builder: flatbuffers.Builder, priceUnit: int):
    builder.PrependUint8Slot(9, priceUnit, 0)

def AddPriceUnit(builder: flatbuffers.Builder, priceUnit: int):
    OrderEventAddPriceUnit(builder, priceUnit)

def OrderEventAddPriceTicks(builder: flatbuffers.Builder, priceTicks: int):
    builder.PrependInt64Slot(10, priceTicks, 0)

def AddPriceTicks(builder: flatbuffers.Builder, priceTicks: int):
    OrderEventAddPriceTicks(builder, priceTicks)

def OrderEventAddQuantityUnit(builder: flatbuffers.Builder, quantityUnit: int):
    builder.PrependUint8Slot(11, quantityUnit, 0)

def AddQuantityUnit(builder: flatbuffers.Builder, quantityUnit: int):
    OrderEventAddQuantityUnit(builder, quantityUnit)

def OrderEventAddOrderQuantityUnits(builder: flatbuffers.Builder, orderQuantityUnits: int):
    builder.PrependUint64Slot(12, orderQuantityUnits, 0)

def AddOrderQuantityUnits(builder: flatbuffers.Builder, orderQuantityUnits: int):
    OrderEventAddOrderQuantityUnits(builder, orderQuantityUnits)

def OrderEventAddCumulativeFillQuantityUnits(builder: flatbuffers.Builder, cumulativeFillQuantityUnits: int):
    builder.PrependUint64Slot(13, cumulativeFillQuantityUnits, 0)

def AddCumulativeFillQuantityUnits(builder: flatbuffers.Builder, cumulativeFillQuantityUnits: int):
    OrderEventAddCumulativeFillQuantityUnits(builder, cumulativeFillQuantityUnits)

def OrderEventAddRemainingQuantityUnits(builder: flatbuffers.Builder, remainingQuantityUnits: int):
    builder.PrependUint64Slot(14, remainingQuantityUnits, 0)

def AddRemainingQuantityUnits(builder: flatbuffers.Builder, remainingQuantityUnits: int):
    OrderEventAddRemainingQuantityUnits(builder, remainingQuantityUnits)

def OrderEventAddExchangeEventTime(builder: flatbuffers.Builder, exchangeEventTime: Any):
    builder.PrependStructSlot(15, flatbuffers.number_types.UOffsetTFlags.py_type(exchangeEventTime), 0)

def AddExchangeEventTime(builder: flatbuffers.Builder, exchangeEventTime: Any):
    OrderEventAddExchangeEventTime(builder, exchangeEventTime)

def OrderEventAddNicReceiveTime(builder: flatbuffers.Builder, nicReceiveTime: Any):
    builder.PrependStructSlot(16, flatbuffers.number_types.UOffsetTFlags.py_type(nicReceiveTime), 0)

def AddNicReceiveTime(builder: flatbuffers.Builder, nicReceiveTime: Any):
    OrderEventAddNicReceiveTime(builder, nicReceiveTime)

def OrderEventAddProcessMonotonicTime(builder: flatbuffers.Builder, processMonotonicTime: Any):
    builder.PrependStructSlot(17, flatbuffers.number_types.UOffsetTFlags.py_type(processMonotonicTime), 0)

def AddProcessMonotonicTime(builder: flatbuffers.Builder, processMonotonicTime: Any):
    OrderEventAddProcessMonotonicTime(builder, processMonotonicTime)

def OrderEventAddReasonCode(builder: flatbuffers.Builder, reasonCode: int):
    builder.PrependUint32Slot(18, reasonCode, 0)

def AddReasonCode(builder: flatbuffers.Builder, reasonCode: int):
    OrderEventAddReasonCode(builder, reasonCode)

def OrderEventAddAccountId(builder: flatbuffers.Builder, accountId: Any):
    builder.PrependStructSlot(19, flatbuffers.number_types.UOffsetTFlags.py_type(accountId), 0)

def AddAccountId(builder: flatbuffers.Builder, accountId: Any):
    OrderEventAddAccountId(builder, accountId)

def OrderEventAddStrategyId(builder: flatbuffers.Builder, strategyId: Any):
    builder.PrependStructSlot(20, flatbuffers.number_types.UOffsetTFlags.py_type(strategyId), 0)

def AddStrategyId(builder: flatbuffers.Builder, strategyId: Any):
    OrderEventAddStrategyId(builder, strategyId)

def OrderEventAddInputKind(builder: flatbuffers.Builder, inputKind: int):
    builder.PrependUint8Slot(21, inputKind, 0)

def AddInputKind(builder: flatbuffers.Builder, inputKind: int):
    OrderEventAddInputKind(builder, inputKind)

def OrderEventAddSource(builder: flatbuffers.Builder, source: int):
    builder.PrependUint8Slot(22, source, 0)

def AddSource(builder: flatbuffers.Builder, source: int):
    OrderEventAddSource(builder, source)

def OrderEventAddOutcome(builder: flatbuffers.Builder, outcome: int):
    builder.PrependUint8Slot(23, outcome, 0)

def AddOutcome(builder: flatbuffers.Builder, outcome: int):
    OrderEventAddOutcome(builder, outcome)

def OrderEventAddPreviousState(builder: flatbuffers.Builder, previousState: int):
    builder.PrependUint8Slot(24, previousState, 0)

def AddPreviousState(builder: flatbuffers.Builder, previousState: int):
    OrderEventAddPreviousState(builder, previousState)

def OrderEventAddCurrentState(builder: flatbuffers.Builder, currentState: int):
    builder.PrependUint8Slot(25, currentState, 0)

def AddCurrentState(builder: flatbuffers.Builder, currentState: int):
    OrderEventAddCurrentState(builder, currentState)

def OrderEventAddStateVersion(builder: flatbuffers.Builder, stateVersion: int):
    builder.PrependUint64Slot(26, stateVersion, 0)

def AddStateVersion(builder: flatbuffers.Builder, stateVersion: int):
    OrderEventAddStateVersion(builder, stateVersion)

def OrderEventAddExchangeSessionEpoch(builder: flatbuffers.Builder, exchangeSessionEpoch: int):
    builder.PrependUint64Slot(27, exchangeSessionEpoch, 0)

def AddExchangeSessionEpoch(builder: flatbuffers.Builder, exchangeSessionEpoch: int):
    OrderEventAddExchangeSessionEpoch(builder, exchangeSessionEpoch)

def OrderEventAddActiveFencingToken(builder: flatbuffers.Builder, activeFencingToken: int):
    builder.PrependUint64Slot(28, activeFencingToken, 0)

def AddActiveFencingToken(builder: flatbuffers.Builder, activeFencingToken: int):
    OrderEventAddActiveFencingToken(builder, activeFencingToken)

def OrderEventAddExternalOrderIdHigh(builder: flatbuffers.Builder, externalOrderIdHigh: int):
    builder.PrependUint64Slot(29, externalOrderIdHigh, 0)

def AddExternalOrderIdHigh(builder: flatbuffers.Builder, externalOrderIdHigh: int):
    OrderEventAddExternalOrderIdHigh(builder, externalOrderIdHigh)

def OrderEventAddExternalOrderIdLow(builder: flatbuffers.Builder, externalOrderIdLow: int):
    builder.PrependUint64Slot(30, externalOrderIdLow, 0)

def AddExternalOrderIdLow(builder: flatbuffers.Builder, externalOrderIdLow: int):
    OrderEventAddExternalOrderIdLow(builder, externalOrderIdLow)

def OrderEventAddClientOrderId(builder: flatbuffers.Builder, clientOrderId: int):
    builder.PrependUOffsetTRelativeSlot(31, flatbuffers.number_types.UOffsetTFlags.py_type(clientOrderId), 0)

def AddClientOrderId(builder: flatbuffers.Builder, clientOrderId: int):
    OrderEventAddClientOrderId(builder, clientOrderId)

def OrderEventAddRiskDecisionHash(builder: flatbuffers.Builder, riskDecisionHash: int):
    builder.PrependUint64Slot(32, riskDecisionHash, 0)

def AddRiskDecisionHash(builder: flatbuffers.Builder, riskDecisionHash: int):
    OrderEventAddRiskDecisionHash(builder, riskDecisionHash)

def OrderEventAddJournalSequence(builder: flatbuffers.Builder, journalSequence: int):
    builder.PrependUint64Slot(33, journalSequence, 0)

def AddJournalSequence(builder: flatbuffers.Builder, journalSequence: int):
    OrderEventAddJournalSequence(builder, journalSequence)

def OrderEventAddSnapshotSequence(builder: flatbuffers.Builder, snapshotSequence: int):
    builder.PrependUint64Slot(34, snapshotSequence, 0)

def AddSnapshotSequence(builder: flatbuffers.Builder, snapshotSequence: int):
    OrderEventAddSnapshotSequence(builder, snapshotSequence)

def OrderEventAddSnapshotHash(builder: flatbuffers.Builder, snapshotHash: int):
    builder.PrependUint64Slot(35, snapshotHash, 0)

def AddSnapshotHash(builder: flatbuffers.Builder, snapshotHash: int):
    OrderEventAddSnapshotHash(builder, snapshotHash)

def OrderEventAddOrderEventHash(builder: flatbuffers.Builder, orderEventHash: int):
    builder.PrependUint64Slot(36, orderEventHash, 0)

def AddOrderEventHash(builder: flatbuffers.Builder, orderEventHash: int):
    OrderEventAddOrderEventHash(builder, orderEventHash)

def OrderEventAddJournalRecordHash(builder: flatbuffers.Builder, journalRecordHash: int):
    builder.PrependUint64Slot(37, journalRecordHash, 0)

def AddJournalRecordHash(builder: flatbuffers.Builder, journalRecordHash: int):
    OrderEventAddJournalRecordHash(builder, journalRecordHash)

def OrderEventEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return OrderEventEnd(builder)
