# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

class PortfolioHealthCode(object):
    UNKNOWN = 0
    STARTING = 1
    HEALTHY = 2
    RECONCILING = 3
    UNSAFE = 4
    STOPPED = 5
