# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

class PortfolioInvariantCode(object):
    UNKNOWN = 0
    NONE = 1
    INVALID_CONFIGURATION = 2
    CONFLICTING_FILL = 3
    ORPHAN_FILL = 4
    ACCOUNTING_MISMATCH = 5
    ARITHMETIC_OVERFLOW = 6
    STALE_EVENT = 7
    UNSUPPORTED_CORPORATE_ACTION = 8
    JOURNAL_EXHAUSTED = 9
