# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from aegis.mx.contracts.v1.AccountId import AccountId
from aegis.mx.contracts.v1.ConfigurationVersion import ConfigurationVersion
from aegis.mx.contracts.v1.GlobalEventId import GlobalEventId
from aegis.mx.contracts.v1.InstrumentId import InstrumentId
from aegis.mx.contracts.v1.ProcessMonotonicTimeNs import ProcessMonotonicTimeNs
from aegis.mx.contracts.v1.RiskSnapshotId import RiskSnapshotId
from aegis.mx.contracts.v1.SchemaVersion import SchemaVersion
from aegis.mx.contracts.v1.SessionId import SessionId
from aegis.mx.contracts.v1.StrategyId import StrategyId
from typing import Optional
np = import_numpy()

class PositionSnapshot(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PositionSnapshot()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPositionSnapshot(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # PositionSnapshot
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PositionSnapshot
    def SchemaVersion(self) -> Optional[SchemaVersion]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            obj = SchemaVersion()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # PositionSnapshot
    def GlobalEventId(self) -> Optional[GlobalEventId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            obj = GlobalEventId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # PositionSnapshot
    def SessionId(self) -> Optional[SessionId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = o + self._tab.Pos
            obj = SessionId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # PositionSnapshot
    def StrategyId(self) -> Optional[StrategyId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = o + self._tab.Pos
            obj = StrategyId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # PositionSnapshot
    def InstrumentId(self) -> Optional[InstrumentId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = o + self._tab.Pos
            obj = InstrumentId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # PositionSnapshot
    def RiskSnapshotId(self) -> Optional[RiskSnapshotId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = o + self._tab.Pos
            obj = RiskSnapshotId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # PositionSnapshot
    def ConfigurationVersion(self) -> Optional[ConfigurationVersion]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            x = o + self._tab.Pos
            obj = ConfigurationVersion()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # PositionSnapshot
    def QuantityUnit(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # PositionSnapshot
    def NetQuantityUnits(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # PositionSnapshot
    def PriceUnit(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # PositionSnapshot
    def AveragePriceTicks(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # PositionSnapshot
    def CurrencyUnit(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # PositionSnapshot
    def RealizedPnlCurrencyNanos(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # PositionSnapshot
    def UnrealizedPnlCurrencyNanos(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # PositionSnapshot
    def AsOfProcessMonotonicTime(self) -> Optional[ProcessMonotonicTimeNs]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            x = o + self._tab.Pos
            obj = ProcessMonotonicTimeNs()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # PositionSnapshot
    def AccountId(self) -> Optional[AccountId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            x = o + self._tab.Pos
            obj = AccountId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # PositionSnapshot
    def PortfolioSequence(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # PositionSnapshot
    def SourceJournalSequence(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(38))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # PositionSnapshot
    def PortfolioSnapshotHash(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(40))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # PositionSnapshot
    def OpenCostCurrencyNanos(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(42))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # PositionSnapshot
    def PendingBuyQuantityUnits(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(44))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # PositionSnapshot
    def PendingSellQuantityUnits(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(46))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # PositionSnapshot
    def GrossExposureCurrencyNanos(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(48))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # PositionSnapshot
    def NetExposureCurrencyNanos(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(50))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # PositionSnapshot
    def BetaExposureCurrencyNanos(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(52))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # PositionSnapshot
    def LiquidityAdjustedExposureCurrencyNanos(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(54))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # PositionSnapshot
    def EventExposureCurrencyNanos(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(56))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # PositionSnapshot
    def DrawdownCurrencyNanos(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(58))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # PositionSnapshot
    def Health(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(60))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # PositionSnapshot
    def Invariant(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(62))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # PositionSnapshot
    def Ready(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(64))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def PositionSnapshotStart(builder: flatbuffers.Builder):
    builder.StartObject(31)

def Start(builder: flatbuffers.Builder):
    PositionSnapshotStart(builder)

def PositionSnapshotAddSchemaVersion(builder: flatbuffers.Builder, schemaVersion: Any):
    builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(schemaVersion), 0)

def AddSchemaVersion(builder: flatbuffers.Builder, schemaVersion: Any):
    PositionSnapshotAddSchemaVersion(builder, schemaVersion)

def PositionSnapshotAddGlobalEventId(builder: flatbuffers.Builder, globalEventId: Any):
    builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(globalEventId), 0)

def AddGlobalEventId(builder: flatbuffers.Builder, globalEventId: Any):
    PositionSnapshotAddGlobalEventId(builder, globalEventId)

def PositionSnapshotAddSessionId(builder: flatbuffers.Builder, sessionId: Any):
    builder.PrependStructSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(sessionId), 0)

def AddSessionId(builder: flatbuffers.Builder, sessionId: Any):
    PositionSnapshotAddSessionId(builder, sessionId)

def PositionSnapshotAddStrategyId(builder: flatbuffers.Builder, strategyId: Any):
    builder.PrependStructSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(strategyId), 0)

def AddStrategyId(builder: flatbuffers.Builder, strategyId: Any):
    PositionSnapshotAddStrategyId(builder, strategyId)

def PositionSnapshotAddInstrumentId(builder: flatbuffers.Builder, instrumentId: Any):
    builder.PrependStructSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(instrumentId), 0)

def AddInstrumentId(builder: flatbuffers.Builder, instrumentId: Any):
    PositionSnapshotAddInstrumentId(builder, instrumentId)

def PositionSnapshotAddRiskSnapshotId(builder: flatbuffers.Builder, riskSnapshotId: Any):
    builder.PrependStructSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(riskSnapshotId), 0)

def AddRiskSnapshotId(builder: flatbuffers.Builder, riskSnapshotId: Any):
    PositionSnapshotAddRiskSnapshotId(builder, riskSnapshotId)

def PositionSnapshotAddConfigurationVersion(builder: flatbuffers.Builder, configurationVersion: Any):
    builder.PrependStructSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(configurationVersion), 0)

def AddConfigurationVersion(builder: flatbuffers.Builder, configurationVersion: Any):
    PositionSnapshotAddConfigurationVersion(builder, configurationVersion)

def PositionSnapshotAddQuantityUnit(builder: flatbuffers.Builder, quantityUnit: int):
    builder.PrependUint8Slot(7, quantityUnit, 0)

def AddQuantityUnit(builder: flatbuffers.Builder, quantityUnit: int):
    PositionSnapshotAddQuantityUnit(builder, quantityUnit)

def PositionSnapshotAddNetQuantityUnits(builder: flatbuffers.Builder, netQuantityUnits: int):
    builder.PrependInt64Slot(8, netQuantityUnits, 0)

def AddNetQuantityUnits(builder: flatbuffers.Builder, netQuantityUnits: int):
    PositionSnapshotAddNetQuantityUnits(builder, netQuantityUnits)

def PositionSnapshotAddPriceUnit(builder: flatbuffers.Builder, priceUnit: int):
    builder.PrependUint8Slot(9, priceUnit, 0)

def AddPriceUnit(builder: flatbuffers.Builder, priceUnit: int):
    PositionSnapshotAddPriceUnit(builder, priceUnit)

def PositionSnapshotAddAveragePriceTicks(builder: flatbuffers.Builder, averagePriceTicks: int):
    builder.PrependInt64Slot(10, averagePriceTicks, 0)

def AddAveragePriceTicks(builder: flatbuffers.Builder, averagePriceTicks: int):
    PositionSnapshotAddAveragePriceTicks(builder, averagePriceTicks)

def PositionSnapshotAddCurrencyUnit(builder: flatbuffers.Builder, currencyUnit: int):
    builder.PrependUint8Slot(11, currencyUnit, 0)

def AddCurrencyUnit(builder: flatbuffers.Builder, currencyUnit: int):
    PositionSnapshotAddCurrencyUnit(builder, currencyUnit)

def PositionSnapshotAddRealizedPnlCurrencyNanos(builder: flatbuffers.Builder, realizedPnlCurrencyNanos: int):
    builder.PrependInt64Slot(12, realizedPnlCurrencyNanos, 0)

def AddRealizedPnlCurrencyNanos(builder: flatbuffers.Builder, realizedPnlCurrencyNanos: int):
    PositionSnapshotAddRealizedPnlCurrencyNanos(builder, realizedPnlCurrencyNanos)

def PositionSnapshotAddUnrealizedPnlCurrencyNanos(builder: flatbuffers.Builder, unrealizedPnlCurrencyNanos: int):
    builder.PrependInt64Slot(13, unrealizedPnlCurrencyNanos, 0)

def AddUnrealizedPnlCurrencyNanos(builder: flatbuffers.Builder, unrealizedPnlCurrencyNanos: int):
    PositionSnapshotAddUnrealizedPnlCurrencyNanos(builder, unrealizedPnlCurrencyNanos)

def PositionSnapshotAddAsOfProcessMonotonicTime(builder: flatbuffers.Builder, asOfProcessMonotonicTime: Any):
    builder.PrependStructSlot(14, flatbuffers.number_types.UOffsetTFlags.py_type(asOfProcessMonotonicTime), 0)

def AddAsOfProcessMonotonicTime(builder: flatbuffers.Builder, asOfProcessMonotonicTime: Any):
    PositionSnapshotAddAsOfProcessMonotonicTime(builder, asOfProcessMonotonicTime)

def PositionSnapshotAddAccountId(builder: flatbuffers.Builder, accountId: Any):
    builder.PrependStructSlot(15, flatbuffers.number_types.UOffsetTFlags.py_type(accountId), 0)

def AddAccountId(builder: flatbuffers.Builder, accountId: Any):
    PositionSnapshotAddAccountId(builder, accountId)

def PositionSnapshotAddPortfolioSequence(builder: flatbuffers.Builder, portfolioSequence: int):
    builder.PrependUint64Slot(16, portfolioSequence, 0)

def AddPortfolioSequence(builder: flatbuffers.Builder, portfolioSequence: int):
    PositionSnapshotAddPortfolioSequence(builder, portfolioSequence)

def PositionSnapshotAddSourceJournalSequence(builder: flatbuffers.Builder, sourceJournalSequence: int):
    builder.PrependUint64Slot(17, sourceJournalSequence, 0)

def AddSourceJournalSequence(builder: flatbuffers.Builder, sourceJournalSequence: int):
    PositionSnapshotAddSourceJournalSequence(builder, sourceJournalSequence)

def PositionSnapshotAddPortfolioSnapshotHash(builder: flatbuffers.Builder, portfolioSnapshotHash: int):
    builder.PrependUint64Slot(18, portfolioSnapshotHash, 0)

def AddPortfolioSnapshotHash(builder: flatbuffers.Builder, portfolioSnapshotHash: int):
    PositionSnapshotAddPortfolioSnapshotHash(builder, portfolioSnapshotHash)

def PositionSnapshotAddOpenCostCurrencyNanos(builder: flatbuffers.Builder, openCostCurrencyNanos: int):
    builder.PrependInt64Slot(19, openCostCurrencyNanos, 0)

def AddOpenCostCurrencyNanos(builder: flatbuffers.Builder, openCostCurrencyNanos: int):
    PositionSnapshotAddOpenCostCurrencyNanos(builder, openCostCurrencyNanos)

def PositionSnapshotAddPendingBuyQuantityUnits(builder: flatbuffers.Builder, pendingBuyQuantityUnits: int):
    builder.PrependUint64Slot(20, pendingBuyQuantityUnits, 0)

def AddPendingBuyQuantityUnits(builder: flatbuffers.Builder, pendingBuyQuantityUnits: int):
    PositionSnapshotAddPendingBuyQuantityUnits(builder, pendingBuyQuantityUnits)

def PositionSnapshotAddPendingSellQuantityUnits(builder: flatbuffers.Builder, pendingSellQuantityUnits: int):
    builder.PrependUint64Slot(21, pendingSellQuantityUnits, 0)

def AddPendingSellQuantityUnits(builder: flatbuffers.Builder, pendingSellQuantityUnits: int):
    PositionSnapshotAddPendingSellQuantityUnits(builder, pendingSellQuantityUnits)

def PositionSnapshotAddGrossExposureCurrencyNanos(builder: flatbuffers.Builder, grossExposureCurrencyNanos: int):
    builder.PrependUint64Slot(22, grossExposureCurrencyNanos, 0)

def AddGrossExposureCurrencyNanos(builder: flatbuffers.Builder, grossExposureCurrencyNanos: int):
    PositionSnapshotAddGrossExposureCurrencyNanos(builder, grossExposureCurrencyNanos)

def PositionSnapshotAddNetExposureCurrencyNanos(builder: flatbuffers.Builder, netExposureCurrencyNanos: int):
    builder.PrependInt64Slot(23, netExposureCurrencyNanos, 0)

def AddNetExposureCurrencyNanos(builder: flatbuffers.Builder, netExposureCurrencyNanos: int):
    PositionSnapshotAddNetExposureCurrencyNanos(builder, netExposureCurrencyNanos)

def PositionSnapshotAddBetaExposureCurrencyNanos(builder: flatbuffers.Builder, betaExposureCurrencyNanos: int):
    builder.PrependInt64Slot(24, betaExposureCurrencyNanos, 0)

def AddBetaExposureCurrencyNanos(builder: flatbuffers.Builder, betaExposureCurrencyNanos: int):
    PositionSnapshotAddBetaExposureCurrencyNanos(builder, betaExposureCurrencyNanos)

def PositionSnapshotAddLiquidityAdjustedExposureCurrencyNanos(builder: flatbuffers.Builder, liquidityAdjustedExposureCurrencyNanos: int):
    builder.PrependUint64Slot(25, liquidityAdjustedExposureCurrencyNanos, 0)

def AddLiquidityAdjustedExposureCurrencyNanos(builder: flatbuffers.Builder, liquidityAdjustedExposureCurrencyNanos: int):
    PositionSnapshotAddLiquidityAdjustedExposureCurrencyNanos(builder, liquidityAdjustedExposureCurrencyNanos)

def PositionSnapshotAddEventExposureCurrencyNanos(builder: flatbuffers.Builder, eventExposureCurrencyNanos: int):
    builder.PrependUint64Slot(26, eventExposureCurrencyNanos, 0)

def AddEventExposureCurrencyNanos(builder: flatbuffers.Builder, eventExposureCurrencyNanos: int):
    PositionSnapshotAddEventExposureCurrencyNanos(builder, eventExposureCurrencyNanos)

def PositionSnapshotAddDrawdownCurrencyNanos(builder: flatbuffers.Builder, drawdownCurrencyNanos: int):
    builder.PrependUint64Slot(27, drawdownCurrencyNanos, 0)

def AddDrawdownCurrencyNanos(builder: flatbuffers.Builder, drawdownCurrencyNanos: int):
    PositionSnapshotAddDrawdownCurrencyNanos(builder, drawdownCurrencyNanos)

def PositionSnapshotAddHealth(builder: flatbuffers.Builder, health: int):
    builder.PrependUint8Slot(28, health, 0)

def AddHealth(builder: flatbuffers.Builder, health: int):
    PositionSnapshotAddHealth(builder, health)

def PositionSnapshotAddInvariant(builder: flatbuffers.Builder, invariant: int):
    builder.PrependUint8Slot(29, invariant, 0)

def AddInvariant(builder: flatbuffers.Builder, invariant: int):
    PositionSnapshotAddInvariant(builder, invariant)

def PositionSnapshotAddReady(builder: flatbuffers.Builder, ready: bool):
    builder.PrependBoolSlot(30, ready, 0)

def AddReady(builder: flatbuffers.Builder, ready: bool):
    PositionSnapshotAddReady(builder, ready)

def PositionSnapshotEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return PositionSnapshotEnd(builder)
