from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from aegis.mx.contracts.v1.AccountId import AccountId
from aegis.mx.contracts.v1.ConfigurationVersion import ConfigurationVersion
from aegis.mx.contracts.v1.CurrencyUnit import CurrencyUnit
from aegis.mx.contracts.v1.GlobalEventId import GlobalEventId
from aegis.mx.contracts.v1.InstrumentId import InstrumentId
from aegis.mx.contracts.v1.PortfolioHealthCode import PortfolioHealthCode
from aegis.mx.contracts.v1.PortfolioInvariantCode import PortfolioInvariantCode
from aegis.mx.contracts.v1.PriceUnit import PriceUnit
from aegis.mx.contracts.v1.ProcessMonotonicTimeNs import ProcessMonotonicTimeNs
from aegis.mx.contracts.v1.QuantityUnit import QuantityUnit
from aegis.mx.contracts.v1.RiskSnapshotId import RiskSnapshotId
from aegis.mx.contracts.v1.SchemaVersion import SchemaVersion
from aegis.mx.contracts.v1.SessionId import SessionId
from aegis.mx.contracts.v1.StrategyId import StrategyId

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class PositionSnapshot:
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> PositionSnapshot: ...
  @classmethod
  def GetRootAsPositionSnapshot(cls, buf: bytes, offset: int) -> PositionSnapshot: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def SchemaVersion(self) -> SchemaVersion | None: ...
  def GlobalEventId(self) -> GlobalEventId | None: ...
  def SessionId(self) -> SessionId | None: ...
  def StrategyId(self) -> StrategyId | None: ...
  def InstrumentId(self) -> InstrumentId | None: ...
  def RiskSnapshotId(self) -> RiskSnapshotId | None: ...
  def ConfigurationVersion(self) -> ConfigurationVersion | None: ...
  def QuantityUnit(self) -> typing.Literal[QuantityUnit.UNKNOWN, QuantityUnit.INSTRUMENT_UNITS]: ...
  def NetQuantityUnits(self) -> int: ...
  def PriceUnit(self) -> typing.Literal[PriceUnit.UNKNOWN, PriceUnit.TICKS]: ...
  def AveragePriceTicks(self) -> int: ...
  def CurrencyUnit(self) -> typing.Literal[CurrencyUnit.UNKNOWN, CurrencyUnit.CURRENCY_NANOS]: ...
  def RealizedPnlCurrencyNanos(self) -> int: ...
  def UnrealizedPnlCurrencyNanos(self) -> int: ...
  def AsOfProcessMonotonicTime(self) -> ProcessMonotonicTimeNs | None: ...
  def AccountId(self) -> AccountId | None: ...
  def PortfolioSequence(self) -> int: ...
  def SourceJournalSequence(self) -> int: ...
  def PortfolioSnapshotHash(self) -> int: ...
  def OpenCostCurrencyNanos(self) -> int: ...
  def PendingBuyQuantityUnits(self) -> int: ...
  def PendingSellQuantityUnits(self) -> int: ...
  def GrossExposureCurrencyNanos(self) -> int: ...
  def NetExposureCurrencyNanos(self) -> int: ...
  def BetaExposureCurrencyNanos(self) -> int: ...
  def LiquidityAdjustedExposureCurrencyNanos(self) -> int: ...
  def EventExposureCurrencyNanos(self) -> int: ...
  def DrawdownCurrencyNanos(self) -> int: ...
  def Health(self) -> typing.Literal[PortfolioHealthCode.UNKNOWN, PortfolioHealthCode.STARTING, PortfolioHealthCode.HEALTHY, PortfolioHealthCode.RECONCILING, PortfolioHealthCode.UNSAFE, PortfolioHealthCode.STOPPED]: ...
  def Invariant(self) -> typing.Literal[PortfolioInvariantCode.UNKNOWN, PortfolioInvariantCode.NONE, PortfolioInvariantCode.INVALID_CONFIGURATION, PortfolioInvariantCode.CONFLICTING_FILL, PortfolioInvariantCode.ORPHAN_FILL, PortfolioInvariantCode.ACCOUNTING_MISMATCH, PortfolioInvariantCode.ARITHMETIC_OVERFLOW, PortfolioInvariantCode.STALE_EVENT, PortfolioInvariantCode.UNSUPPORTED_CORPORATE_ACTION, PortfolioInvariantCode.JOURNAL_EXHAUSTED]: ...
  def Ready(self) -> bool: ...
def PositionSnapshotStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def PositionSnapshotAddSchemaVersion(builder: flatbuffers.Builder, schemaVersion: uoffset) -> None: ...
def PositionSnapshotAddGlobalEventId(builder: flatbuffers.Builder, globalEventId: uoffset) -> None: ...
def PositionSnapshotAddSessionId(builder: flatbuffers.Builder, sessionId: uoffset) -> None: ...
def PositionSnapshotAddStrategyId(builder: flatbuffers.Builder, strategyId: uoffset) -> None: ...
def PositionSnapshotAddInstrumentId(builder: flatbuffers.Builder, instrumentId: uoffset) -> None: ...
def PositionSnapshotAddRiskSnapshotId(builder: flatbuffers.Builder, riskSnapshotId: uoffset) -> None: ...
def PositionSnapshotAddConfigurationVersion(builder: flatbuffers.Builder, configurationVersion: uoffset) -> None: ...
def PositionSnapshotAddQuantityUnit(builder: flatbuffers.Builder, quantityUnit: typing.Literal[QuantityUnit.UNKNOWN, QuantityUnit.INSTRUMENT_UNITS]) -> None: ...
def PositionSnapshotAddNetQuantityUnits(builder: flatbuffers.Builder, netQuantityUnits: int) -> None: ...
def PositionSnapshotAddPriceUnit(builder: flatbuffers.Builder, priceUnit: typing.Literal[PriceUnit.UNKNOWN, PriceUnit.TICKS]) -> None: ...
def PositionSnapshotAddAveragePriceTicks(builder: flatbuffers.Builder, averagePriceTicks: int) -> None: ...
def PositionSnapshotAddCurrencyUnit(builder: flatbuffers.Builder, currencyUnit: typing.Literal[CurrencyUnit.UNKNOWN, CurrencyUnit.CURRENCY_NANOS]) -> None: ...
def PositionSnapshotAddRealizedPnlCurrencyNanos(builder: flatbuffers.Builder, realizedPnlCurrencyNanos: int) -> None: ...
def PositionSnapshotAddUnrealizedPnlCurrencyNanos(builder: flatbuffers.Builder, unrealizedPnlCurrencyNanos: int) -> None: ...
def PositionSnapshotAddAsOfProcessMonotonicTime(builder: flatbuffers.Builder, asOfProcessMonotonicTime: uoffset) -> None: ...
def PositionSnapshotAddAccountId(builder: flatbuffers.Builder, accountId: uoffset) -> None: ...
def PositionSnapshotAddPortfolioSequence(builder: flatbuffers.Builder, portfolioSequence: int) -> None: ...
def PositionSnapshotAddSourceJournalSequence(builder: flatbuffers.Builder, sourceJournalSequence: int) -> None: ...
def PositionSnapshotAddPortfolioSnapshotHash(builder: flatbuffers.Builder, portfolioSnapshotHash: int) -> None: ...
def PositionSnapshotAddOpenCostCurrencyNanos(builder: flatbuffers.Builder, openCostCurrencyNanos: int) -> None: ...
def PositionSnapshotAddPendingBuyQuantityUnits(builder: flatbuffers.Builder, pendingBuyQuantityUnits: int) -> None: ...
def PositionSnapshotAddPendingSellQuantityUnits(builder: flatbuffers.Builder, pendingSellQuantityUnits: int) -> None: ...
def PositionSnapshotAddGrossExposureCurrencyNanos(builder: flatbuffers.Builder, grossExposureCurrencyNanos: int) -> None: ...
def PositionSnapshotAddNetExposureCurrencyNanos(builder: flatbuffers.Builder, netExposureCurrencyNanos: int) -> None: ...
def PositionSnapshotAddBetaExposureCurrencyNanos(builder: flatbuffers.Builder, betaExposureCurrencyNanos: int) -> None: ...
def PositionSnapshotAddLiquidityAdjustedExposureCurrencyNanos(builder: flatbuffers.Builder, liquidityAdjustedExposureCurrencyNanos: int) -> None: ...
def PositionSnapshotAddEventExposureCurrencyNanos(builder: flatbuffers.Builder, eventExposureCurrencyNanos: int) -> None: ...
def PositionSnapshotAddDrawdownCurrencyNanos(builder: flatbuffers.Builder, drawdownCurrencyNanos: int) -> None: ...
def PositionSnapshotAddHealth(builder: flatbuffers.Builder, health: typing.Literal[PortfolioHealthCode.UNKNOWN, PortfolioHealthCode.STARTING, PortfolioHealthCode.HEALTHY, PortfolioHealthCode.RECONCILING, PortfolioHealthCode.UNSAFE, PortfolioHealthCode.STOPPED]) -> None: ...
def PositionSnapshotAddInvariant(builder: flatbuffers.Builder, invariant: typing.Literal[PortfolioInvariantCode.UNKNOWN, PortfolioInvariantCode.NONE, PortfolioInvariantCode.INVALID_CONFIGURATION, PortfolioInvariantCode.CONFLICTING_FILL, PortfolioInvariantCode.ORPHAN_FILL, PortfolioInvariantCode.ACCOUNTING_MISMATCH, PortfolioInvariantCode.ARITHMETIC_OVERFLOW, PortfolioInvariantCode.STALE_EVENT, PortfolioInvariantCode.UNSUPPORTED_CORPORATE_ACTION, PortfolioInvariantCode.JOURNAL_EXHAUSTED]) -> None: ...
def PositionSnapshotAddReady(builder: flatbuffers.Builder, ready: bool) -> None: ...
def PositionSnapshotEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

