# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from aegis.mx.contracts.v1.ChannelId import ChannelId
from aegis.mx.contracts.v1.ExchangeEventTimeNs import ExchangeEventTimeNs
from aegis.mx.contracts.v1.GlobalEventId import GlobalEventId
from aegis.mx.contracts.v1.InstrumentId import InstrumentId
from aegis.mx.contracts.v1.NicReceiveTimeNs import NicReceiveTimeNs
from aegis.mx.contracts.v1.ProcessMonotonicTimeNs import ProcessMonotonicTimeNs
from aegis.mx.contracts.v1.SchemaVersion import SchemaVersion
from aegis.mx.contracts.v1.SessionId import SessionId
from aegis.mx.contracts.v1.VenueId import VenueId
from typing import Optional
np = import_numpy()

class QuoteEvent(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = QuoteEvent()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsQuoteEvent(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # QuoteEvent
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # QuoteEvent
    def SchemaVersion(self) -> Optional[SchemaVersion]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            obj = SchemaVersion()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # QuoteEvent
    def GlobalEventId(self) -> Optional[GlobalEventId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            obj = GlobalEventId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # QuoteEvent
    def SessionId(self) -> Optional[SessionId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = o + self._tab.Pos
            obj = SessionId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # QuoteEvent
    def VenueId(self) -> Optional[VenueId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = o + self._tab.Pos
            obj = VenueId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # QuoteEvent
    def InstrumentId(self) -> Optional[InstrumentId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = o + self._tab.Pos
            obj = InstrumentId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # QuoteEvent
    def ChannelId(self) -> Optional[ChannelId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = o + self._tab.Pos
            obj = ChannelId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # QuoteEvent
    def ChannelSequence(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # QuoteEvent
    def ExchangeEventTime(self) -> Optional[ExchangeEventTimeNs]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            x = o + self._tab.Pos
            obj = ExchangeEventTimeNs()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # QuoteEvent
    def NicReceiveTime(self) -> Optional[NicReceiveTimeNs]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            x = o + self._tab.Pos
            obj = NicReceiveTimeNs()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # QuoteEvent
    def ProcessMonotonicTime(self) -> Optional[ProcessMonotonicTimeNs]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            x = o + self._tab.Pos
            obj = ProcessMonotonicTimeNs()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # QuoteEvent
    def PriceUnit(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # QuoteEvent
    def BidPriceTicks(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # QuoteEvent
    def AskPriceTicks(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # QuoteEvent
    def QuantityUnit(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # QuoteEvent
    def BidQuantityUnits(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # QuoteEvent
    def AskQuantityUnits(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def QuoteEventStart(builder: flatbuffers.Builder):
    builder.StartObject(16)

def Start(builder: flatbuffers.Builder):
    QuoteEventStart(builder)

def QuoteEventAddSchemaVersion(builder: flatbuffers.Builder, schemaVersion: Any):
    builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(schemaVersion), 0)

def AddSchemaVersion(builder: flatbuffers.Builder, schemaVersion: Any):
    QuoteEventAddSchemaVersion(builder, schemaVersion)

def QuoteEventAddGlobalEventId(builder: flatbuffers.Builder, globalEventId: Any):
    builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(globalEventId), 0)

def AddGlobalEventId(builder: flatbuffers.Builder, globalEventId: Any):
    QuoteEventAddGlobalEventId(builder, globalEventId)

def QuoteEventAddSessionId(builder: flatbuffers.Builder, sessionId: Any):
    builder.PrependStructSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(sessionId), 0)

def AddSessionId(builder: flatbuffers.Builder, sessionId: Any):
    QuoteEventAddSessionId(builder, sessionId)

def QuoteEventAddVenueId(builder: flatbuffers.Builder, venueId: Any):
    builder.PrependStructSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(venueId), 0)

def AddVenueId(builder: flatbuffers.Builder, venueId: Any):
    QuoteEventAddVenueId(builder, venueId)

def QuoteEventAddInstrumentId(builder: flatbuffers.Builder, instrumentId: Any):
    builder.PrependStructSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(instrumentId), 0)

def AddInstrumentId(builder: flatbuffers.Builder, instrumentId: Any):
    QuoteEventAddInstrumentId(builder, instrumentId)

def QuoteEventAddChannelId(builder: flatbuffers.Builder, channelId: Any):
    builder.PrependStructSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(channelId), 0)

def AddChannelId(builder: flatbuffers.Builder, channelId: Any):
    QuoteEventAddChannelId(builder, channelId)

def QuoteEventAddChannelSequence(builder: flatbuffers.Builder, channelSequence: int):
    builder.PrependUint64Slot(6, channelSequence, 0)

def AddChannelSequence(builder: flatbuffers.Builder, channelSequence: int):
    QuoteEventAddChannelSequence(builder, channelSequence)

def QuoteEventAddExchangeEventTime(builder: flatbuffers.Builder, exchangeEventTime: Any):
    builder.PrependStructSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(exchangeEventTime), 0)

def AddExchangeEventTime(builder: flatbuffers.Builder, exchangeEventTime: Any):
    QuoteEventAddExchangeEventTime(builder, exchangeEventTime)

def QuoteEventAddNicReceiveTime(builder: flatbuffers.Builder, nicReceiveTime: Any):
    builder.PrependStructSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(nicReceiveTime), 0)

def AddNicReceiveTime(builder: flatbuffers.Builder, nicReceiveTime: Any):
    QuoteEventAddNicReceiveTime(builder, nicReceiveTime)

def QuoteEventAddProcessMonotonicTime(builder: flatbuffers.Builder, processMonotonicTime: Any):
    builder.PrependStructSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(processMonotonicTime), 0)

def AddProcessMonotonicTime(builder: flatbuffers.Builder, processMonotonicTime: Any):
    QuoteEventAddProcessMonotonicTime(builder, processMonotonicTime)

def QuoteEventAddPriceUnit(builder: flatbuffers.Builder, priceUnit: int):
    builder.PrependUint8Slot(10, priceUnit, 0)

def AddPriceUnit(builder: flatbuffers.Builder, priceUnit: int):
    QuoteEventAddPriceUnit(builder, priceUnit)

def QuoteEventAddBidPriceTicks(builder: flatbuffers.Builder, bidPriceTicks: int):
    builder.PrependInt64Slot(11, bidPriceTicks, 0)

def AddBidPriceTicks(builder: flatbuffers.Builder, bidPriceTicks: int):
    QuoteEventAddBidPriceTicks(builder, bidPriceTicks)

def QuoteEventAddAskPriceTicks(builder: flatbuffers.Builder, askPriceTicks: int):
    builder.PrependInt64Slot(12, askPriceTicks, 0)

def AddAskPriceTicks(builder: flatbuffers.Builder, askPriceTicks: int):
    QuoteEventAddAskPriceTicks(builder, askPriceTicks)

def QuoteEventAddQuantityUnit(builder: flatbuffers.Builder, quantityUnit: int):
    builder.PrependUint8Slot(13, quantityUnit, 0)

def AddQuantityUnit(builder: flatbuffers.Builder, quantityUnit: int):
    QuoteEventAddQuantityUnit(builder, quantityUnit)

def QuoteEventAddBidQuantityUnits(builder: flatbuffers.Builder, bidQuantityUnits: int):
    builder.PrependUint64Slot(14, bidQuantityUnits, 0)

def AddBidQuantityUnits(builder: flatbuffers.Builder, bidQuantityUnits: int):
    QuoteEventAddBidQuantityUnits(builder, bidQuantityUnits)

def QuoteEventAddAskQuantityUnits(builder: flatbuffers.Builder, askQuantityUnits: int):
    builder.PrependUint64Slot(15, askQuantityUnits, 0)

def AddAskQuantityUnits(builder: flatbuffers.Builder, askQuantityUnits: int):
    QuoteEventAddAskQuantityUnits(builder, askQuantityUnits)

def QuoteEventEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return QuoteEventEnd(builder)
