from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from aegis.mx.contracts.v1.ChannelId import ChannelId
from aegis.mx.contracts.v1.ExchangeEventTimeNs import ExchangeEventTimeNs
from aegis.mx.contracts.v1.GlobalEventId import GlobalEventId
from aegis.mx.contracts.v1.InstrumentId import InstrumentId
from aegis.mx.contracts.v1.NicReceiveTimeNs import NicReceiveTimeNs
from aegis.mx.contracts.v1.PriceUnit import PriceUnit
from aegis.mx.contracts.v1.ProcessMonotonicTimeNs import ProcessMonotonicTimeNs
from aegis.mx.contracts.v1.QuantityUnit import QuantityUnit
from aegis.mx.contracts.v1.SchemaVersion import SchemaVersion
from aegis.mx.contracts.v1.SessionId import SessionId
from aegis.mx.contracts.v1.VenueId import VenueId

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class QuoteEvent:
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> QuoteEvent: ...
  @classmethod
  def GetRootAsQuoteEvent(cls, buf: bytes, offset: int) -> QuoteEvent: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def SchemaVersion(self) -> SchemaVersion | None: ...
  def GlobalEventId(self) -> GlobalEventId | None: ...
  def SessionId(self) -> SessionId | None: ...
  def VenueId(self) -> VenueId | None: ...
  def InstrumentId(self) -> InstrumentId | None: ...
  def ChannelId(self) -> ChannelId | None: ...
  def ChannelSequence(self) -> int: ...
  def ExchangeEventTime(self) -> ExchangeEventTimeNs | None: ...
  def NicReceiveTime(self) -> NicReceiveTimeNs | None: ...
  def ProcessMonotonicTime(self) -> ProcessMonotonicTimeNs | None: ...
  def PriceUnit(self) -> typing.Literal[PriceUnit.UNKNOWN, PriceUnit.TICKS]: ...
  def BidPriceTicks(self) -> int: ...
  def AskPriceTicks(self) -> int: ...
  def QuantityUnit(self) -> typing.Literal[QuantityUnit.UNKNOWN, QuantityUnit.INSTRUMENT_UNITS]: ...
  def BidQuantityUnits(self) -> int: ...
  def AskQuantityUnits(self) -> int: ...
def QuoteEventStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def QuoteEventAddSchemaVersion(builder: flatbuffers.Builder, schemaVersion: uoffset) -> None: ...
def QuoteEventAddGlobalEventId(builder: flatbuffers.Builder, globalEventId: uoffset) -> None: ...
def QuoteEventAddSessionId(builder: flatbuffers.Builder, sessionId: uoffset) -> None: ...
def QuoteEventAddVenueId(builder: flatbuffers.Builder, venueId: uoffset) -> None: ...
def QuoteEventAddInstrumentId(builder: flatbuffers.Builder, instrumentId: uoffset) -> None: ...
def QuoteEventAddChannelId(builder: flatbuffers.Builder, channelId: uoffset) -> None: ...
def QuoteEventAddChannelSequence(builder: flatbuffers.Builder, channelSequence: int) -> None: ...
def QuoteEventAddExchangeEventTime(builder: flatbuffers.Builder, exchangeEventTime: uoffset) -> None: ...
def QuoteEventAddNicReceiveTime(builder: flatbuffers.Builder, nicReceiveTime: uoffset) -> None: ...
def QuoteEventAddProcessMonotonicTime(builder: flatbuffers.Builder, processMonotonicTime: uoffset) -> None: ...
def QuoteEventAddPriceUnit(builder: flatbuffers.Builder, priceUnit: typing.Literal[PriceUnit.UNKNOWN, PriceUnit.TICKS]) -> None: ...
def QuoteEventAddBidPriceTicks(builder: flatbuffers.Builder, bidPriceTicks: int) -> None: ...
def QuoteEventAddAskPriceTicks(builder: flatbuffers.Builder, askPriceTicks: int) -> None: ...
def QuoteEventAddQuantityUnit(builder: flatbuffers.Builder, quantityUnit: typing.Literal[QuantityUnit.UNKNOWN, QuantityUnit.INSTRUMENT_UNITS]) -> None: ...
def QuoteEventAddBidQuantityUnits(builder: flatbuffers.Builder, bidQuantityUnits: int) -> None: ...
def QuoteEventAddAskQuantityUnits(builder: flatbuffers.Builder, askQuantityUnits: int) -> None: ...
def QuoteEventEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

