from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from aegis.mx.contracts.v1.AccountId import AccountId
from aegis.mx.contracts.v1.ConfigurationVersion import ConfigurationVersion
from aegis.mx.contracts.v1.GlobalEventId import GlobalEventId
from aegis.mx.contracts.v1.InstrumentId import InstrumentId
from aegis.mx.contracts.v1.IntentAction import IntentAction
from aegis.mx.contracts.v1.IntentId import IntentId
from aegis.mx.contracts.v1.PriceUnit import PriceUnit
from aegis.mx.contracts.v1.ProcessMonotonicTimeNs import ProcessMonotonicTimeNs
from aegis.mx.contracts.v1.QuantityUnit import QuantityUnit
from aegis.mx.contracts.v1.RiskCheckCode import RiskCheckCode
from aegis.mx.contracts.v1.RiskDecisionCode import RiskDecisionCode
from aegis.mx.contracts.v1.RiskReasonCode import RiskReasonCode
from aegis.mx.contracts.v1.RiskSnapshotId import RiskSnapshotId
from aegis.mx.contracts.v1.SchemaVersion import SchemaVersion
from aegis.mx.contracts.v1.SessionId import SessionId
from aegis.mx.contracts.v1.Sha256Digest import Sha256Digest
from aegis.mx.contracts.v1.StrategyId import StrategyId
from aegis.mx.contracts.v1.TradingModeCode import TradingModeCode
from aegis.mx.contracts.v1.VenueId import VenueId

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class RiskDecision:
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> RiskDecision: ...
  @classmethod
  def GetRootAsRiskDecision(cls, buf: bytes, offset: int) -> RiskDecision: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def SchemaVersion(self) -> SchemaVersion | None: ...
  def GlobalEventId(self) -> GlobalEventId | None: ...
  def IntentId(self) -> IntentId | None: ...
  def SessionId(self) -> SessionId | None: ...
  def RiskSnapshotId(self) -> RiskSnapshotId | None: ...
  def ConfigurationVersion(self) -> ConfigurationVersion | None: ...
  def Decision(self) -> typing.Literal[RiskDecisionCode.UNKNOWN, RiskDecisionCode.REJECTED, RiskDecisionCode.APPROVED]: ...
  def Reason(self) -> typing.Literal[RiskReasonCode.UNKNOWN, RiskReasonCode.WITHIN_LIMITS, RiskReasonCode.KILL_SWITCH_ENGAGED, RiskReasonCode.STALE_MARKET_DATA, RiskReasonCode.INVALID_BOOK, RiskReasonCode.CLOCK_UNSYNCHRONIZED, RiskReasonCode.LIMIT_EXCEEDED, RiskReasonCode.INVALID_INTENT, RiskReasonCode.CONFIGURATION_MISMATCH, RiskReasonCode.EXPIRED_INTENT, RiskReasonCode.TRADING_MODE_UNAUTHORIZED, RiskReasonCode.OPERATOR_SESSION_UNAUTHORIZED, RiskReasonCode.STRATEGY_UNAUTHORIZED, RiskReasonCode.SYMBOL_UNAUTHORIZED, RiskReasonCode.RESTRICTED_INSTRUMENT, RiskReasonCode.MARKET_STATE_UNSAFE, RiskReasonCode.TRADING_HALTED, RiskReasonCode.FEED_BOOK_UNHEALTHY, RiskReasonCode.ORDER_QUANTITY_EXCEEDED, RiskReasonCode.ORDER_NOTIONAL_EXCEEDED, RiskReasonCode.PRICE_COLLAR_EXCEEDED, RiskReasonCode.INVALID_TICK_SIZE, RiskReasonCode.DUPLICATE_INTENT, RiskReasonCode.ORDER_RATE_EXCEEDED, RiskReasonCode.CANCEL_RATE_EXCEEDED, RiskReasonCode.SYMBOL_POSITION_EXCEEDED, RiskReasonCode.GROSS_EXPOSURE_EXCEEDED, RiskReasonCode.NET_EXPOSURE_EXCEEDED, RiskReasonCode.SECTOR_CONCENTRATION_EXCEEDED, RiskReasonCode.FACTOR_EXPOSURE_EXCEEDED, RiskReasonCode.DAILY_LOSS_EXCEEDED, RiskReasonCode.STRATEGY_LOSS_EXCEEDED, RiskReasonCode.DRAWDOWN_EXCEEDED, RiskReasonCode.CREDIT_CAPITAL_EXCEEDED, RiskReasonCode.SHORT_SALE_LOCATE_DENIED, RiskReasonCode.SELF_TRADE_PREVENTION_DENIED, RiskReasonCode.VENUE_UNAUTHORIZED, RiskReasonCode.CONFIGURATION_STALE, RiskReasonCode.STALE_POSITION, RiskReasonCode.RISK_STATE_UNAVAILABLE, RiskReasonCode.CONFIGURATION_ROLLBACK, RiskReasonCode.SPLIT_BRAIN_EPOCH, RiskReasonCode.ARITHMETIC_OVERFLOW, RiskReasonCode.JOURNAL_UNAVAILABLE, RiskReasonCode.ENGINE_BUSY]: ...
  def ApprovedQuantityUnit(self) -> typing.Literal[QuantityUnit.UNKNOWN, QuantityUnit.INSTRUMENT_UNITS]: ...
  def ApprovedQuantityUnits(self) -> int: ...
  def IntentSha256(self) -> Sha256Digest | None: ...
  def EvaluatedProcessMonotonicTime(self) -> ProcessMonotonicTimeNs | None: ...
  def ValidUntilProcessMonotonicTime(self) -> ProcessMonotonicTimeNs | None: ...
  def AccountId(self) -> AccountId | None: ...
  def StrategyId(self) -> StrategyId | None: ...
  def VenueId(self) -> VenueId | None: ...
  def InstrumentId(self) -> InstrumentId | None: ...
  def IntentAction(self) -> typing.Literal[IntentAction.UNKNOWN, IntentAction.BUY, IntentAction.SELL, IntentAction.CANCEL]: ...
  def TradingMode(self) -> typing.Literal[TradingModeCode.UNKNOWN, TradingModeCode.SIMULATION, TradingModeCode.PAPER, TradingModeCode.LIVE]: ...
  def FailedCheck(self) -> typing.Literal[RiskCheckCode.NONE, RiskCheckCode.TRADING_MODE_AUTHORIZATION, RiskCheckCode.OPERATOR_SESSION_AUTHORIZATION, RiskCheckCode.STRATEGY_AUTHORIZATION, RiskCheckCode.SYMBOL_AUTHORIZATION, RiskCheckCode.RESTRICTED_LIST, RiskCheckCode.MARKET_STATE, RiskCheckCode.HALT, RiskCheckCode.CLOCK_HEALTH, RiskCheckCode.FEED_BOOK_HEALTH, RiskCheckCode.MAXIMUM_ORDER_QUANTITY, RiskCheckCode.MAXIMUM_ORDER_NOTIONAL, RiskCheckCode.PRICE_COLLAR, RiskCheckCode.TICK_SIZE, RiskCheckCode.DUPLICATE_INTENT, RiskCheckCode.ORDER_RATE, RiskCheckCode.CANCEL_RATE, RiskCheckCode.SYMBOL_POSITION, RiskCheckCode.GROSS_EXPOSURE, RiskCheckCode.NET_EXPOSURE, RiskCheckCode.SECTOR_CONCENTRATION, RiskCheckCode.FACTOR_EXPOSURE, RiskCheckCode.DAILY_LOSS, RiskCheckCode.STRATEGY_LOSS, RiskCheckCode.DRAWDOWN, RiskCheckCode.CREDIT_CAPITAL, RiskCheckCode.SHORT_SALE_LOCATE, RiskCheckCode.SELF_TRADE_PREVENTION, RiskCheckCode.VENUE_AUTHORIZATION, RiskCheckCode.KILL_SWITCH, RiskCheckCode.CONFIGURATION_FRESHNESS]: ...
  def ApprovedPriceUnit(self) -> typing.Literal[PriceUnit.UNKNOWN, PriceUnit.TICKS]: ...
  def ApprovedPriceTicks(self) -> int: ...
  def IntentHash(self) -> int: ...
  def RiskSnapshotHash(self) -> int: ...
  def RiskContextHash(self) -> int: ...
  def PositionGeneration(self) -> int: ...
  def AuthorityEpoch(self) -> int: ...
  def PolicyRevision(self) -> int: ...
  def EvaluationOrdinal(self) -> int: ...
  def JournalSequence(self) -> int: ...
  def ReasonMask(self) -> int: ...
  def CompletedCheckMask(self) -> int: ...
  def DecisionHash(self) -> int: ...
def RiskDecisionStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def RiskDecisionAddSchemaVersion(builder: flatbuffers.Builder, schemaVersion: uoffset) -> None: ...
def RiskDecisionAddGlobalEventId(builder: flatbuffers.Builder, globalEventId: uoffset) -> None: ...
def RiskDecisionAddIntentId(builder: flatbuffers.Builder, intentId: uoffset) -> None: ...
def RiskDecisionAddSessionId(builder: flatbuffers.Builder, sessionId: uoffset) -> None: ...
def RiskDecisionAddRiskSnapshotId(builder: flatbuffers.Builder, riskSnapshotId: uoffset) -> None: ...
def RiskDecisionAddConfigurationVersion(builder: flatbuffers.Builder, configurationVersion: uoffset) -> None: ...
def RiskDecisionAddDecision(builder: flatbuffers.Builder, decision: typing.Literal[RiskDecisionCode.UNKNOWN, RiskDecisionCode.REJECTED, RiskDecisionCode.APPROVED]) -> None: ...
def RiskDecisionAddReason(builder: flatbuffers.Builder, reason: typing.Literal[RiskReasonCode.UNKNOWN, RiskReasonCode.WITHIN_LIMITS, RiskReasonCode.KILL_SWITCH_ENGAGED, RiskReasonCode.STALE_MARKET_DATA, RiskReasonCode.INVALID_BOOK, RiskReasonCode.CLOCK_UNSYNCHRONIZED, RiskReasonCode.LIMIT_EXCEEDED, RiskReasonCode.INVALID_INTENT, RiskReasonCode.CONFIGURATION_MISMATCH, RiskReasonCode.EXPIRED_INTENT, RiskReasonCode.TRADING_MODE_UNAUTHORIZED, RiskReasonCode.OPERATOR_SESSION_UNAUTHORIZED, RiskReasonCode.STRATEGY_UNAUTHORIZED, RiskReasonCode.SYMBOL_UNAUTHORIZED, RiskReasonCode.RESTRICTED_INSTRUMENT, RiskReasonCode.MARKET_STATE_UNSAFE, RiskReasonCode.TRADING_HALTED, RiskReasonCode.FEED_BOOK_UNHEALTHY, RiskReasonCode.ORDER_QUANTITY_EXCEEDED, RiskReasonCode.ORDER_NOTIONAL_EXCEEDED, RiskReasonCode.PRICE_COLLAR_EXCEEDED, RiskReasonCode.INVALID_TICK_SIZE, RiskReasonCode.DUPLICATE_INTENT, RiskReasonCode.ORDER_RATE_EXCEEDED, RiskReasonCode.CANCEL_RATE_EXCEEDED, RiskReasonCode.SYMBOL_POSITION_EXCEEDED, RiskReasonCode.GROSS_EXPOSURE_EXCEEDED, RiskReasonCode.NET_EXPOSURE_EXCEEDED, RiskReasonCode.SECTOR_CONCENTRATION_EXCEEDED, RiskReasonCode.FACTOR_EXPOSURE_EXCEEDED, RiskReasonCode.DAILY_LOSS_EXCEEDED, RiskReasonCode.STRATEGY_LOSS_EXCEEDED, RiskReasonCode.DRAWDOWN_EXCEEDED, RiskReasonCode.CREDIT_CAPITAL_EXCEEDED, RiskReasonCode.SHORT_SALE_LOCATE_DENIED, RiskReasonCode.SELF_TRADE_PREVENTION_DENIED, RiskReasonCode.VENUE_UNAUTHORIZED, RiskReasonCode.CONFIGURATION_STALE, RiskReasonCode.STALE_POSITION, RiskReasonCode.RISK_STATE_UNAVAILABLE, RiskReasonCode.CONFIGURATION_ROLLBACK, RiskReasonCode.SPLIT_BRAIN_EPOCH, RiskReasonCode.ARITHMETIC_OVERFLOW, RiskReasonCode.JOURNAL_UNAVAILABLE, RiskReasonCode.ENGINE_BUSY]) -> None: ...
def RiskDecisionAddApprovedQuantityUnit(builder: flatbuffers.Builder, approvedQuantityUnit: typing.Literal[QuantityUnit.UNKNOWN, QuantityUnit.INSTRUMENT_UNITS]) -> None: ...
def RiskDecisionAddApprovedQuantityUnits(builder: flatbuffers.Builder, approvedQuantityUnits: int) -> None: ...
def RiskDecisionAddIntentSha256(builder: flatbuffers.Builder, intentSha256: uoffset) -> None: ...
def RiskDecisionAddEvaluatedProcessMonotonicTime(builder: flatbuffers.Builder, evaluatedProcessMonotonicTime: uoffset) -> None: ...
def RiskDecisionAddValidUntilProcessMonotonicTime(builder: flatbuffers.Builder, validUntilProcessMonotonicTime: uoffset) -> None: ...
def RiskDecisionAddAccountId(builder: flatbuffers.Builder, accountId: uoffset) -> None: ...
def RiskDecisionAddStrategyId(builder: flatbuffers.Builder, strategyId: uoffset) -> None: ...
def RiskDecisionAddVenueId(builder: flatbuffers.Builder, venueId: uoffset) -> None: ...
def RiskDecisionAddInstrumentId(builder: flatbuffers.Builder, instrumentId: uoffset) -> None: ...
def RiskDecisionAddIntentAction(builder: flatbuffers.Builder, intentAction: typing.Literal[IntentAction.UNKNOWN, IntentAction.BUY, IntentAction.SELL, IntentAction.CANCEL]) -> None: ...
def RiskDecisionAddTradingMode(builder: flatbuffers.Builder, tradingMode: typing.Literal[TradingModeCode.UNKNOWN, TradingModeCode.SIMULATION, TradingModeCode.PAPER, TradingModeCode.LIVE]) -> None: ...
def RiskDecisionAddFailedCheck(builder: flatbuffers.Builder, failedCheck: typing.Literal[RiskCheckCode.NONE, RiskCheckCode.TRADING_MODE_AUTHORIZATION, RiskCheckCode.OPERATOR_SESSION_AUTHORIZATION, RiskCheckCode.STRATEGY_AUTHORIZATION, RiskCheckCode.SYMBOL_AUTHORIZATION, RiskCheckCode.RESTRICTED_LIST, RiskCheckCode.MARKET_STATE, RiskCheckCode.HALT, RiskCheckCode.CLOCK_HEALTH, RiskCheckCode.FEED_BOOK_HEALTH, RiskCheckCode.MAXIMUM_ORDER_QUANTITY, RiskCheckCode.MAXIMUM_ORDER_NOTIONAL, RiskCheckCode.PRICE_COLLAR, RiskCheckCode.TICK_SIZE, RiskCheckCode.DUPLICATE_INTENT, RiskCheckCode.ORDER_RATE, RiskCheckCode.CANCEL_RATE, RiskCheckCode.SYMBOL_POSITION, RiskCheckCode.GROSS_EXPOSURE, RiskCheckCode.NET_EXPOSURE, RiskCheckCode.SECTOR_CONCENTRATION, RiskCheckCode.FACTOR_EXPOSURE, RiskCheckCode.DAILY_LOSS, RiskCheckCode.STRATEGY_LOSS, RiskCheckCode.DRAWDOWN, RiskCheckCode.CREDIT_CAPITAL, RiskCheckCode.SHORT_SALE_LOCATE, RiskCheckCode.SELF_TRADE_PREVENTION, RiskCheckCode.VENUE_AUTHORIZATION, RiskCheckCode.KILL_SWITCH, RiskCheckCode.CONFIGURATION_FRESHNESS]) -> None: ...
def RiskDecisionAddApprovedPriceUnit(builder: flatbuffers.Builder, approvedPriceUnit: typing.Literal[PriceUnit.UNKNOWN, PriceUnit.TICKS]) -> None: ...
def RiskDecisionAddApprovedPriceTicks(builder: flatbuffers.Builder, approvedPriceTicks: int) -> None: ...
def RiskDecisionAddIntentHash(builder: flatbuffers.Builder, intentHash: int) -> None: ...
def RiskDecisionAddRiskSnapshotHash(builder: flatbuffers.Builder, riskSnapshotHash: int) -> None: ...
def RiskDecisionAddRiskContextHash(builder: flatbuffers.Builder, riskContextHash: int) -> None: ...
def RiskDecisionAddPositionGeneration(builder: flatbuffers.Builder, positionGeneration: int) -> None: ...
def RiskDecisionAddAuthorityEpoch(builder: flatbuffers.Builder, authorityEpoch: int) -> None: ...
def RiskDecisionAddPolicyRevision(builder: flatbuffers.Builder, policyRevision: int) -> None: ...
def RiskDecisionAddEvaluationOrdinal(builder: flatbuffers.Builder, evaluationOrdinal: int) -> None: ...
def RiskDecisionAddJournalSequence(builder: flatbuffers.Builder, journalSequence: int) -> None: ...
def RiskDecisionAddReasonMask(builder: flatbuffers.Builder, reasonMask: int) -> None: ...
def RiskDecisionAddCompletedCheckMask(builder: flatbuffers.Builder, completedCheckMask: int) -> None: ...
def RiskDecisionAddDecisionHash(builder: flatbuffers.Builder, decisionHash: int) -> None: ...
def RiskDecisionEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

