# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from aegis.mx.contracts.v1.AccountId import AccountId
from aegis.mx.contracts.v1.ConfigurationVersion import ConfigurationVersion
from aegis.mx.contracts.v1.GlobalEventId import GlobalEventId
from aegis.mx.contracts.v1.InstrumentId import InstrumentId
from aegis.mx.contracts.v1.IntentId import IntentId
from aegis.mx.contracts.v1.ProcessMonotonicTimeNs import ProcessMonotonicTimeNs
from aegis.mx.contracts.v1.RiskSnapshotId import RiskSnapshotId
from aegis.mx.contracts.v1.SchemaVersion import SchemaVersion
from aegis.mx.contracts.v1.SessionId import SessionId
from aegis.mx.contracts.v1.Sha256Digest import Sha256Digest
from aegis.mx.contracts.v1.StrategyId import StrategyId
from aegis.mx.contracts.v1.VenueId import VenueId
from typing import Optional
np = import_numpy()

class RiskDecision(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RiskDecision()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRiskDecision(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # RiskDecision
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RiskDecision
    def SchemaVersion(self) -> Optional[SchemaVersion]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            obj = SchemaVersion()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RiskDecision
    def GlobalEventId(self) -> Optional[GlobalEventId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            obj = GlobalEventId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RiskDecision
    def IntentId(self) -> Optional[IntentId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = o + self._tab.Pos
            obj = IntentId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RiskDecision
    def SessionId(self) -> Optional[SessionId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = o + self._tab.Pos
            obj = SessionId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RiskDecision
    def RiskSnapshotId(self) -> Optional[RiskSnapshotId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = o + self._tab.Pos
            obj = RiskSnapshotId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RiskDecision
    def ConfigurationVersion(self) -> Optional[ConfigurationVersion]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = o + self._tab.Pos
            obj = ConfigurationVersion()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RiskDecision
    def Decision(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # RiskDecision
    def Reason(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # RiskDecision
    def ApprovedQuantityUnit(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # RiskDecision
    def ApprovedQuantityUnits(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # RiskDecision
    def IntentSha256(self) -> Optional[Sha256Digest]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            x = o + self._tab.Pos
            obj = Sha256Digest()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RiskDecision
    def EvaluatedProcessMonotonicTime(self) -> Optional[ProcessMonotonicTimeNs]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            x = o + self._tab.Pos
            obj = ProcessMonotonicTimeNs()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RiskDecision
    def ValidUntilProcessMonotonicTime(self) -> Optional[ProcessMonotonicTimeNs]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            x = o + self._tab.Pos
            obj = ProcessMonotonicTimeNs()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RiskDecision
    def AccountId(self) -> Optional[AccountId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            x = o + self._tab.Pos
            obj = AccountId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RiskDecision
    def StrategyId(self) -> Optional[StrategyId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            x = o + self._tab.Pos
            obj = StrategyId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RiskDecision
    def VenueId(self) -> Optional[VenueId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            x = o + self._tab.Pos
            obj = VenueId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RiskDecision
    def InstrumentId(self) -> Optional[InstrumentId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        if o != 0:
            x = o + self._tab.Pos
            obj = InstrumentId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RiskDecision
    def IntentAction(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(38))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # RiskDecision
    def TradingMode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(40))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # RiskDecision
    def FailedCheck(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(42))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # RiskDecision
    def ApprovedPriceUnit(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(44))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # RiskDecision
    def ApprovedPriceTicks(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(46))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # RiskDecision
    def IntentHash(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(48))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # RiskDecision
    def RiskSnapshotHash(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(50))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # RiskDecision
    def RiskContextHash(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(52))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # RiskDecision
    def PositionGeneration(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(54))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # RiskDecision
    def AuthorityEpoch(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(56))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # RiskDecision
    def PolicyRevision(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(58))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # RiskDecision
    def EvaluationOrdinal(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(60))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # RiskDecision
    def JournalSequence(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(62))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # RiskDecision
    def ReasonMask(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(64))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # RiskDecision
    def CompletedCheckMask(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(66))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # RiskDecision
    def DecisionHash(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(68))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def RiskDecisionStart(builder: flatbuffers.Builder):
    builder.StartObject(33)

def Start(builder: flatbuffers.Builder):
    RiskDecisionStart(builder)

def RiskDecisionAddSchemaVersion(builder: flatbuffers.Builder, schemaVersion: Any):
    builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(schemaVersion), 0)

def AddSchemaVersion(builder: flatbuffers.Builder, schemaVersion: Any):
    RiskDecisionAddSchemaVersion(builder, schemaVersion)

def RiskDecisionAddGlobalEventId(builder: flatbuffers.Builder, globalEventId: Any):
    builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(globalEventId), 0)

def AddGlobalEventId(builder: flatbuffers.Builder, globalEventId: Any):
    RiskDecisionAddGlobalEventId(builder, globalEventId)

def RiskDecisionAddIntentId(builder: flatbuffers.Builder, intentId: Any):
    builder.PrependStructSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(intentId), 0)

def AddIntentId(builder: flatbuffers.Builder, intentId: Any):
    RiskDecisionAddIntentId(builder, intentId)

def RiskDecisionAddSessionId(builder: flatbuffers.Builder, sessionId: Any):
    builder.PrependStructSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(sessionId), 0)

def AddSessionId(builder: flatbuffers.Builder, sessionId: Any):
    RiskDecisionAddSessionId(builder, sessionId)

def RiskDecisionAddRiskSnapshotId(builder: flatbuffers.Builder, riskSnapshotId: Any):
    builder.PrependStructSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(riskSnapshotId), 0)

def AddRiskSnapshotId(builder: flatbuffers.Builder, riskSnapshotId: Any):
    RiskDecisionAddRiskSnapshotId(builder, riskSnapshotId)

def RiskDecisionAddConfigurationVersion(builder: flatbuffers.Builder, configurationVersion: Any):
    builder.PrependStructSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(configurationVersion), 0)

def AddConfigurationVersion(builder: flatbuffers.Builder, configurationVersion: Any):
    RiskDecisionAddConfigurationVersion(builder, configurationVersion)

def RiskDecisionAddDecision(builder: flatbuffers.Builder, decision: int):
    builder.PrependUint8Slot(6, decision, 0)

def AddDecision(builder: flatbuffers.Builder, decision: int):
    RiskDecisionAddDecision(builder, decision)

def RiskDecisionAddReason(builder: flatbuffers.Builder, reason: int):
    builder.PrependUint16Slot(7, reason, 0)

def AddReason(builder: flatbuffers.Builder, reason: int):
    RiskDecisionAddReason(builder, reason)

def RiskDecisionAddApprovedQuantityUnit(builder: flatbuffers.Builder, approvedQuantityUnit: int):
    builder.PrependUint8Slot(8, approvedQuantityUnit, 0)

def AddApprovedQuantityUnit(builder: flatbuffers.Builder, approvedQuantityUnit: int):
    RiskDecisionAddApprovedQuantityUnit(builder, approvedQuantityUnit)

def RiskDecisionAddApprovedQuantityUnits(builder: flatbuffers.Builder, approvedQuantityUnits: int):
    builder.PrependUint64Slot(9, approvedQuantityUnits, 0)

def AddApprovedQuantityUnits(builder: flatbuffers.Builder, approvedQuantityUnits: int):
    RiskDecisionAddApprovedQuantityUnits(builder, approvedQuantityUnits)

def RiskDecisionAddIntentSha256(builder: flatbuffers.Builder, intentSha256: Any):
    builder.PrependStructSlot(10, flatbuffers.number_types.UOffsetTFlags.py_type(intentSha256), 0)

def AddIntentSha256(builder: flatbuffers.Builder, intentSha256: Any):
    RiskDecisionAddIntentSha256(builder, intentSha256)

def RiskDecisionAddEvaluatedProcessMonotonicTime(builder: flatbuffers.Builder, evaluatedProcessMonotonicTime: Any):
    builder.PrependStructSlot(11, flatbuffers.number_types.UOffsetTFlags.py_type(evaluatedProcessMonotonicTime), 0)

def AddEvaluatedProcessMonotonicTime(builder: flatbuffers.Builder, evaluatedProcessMonotonicTime: Any):
    RiskDecisionAddEvaluatedProcessMonotonicTime(builder, evaluatedProcessMonotonicTime)

def RiskDecisionAddValidUntilProcessMonotonicTime(builder: flatbuffers.Builder, validUntilProcessMonotonicTime: Any):
    builder.PrependStructSlot(12, flatbuffers.number_types.UOffsetTFlags.py_type(validUntilProcessMonotonicTime), 0)

def AddValidUntilProcessMonotonicTime(builder: flatbuffers.Builder, validUntilProcessMonotonicTime: Any):
    RiskDecisionAddValidUntilProcessMonotonicTime(builder, validUntilProcessMonotonicTime)

def RiskDecisionAddAccountId(builder: flatbuffers.Builder, accountId: Any):
    builder.PrependStructSlot(13, flatbuffers.number_types.UOffsetTFlags.py_type(accountId), 0)

def AddAccountId(builder: flatbuffers.Builder, accountId: Any):
    RiskDecisionAddAccountId(builder, accountId)

def RiskDecisionAddStrategyId(builder: flatbuffers.Builder, strategyId: Any):
    builder.PrependStructSlot(14, flatbuffers.number_types.UOffsetTFlags.py_type(strategyId), 0)

def AddStrategyId(builder: flatbuffers.Builder, strategyId: Any):
    RiskDecisionAddStrategyId(builder, strategyId)

def RiskDecisionAddVenueId(builder: flatbuffers.Builder, venueId: Any):
    builder.PrependStructSlot(15, flatbuffers.number_types.UOffsetTFlags.py_type(venueId), 0)

def AddVenueId(builder: flatbuffers.Builder, venueId: Any):
    RiskDecisionAddVenueId(builder, venueId)

def RiskDecisionAddInstrumentId(builder: flatbuffers.Builder, instrumentId: Any):
    builder.PrependStructSlot(16, flatbuffers.number_types.UOffsetTFlags.py_type(instrumentId), 0)

def AddInstrumentId(builder: flatbuffers.Builder, instrumentId: Any):
    RiskDecisionAddInstrumentId(builder, instrumentId)

def RiskDecisionAddIntentAction(builder: flatbuffers.Builder, intentAction: int):
    builder.PrependUint8Slot(17, intentAction, 0)

def AddIntentAction(builder: flatbuffers.Builder, intentAction: int):
    RiskDecisionAddIntentAction(builder, intentAction)

def RiskDecisionAddTradingMode(builder: flatbuffers.Builder, tradingMode: int):
    builder.PrependUint8Slot(18, tradingMode, 0)

def AddTradingMode(builder: flatbuffers.Builder, tradingMode: int):
    RiskDecisionAddTradingMode(builder, tradingMode)

def RiskDecisionAddFailedCheck(builder: flatbuffers.Builder, failedCheck: int):
    builder.PrependUint8Slot(19, failedCheck, 0)

def AddFailedCheck(builder: flatbuffers.Builder, failedCheck: int):
    RiskDecisionAddFailedCheck(builder, failedCheck)

def RiskDecisionAddApprovedPriceUnit(builder: flatbuffers.Builder, approvedPriceUnit: int):
    builder.PrependUint8Slot(20, approvedPriceUnit, 0)

def AddApprovedPriceUnit(builder: flatbuffers.Builder, approvedPriceUnit: int):
    RiskDecisionAddApprovedPriceUnit(builder, approvedPriceUnit)

def RiskDecisionAddApprovedPriceTicks(builder: flatbuffers.Builder, approvedPriceTicks: int):
    builder.PrependInt64Slot(21, approvedPriceTicks, 0)

def AddApprovedPriceTicks(builder: flatbuffers.Builder, approvedPriceTicks: int):
    RiskDecisionAddApprovedPriceTicks(builder, approvedPriceTicks)

def RiskDecisionAddIntentHash(builder: flatbuffers.Builder, intentHash: int):
    builder.PrependUint64Slot(22, intentHash, 0)

def AddIntentHash(builder: flatbuffers.Builder, intentHash: int):
    RiskDecisionAddIntentHash(builder, intentHash)

def RiskDecisionAddRiskSnapshotHash(builder: flatbuffers.Builder, riskSnapshotHash: int):
    builder.PrependUint64Slot(23, riskSnapshotHash, 0)

def AddRiskSnapshotHash(builder: flatbuffers.Builder, riskSnapshotHash: int):
    RiskDecisionAddRiskSnapshotHash(builder, riskSnapshotHash)

def RiskDecisionAddRiskContextHash(builder: flatbuffers.Builder, riskContextHash: int):
    builder.PrependUint64Slot(24, riskContextHash, 0)

def AddRiskContextHash(builder: flatbuffers.Builder, riskContextHash: int):
    RiskDecisionAddRiskContextHash(builder, riskContextHash)

def RiskDecisionAddPositionGeneration(builder: flatbuffers.Builder, positionGeneration: int):
    builder.PrependUint64Slot(25, positionGeneration, 0)

def AddPositionGeneration(builder: flatbuffers.Builder, positionGeneration: int):
    RiskDecisionAddPositionGeneration(builder, positionGeneration)

def RiskDecisionAddAuthorityEpoch(builder: flatbuffers.Builder, authorityEpoch: int):
    builder.PrependUint64Slot(26, authorityEpoch, 0)

def AddAuthorityEpoch(builder: flatbuffers.Builder, authorityEpoch: int):
    RiskDecisionAddAuthorityEpoch(builder, authorityEpoch)

def RiskDecisionAddPolicyRevision(builder: flatbuffers.Builder, policyRevision: int):
    builder.PrependUint64Slot(27, policyRevision, 0)

def AddPolicyRevision(builder: flatbuffers.Builder, policyRevision: int):
    RiskDecisionAddPolicyRevision(builder, policyRevision)

def RiskDecisionAddEvaluationOrdinal(builder: flatbuffers.Builder, evaluationOrdinal: int):
    builder.PrependUint64Slot(28, evaluationOrdinal, 0)

def AddEvaluationOrdinal(builder: flatbuffers.Builder, evaluationOrdinal: int):
    RiskDecisionAddEvaluationOrdinal(builder, evaluationOrdinal)

def RiskDecisionAddJournalSequence(builder: flatbuffers.Builder, journalSequence: int):
    builder.PrependUint64Slot(29, journalSequence, 0)

def AddJournalSequence(builder: flatbuffers.Builder, journalSequence: int):
    RiskDecisionAddJournalSequence(builder, journalSequence)

def RiskDecisionAddReasonMask(builder: flatbuffers.Builder, reasonMask: int):
    builder.PrependUint64Slot(30, reasonMask, 0)

def AddReasonMask(builder: flatbuffers.Builder, reasonMask: int):
    RiskDecisionAddReasonMask(builder, reasonMask)

def RiskDecisionAddCompletedCheckMask(builder: flatbuffers.Builder, completedCheckMask: int):
    builder.PrependUint32Slot(31, completedCheckMask, 0)

def AddCompletedCheckMask(builder: flatbuffers.Builder, completedCheckMask: int):
    RiskDecisionAddCompletedCheckMask(builder, completedCheckMask)

def RiskDecisionAddDecisionHash(builder: flatbuffers.Builder, decisionHash: int):
    builder.PrependUint64Slot(32, decisionHash, 0)

def AddDecisionHash(builder: flatbuffers.Builder, decisionHash: int):
    RiskDecisionAddDecisionHash(builder, decisionHash)

def RiskDecisionEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return RiskDecisionEnd(builder)
