from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Sha256Digest:
  @classmethod
  def SizeOf(cls) -> int: ...

  def Init(self, buf: bytes, pos: int) -> None: ...
  def Bytes(self, i: int) -> typing.List[int]: ...
  def BytesAsNumpy(self) -> np.ndarray: ...
  def BytesLength(self) -> int: ...
  def BytesIsNone(self) -> bool: ...

def CreateSha256Digest(builder: flatbuffers.Builder, bytes: int) -> uoffset: ...

