# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

class Sha256Digest(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls) -> int:
        return 32

    # Sha256Digest
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Sha256Digest
    def Bytes(self, j = None):
        if j is None:
            return [self._tab.Get(flatbuffers.number_types.Uint8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0 + i * 1)) for i in range(self.BytesLength())]
        elif j >= 0 and j < self.BytesLength():
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0 + j * 1))
        else:
            return None

    # Sha256Digest
    def BytesAsNumpy(self):
        return self._tab.GetArrayAsNumpy(flatbuffers.number_types.Uint8Flags, self._tab.Pos + 0, self.BytesLength())

    # Sha256Digest
    def BytesLength(self) -> int:
        return 32

    # Sha256Digest
    def BytesIsNone(self) -> bool:
        return False


def CreateSha256Digest(builder, bytes):
    builder.Prep(1, 32)
    for _idx0 in range(32 , 0, -1):
        builder.PrependUint8(bytes[_idx0-1])
    return builder.Offset()
