# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from aegis.mx.contracts.v1.ChannelId import ChannelId
from aegis.mx.contracts.v1.ExchangeEventTimeNs import ExchangeEventTimeNs
from aegis.mx.contracts.v1.GlobalEventId import GlobalEventId
from aegis.mx.contracts.v1.InstrumentId import InstrumentId
from aegis.mx.contracts.v1.NicReceiveTimeNs import NicReceiveTimeNs
from aegis.mx.contracts.v1.ProcessMonotonicTimeNs import ProcessMonotonicTimeNs
from aegis.mx.contracts.v1.SchemaVersion import SchemaVersion
from aegis.mx.contracts.v1.SessionId import SessionId
from aegis.mx.contracts.v1.VenueId import VenueId
from typing import Optional
np = import_numpy()

class TradeEvent(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TradeEvent()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTradeEvent(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # TradeEvent
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TradeEvent
    def SchemaVersion(self) -> Optional[SchemaVersion]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            obj = SchemaVersion()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TradeEvent
    def GlobalEventId(self) -> Optional[GlobalEventId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            obj = GlobalEventId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TradeEvent
    def SessionId(self) -> Optional[SessionId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = o + self._tab.Pos
            obj = SessionId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TradeEvent
    def VenueId(self) -> Optional[VenueId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = o + self._tab.Pos
            obj = VenueId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TradeEvent
    def InstrumentId(self) -> Optional[InstrumentId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = o + self._tab.Pos
            obj = InstrumentId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TradeEvent
    def ChannelId(self) -> Optional[ChannelId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = o + self._tab.Pos
            obj = ChannelId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TradeEvent
    def ChannelSequence(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # TradeEvent
    def ExchangeEventTime(self) -> Optional[ExchangeEventTimeNs]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            x = o + self._tab.Pos
            obj = ExchangeEventTimeNs()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TradeEvent
    def NicReceiveTime(self) -> Optional[NicReceiveTimeNs]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            x = o + self._tab.Pos
            obj = NicReceiveTimeNs()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TradeEvent
    def ProcessMonotonicTime(self) -> Optional[ProcessMonotonicTimeNs]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            x = o + self._tab.Pos
            obj = ProcessMonotonicTimeNs()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TradeEvent
    def AggressorSide(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # TradeEvent
    def PriceUnit(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # TradeEvent
    def PriceTicks(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # TradeEvent
    def QuantityUnit(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # TradeEvent
    def QuantityUnits(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # TradeEvent
    def VenueTradeId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def TradeEventStart(builder: flatbuffers.Builder):
    builder.StartObject(16)

def Start(builder: flatbuffers.Builder):
    TradeEventStart(builder)

def TradeEventAddSchemaVersion(builder: flatbuffers.Builder, schemaVersion: Any):
    builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(schemaVersion), 0)

def AddSchemaVersion(builder: flatbuffers.Builder, schemaVersion: Any):
    TradeEventAddSchemaVersion(builder, schemaVersion)

def TradeEventAddGlobalEventId(builder: flatbuffers.Builder, globalEventId: Any):
    builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(globalEventId), 0)

def AddGlobalEventId(builder: flatbuffers.Builder, globalEventId: Any):
    TradeEventAddGlobalEventId(builder, globalEventId)

def TradeEventAddSessionId(builder: flatbuffers.Builder, sessionId: Any):
    builder.PrependStructSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(sessionId), 0)

def AddSessionId(builder: flatbuffers.Builder, sessionId: Any):
    TradeEventAddSessionId(builder, sessionId)

def TradeEventAddVenueId(builder: flatbuffers.Builder, venueId: Any):
    builder.PrependStructSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(venueId), 0)

def AddVenueId(builder: flatbuffers.Builder, venueId: Any):
    TradeEventAddVenueId(builder, venueId)

def TradeEventAddInstrumentId(builder: flatbuffers.Builder, instrumentId: Any):
    builder.PrependStructSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(instrumentId), 0)

def AddInstrumentId(builder: flatbuffers.Builder, instrumentId: Any):
    TradeEventAddInstrumentId(builder, instrumentId)

def TradeEventAddChannelId(builder: flatbuffers.Builder, channelId: Any):
    builder.PrependStructSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(channelId), 0)

def AddChannelId(builder: flatbuffers.Builder, channelId: Any):
    TradeEventAddChannelId(builder, channelId)

def TradeEventAddChannelSequence(builder: flatbuffers.Builder, channelSequence: int):
    builder.PrependUint64Slot(6, channelSequence, 0)

def AddChannelSequence(builder: flatbuffers.Builder, channelSequence: int):
    TradeEventAddChannelSequence(builder, channelSequence)

def TradeEventAddExchangeEventTime(builder: flatbuffers.Builder, exchangeEventTime: Any):
    builder.PrependStructSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(exchangeEventTime), 0)

def AddExchangeEventTime(builder: flatbuffers.Builder, exchangeEventTime: Any):
    TradeEventAddExchangeEventTime(builder, exchangeEventTime)

def TradeEventAddNicReceiveTime(builder: flatbuffers.Builder, nicReceiveTime: Any):
    builder.PrependStructSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(nicReceiveTime), 0)

def AddNicReceiveTime(builder: flatbuffers.Builder, nicReceiveTime: Any):
    TradeEventAddNicReceiveTime(builder, nicReceiveTime)

def TradeEventAddProcessMonotonicTime(builder: flatbuffers.Builder, processMonotonicTime: Any):
    builder.PrependStructSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(processMonotonicTime), 0)

def AddProcessMonotonicTime(builder: flatbuffers.Builder, processMonotonicTime: Any):
    TradeEventAddProcessMonotonicTime(builder, processMonotonicTime)

def TradeEventAddAggressorSide(builder: flatbuffers.Builder, aggressorSide: int):
    builder.PrependUint8Slot(10, aggressorSide, 0)

def AddAggressorSide(builder: flatbuffers.Builder, aggressorSide: int):
    TradeEventAddAggressorSide(builder, aggressorSide)

def TradeEventAddPriceUnit(builder: flatbuffers.Builder, priceUnit: int):
    builder.PrependUint8Slot(11, priceUnit, 0)

def AddPriceUnit(builder: flatbuffers.Builder, priceUnit: int):
    TradeEventAddPriceUnit(builder, priceUnit)

def TradeEventAddPriceTicks(builder: flatbuffers.Builder, priceTicks: int):
    builder.PrependInt64Slot(12, priceTicks, 0)

def AddPriceTicks(builder: flatbuffers.Builder, priceTicks: int):
    TradeEventAddPriceTicks(builder, priceTicks)

def TradeEventAddQuantityUnit(builder: flatbuffers.Builder, quantityUnit: int):
    builder.PrependUint8Slot(13, quantityUnit, 0)

def AddQuantityUnit(builder: flatbuffers.Builder, quantityUnit: int):
    TradeEventAddQuantityUnit(builder, quantityUnit)

def TradeEventAddQuantityUnits(builder: flatbuffers.Builder, quantityUnits: int):
    builder.PrependUint64Slot(14, quantityUnits, 0)

def AddQuantityUnits(builder: flatbuffers.Builder, quantityUnits: int):
    TradeEventAddQuantityUnits(builder, quantityUnits)

def TradeEventAddVenueTradeId(builder: flatbuffers.Builder, venueTradeId: int):
    builder.PrependUint64Slot(15, venueTradeId, 0)

def AddVenueTradeId(builder: flatbuffers.Builder, venueTradeId: int):
    TradeEventAddVenueTradeId(builder, venueTradeId)

def TradeEventEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return TradeEventEnd(builder)
