# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

class TradingStatusCode(object):
    UNKNOWN = 0
    PRE_OPEN = 1
    OPEN = 2
    HALTED = 3
    AUCTION = 4
    CLOSED = 5
