# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from aegis.mx.contracts.v1.ChannelId import ChannelId
from aegis.mx.contracts.v1.ExchangeEventTimeNs import ExchangeEventTimeNs
from aegis.mx.contracts.v1.GlobalEventId import GlobalEventId
from aegis.mx.contracts.v1.InstrumentId import InstrumentId
from aegis.mx.contracts.v1.NicReceiveTimeNs import NicReceiveTimeNs
from aegis.mx.contracts.v1.ProcessMonotonicTimeNs import ProcessMonotonicTimeNs
from aegis.mx.contracts.v1.SchemaVersion import SchemaVersion
from aegis.mx.contracts.v1.SessionId import SessionId
from aegis.mx.contracts.v1.VenueId import VenueId
from typing import Optional
np = import_numpy()

class TradingStatus(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TradingStatus()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTradingStatus(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # TradingStatus
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TradingStatus
    def SchemaVersion(self) -> Optional[SchemaVersion]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            obj = SchemaVersion()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TradingStatus
    def GlobalEventId(self) -> Optional[GlobalEventId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            obj = GlobalEventId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TradingStatus
    def SessionId(self) -> Optional[SessionId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = o + self._tab.Pos
            obj = SessionId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TradingStatus
    def VenueId(self) -> Optional[VenueId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = o + self._tab.Pos
            obj = VenueId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TradingStatus
    def InstrumentId(self) -> Optional[InstrumentId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = o + self._tab.Pos
            obj = InstrumentId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TradingStatus
    def ChannelId(self) -> Optional[ChannelId]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = o + self._tab.Pos
            obj = ChannelId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TradingStatus
    def ChannelSequence(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # TradingStatus
    def ExchangeEventTime(self) -> Optional[ExchangeEventTimeNs]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            x = o + self._tab.Pos
            obj = ExchangeEventTimeNs()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TradingStatus
    def NicReceiveTime(self) -> Optional[NicReceiveTimeNs]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            x = o + self._tab.Pos
            obj = NicReceiveTimeNs()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TradingStatus
    def ProcessMonotonicTime(self) -> Optional[ProcessMonotonicTimeNs]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            x = o + self._tab.Pos
            obj = ProcessMonotonicTimeNs()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TradingStatus
    def Status(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # TradingStatus
    def ReasonCode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def TradingStatusStart(builder: flatbuffers.Builder):
    builder.StartObject(12)

def Start(builder: flatbuffers.Builder):
    TradingStatusStart(builder)

def TradingStatusAddSchemaVersion(builder: flatbuffers.Builder, schemaVersion: Any):
    builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(schemaVersion), 0)

def AddSchemaVersion(builder: flatbuffers.Builder, schemaVersion: Any):
    TradingStatusAddSchemaVersion(builder, schemaVersion)

def TradingStatusAddGlobalEventId(builder: flatbuffers.Builder, globalEventId: Any):
    builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(globalEventId), 0)

def AddGlobalEventId(builder: flatbuffers.Builder, globalEventId: Any):
    TradingStatusAddGlobalEventId(builder, globalEventId)

def TradingStatusAddSessionId(builder: flatbuffers.Builder, sessionId: Any):
    builder.PrependStructSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(sessionId), 0)

def AddSessionId(builder: flatbuffers.Builder, sessionId: Any):
    TradingStatusAddSessionId(builder, sessionId)

def TradingStatusAddVenueId(builder: flatbuffers.Builder, venueId: Any):
    builder.PrependStructSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(venueId), 0)

def AddVenueId(builder: flatbuffers.Builder, venueId: Any):
    TradingStatusAddVenueId(builder, venueId)

def TradingStatusAddInstrumentId(builder: flatbuffers.Builder, instrumentId: Any):
    builder.PrependStructSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(instrumentId), 0)

def AddInstrumentId(builder: flatbuffers.Builder, instrumentId: Any):
    TradingStatusAddInstrumentId(builder, instrumentId)

def TradingStatusAddChannelId(builder: flatbuffers.Builder, channelId: Any):
    builder.PrependStructSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(channelId), 0)

def AddChannelId(builder: flatbuffers.Builder, channelId: Any):
    TradingStatusAddChannelId(builder, channelId)

def TradingStatusAddChannelSequence(builder: flatbuffers.Builder, channelSequence: int):
    builder.PrependUint64Slot(6, channelSequence, 0)

def AddChannelSequence(builder: flatbuffers.Builder, channelSequence: int):
    TradingStatusAddChannelSequence(builder, channelSequence)

def TradingStatusAddExchangeEventTime(builder: flatbuffers.Builder, exchangeEventTime: Any):
    builder.PrependStructSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(exchangeEventTime), 0)

def AddExchangeEventTime(builder: flatbuffers.Builder, exchangeEventTime: Any):
    TradingStatusAddExchangeEventTime(builder, exchangeEventTime)

def TradingStatusAddNicReceiveTime(builder: flatbuffers.Builder, nicReceiveTime: Any):
    builder.PrependStructSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(nicReceiveTime), 0)

def AddNicReceiveTime(builder: flatbuffers.Builder, nicReceiveTime: Any):
    TradingStatusAddNicReceiveTime(builder, nicReceiveTime)

def TradingStatusAddProcessMonotonicTime(builder: flatbuffers.Builder, processMonotonicTime: Any):
    builder.PrependStructSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(processMonotonicTime), 0)

def AddProcessMonotonicTime(builder: flatbuffers.Builder, processMonotonicTime: Any):
    TradingStatusAddProcessMonotonicTime(builder, processMonotonicTime)

def TradingStatusAddStatus(builder: flatbuffers.Builder, status: int):
    builder.PrependUint8Slot(10, status, 0)

def AddStatus(builder: flatbuffers.Builder, status: int):
    TradingStatusAddStatus(builder, status)

def TradingStatusAddReasonCode(builder: flatbuffers.Builder, reasonCode: int):
    builder.PrependUint32Slot(11, reasonCode, 0)

def AddReasonCode(builder: flatbuffers.Builder, reasonCode: int):
    TradingStatusAddReasonCode(builder, reasonCode)

def TradingStatusEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return TradingStatusEnd(builder)
