from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from aegis.mx.contracts.v1.ChannelId import ChannelId
from aegis.mx.contracts.v1.ExchangeEventTimeNs import ExchangeEventTimeNs
from aegis.mx.contracts.v1.GlobalEventId import GlobalEventId
from aegis.mx.contracts.v1.InstrumentId import InstrumentId
from aegis.mx.contracts.v1.NicReceiveTimeNs import NicReceiveTimeNs
from aegis.mx.contracts.v1.PriceUnit import PriceUnit
from aegis.mx.contracts.v1.ProcessMonotonicTimeNs import ProcessMonotonicTimeNs
from aegis.mx.contracts.v1.QuantityUnit import QuantityUnit
from aegis.mx.contracts.v1.SchemaVersion import SchemaVersion
from aegis.mx.contracts.v1.SessionId import SessionId
from aegis.mx.contracts.v1.TradeSide import TradeSide
from aegis.mx.contracts.v1.VenueId import VenueId

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class TradeEvent:
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> TradeEvent: ...
  @classmethod
  def GetRootAsTradeEvent(cls, buf: bytes, offset: int) -> TradeEvent: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def SchemaVersion(self) -> SchemaVersion | None: ...
  def GlobalEventId(self) -> GlobalEventId | None: ...
  def SessionId(self) -> SessionId | None: ...
  def VenueId(self) -> VenueId | None: ...
  def InstrumentId(self) -> InstrumentId | None: ...
  def ChannelId(self) -> ChannelId | None: ...
  def ChannelSequence(self) -> int: ...
  def ExchangeEventTime(self) -> ExchangeEventTimeNs | None: ...
  def NicReceiveTime(self) -> NicReceiveTimeNs | None: ...
  def ProcessMonotonicTime(self) -> ProcessMonotonicTimeNs | None: ...
  def AggressorSide(self) -> typing.Literal[TradeSide.UNKNOWN, TradeSide.BUY, TradeSide.SELL, TradeSide.NOT_APPLICABLE]: ...
  def PriceUnit(self) -> typing.Literal[PriceUnit.UNKNOWN, PriceUnit.TICKS]: ...
  def PriceTicks(self) -> int: ...
  def QuantityUnit(self) -> typing.Literal[QuantityUnit.UNKNOWN, QuantityUnit.INSTRUMENT_UNITS]: ...
  def QuantityUnits(self) -> int: ...
  def VenueTradeId(self) -> int: ...
def TradeEventStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def TradeEventAddSchemaVersion(builder: flatbuffers.Builder, schemaVersion: uoffset) -> None: ...
def TradeEventAddGlobalEventId(builder: flatbuffers.Builder, globalEventId: uoffset) -> None: ...
def TradeEventAddSessionId(builder: flatbuffers.Builder, sessionId: uoffset) -> None: ...
def TradeEventAddVenueId(builder: flatbuffers.Builder, venueId: uoffset) -> None: ...
def TradeEventAddInstrumentId(builder: flatbuffers.Builder, instrumentId: uoffset) -> None: ...
def TradeEventAddChannelId(builder: flatbuffers.Builder, channelId: uoffset) -> None: ...
def TradeEventAddChannelSequence(builder: flatbuffers.Builder, channelSequence: int) -> None: ...
def TradeEventAddExchangeEventTime(builder: flatbuffers.Builder, exchangeEventTime: uoffset) -> None: ...
def TradeEventAddNicReceiveTime(builder: flatbuffers.Builder, nicReceiveTime: uoffset) -> None: ...
def TradeEventAddProcessMonotonicTime(builder: flatbuffers.Builder, processMonotonicTime: uoffset) -> None: ...
def TradeEventAddAggressorSide(builder: flatbuffers.Builder, aggressorSide: typing.Literal[TradeSide.UNKNOWN, TradeSide.BUY, TradeSide.SELL, TradeSide.NOT_APPLICABLE]) -> None: ...
def TradeEventAddPriceUnit(builder: flatbuffers.Builder, priceUnit: typing.Literal[PriceUnit.UNKNOWN, PriceUnit.TICKS]) -> None: ...
def TradeEventAddPriceTicks(builder: flatbuffers.Builder, priceTicks: int) -> None: ...
def TradeEventAddQuantityUnit(builder: flatbuffers.Builder, quantityUnit: typing.Literal[QuantityUnit.UNKNOWN, QuantityUnit.INSTRUMENT_UNITS]) -> None: ...
def TradeEventAddQuantityUnits(builder: flatbuffers.Builder, quantityUnits: int) -> None: ...
def TradeEventAddVenueTradeId(builder: flatbuffers.Builder, venueTradeId: int) -> None: ...
def TradeEventEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

