from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from aegis.mx.contracts.v1.ChannelId import ChannelId
from aegis.mx.contracts.v1.ExchangeEventTimeNs import ExchangeEventTimeNs
from aegis.mx.contracts.v1.GlobalEventId import GlobalEventId
from aegis.mx.contracts.v1.InstrumentId import InstrumentId
from aegis.mx.contracts.v1.NicReceiveTimeNs import NicReceiveTimeNs
from aegis.mx.contracts.v1.ProcessMonotonicTimeNs import ProcessMonotonicTimeNs
from aegis.mx.contracts.v1.SchemaVersion import SchemaVersion
from aegis.mx.contracts.v1.SessionId import SessionId
from aegis.mx.contracts.v1.TradingStatusCode import TradingStatusCode
from aegis.mx.contracts.v1.VenueId import VenueId

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class TradingStatus:
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> TradingStatus: ...
  @classmethod
  def GetRootAsTradingStatus(cls, buf: bytes, offset: int) -> TradingStatus: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def SchemaVersion(self) -> SchemaVersion | None: ...
  def GlobalEventId(self) -> GlobalEventId | None: ...
  def SessionId(self) -> SessionId | None: ...
  def VenueId(self) -> VenueId | None: ...
  def InstrumentId(self) -> InstrumentId | None: ...
  def ChannelId(self) -> ChannelId | None: ...
  def ChannelSequence(self) -> int: ...
  def ExchangeEventTime(self) -> ExchangeEventTimeNs | None: ...
  def NicReceiveTime(self) -> NicReceiveTimeNs | None: ...
  def ProcessMonotonicTime(self) -> ProcessMonotonicTimeNs | None: ...
  def Status(self) -> typing.Literal[TradingStatusCode.UNKNOWN, TradingStatusCode.PRE_OPEN, TradingStatusCode.OPEN, TradingStatusCode.HALTED, TradingStatusCode.AUCTION, TradingStatusCode.CLOSED]: ...
  def ReasonCode(self) -> int: ...
def TradingStatusStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def TradingStatusAddSchemaVersion(builder: flatbuffers.Builder, schemaVersion: uoffset) -> None: ...
def TradingStatusAddGlobalEventId(builder: flatbuffers.Builder, globalEventId: uoffset) -> None: ...
def TradingStatusAddSessionId(builder: flatbuffers.Builder, sessionId: uoffset) -> None: ...
def TradingStatusAddVenueId(builder: flatbuffers.Builder, venueId: uoffset) -> None: ...
def TradingStatusAddInstrumentId(builder: flatbuffers.Builder, instrumentId: uoffset) -> None: ...
def TradingStatusAddChannelId(builder: flatbuffers.Builder, channelId: uoffset) -> None: ...
def TradingStatusAddChannelSequence(builder: flatbuffers.Builder, channelSequence: int) -> None: ...
def TradingStatusAddExchangeEventTime(builder: flatbuffers.Builder, exchangeEventTime: uoffset) -> None: ...
def TradingStatusAddNicReceiveTime(builder: flatbuffers.Builder, nicReceiveTime: uoffset) -> None: ...
def TradingStatusAddProcessMonotonicTime(builder: flatbuffers.Builder, processMonotonicTime: uoffset) -> None: ...
def TradingStatusAddStatus(builder: flatbuffers.Builder, status: typing.Literal[TradingStatusCode.UNKNOWN, TradingStatusCode.PRE_OPEN, TradingStatusCode.OPEN, TradingStatusCode.HALTED, TradingStatusCode.AUCTION, TradingStatusCode.CLOSED]) -> None: ...
def TradingStatusAddReasonCode(builder: flatbuffers.Builder, reasonCode: int) -> None: ...
def TradingStatusEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

