apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - admission-policy.yaml
  - autoscaling.yaml
  - disruption-budgets.yaml
  - gpu-quota.yaml
patches:
  - path: environment.yaml
  - path: production-workloads.yaml
