apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - resource-guardrails.yaml
  - service-accounts.yaml
  - runtime-config.yaml
  - service-config.yaml
  - workloads.yaml
  - services.yaml
  - network-policies.yaml
  - backup.yaml
